### PR TITLE
LPS-145063

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian ,

Resend.
As we discuss last week, I removed the unused properties "verify.patch.levels.disabled".
It was only used in MainServlet.java, and was removed based on commit 0a6c878, see LPS-137936.
I also update the commit message, and get rid of the commit message of cc1eca7.
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 Please see https://github.com/liferay-core-infra/liferay-portal/pull/183.

**Pull request closed without merging**
