### PR TITLE
[SampleSQLBuilder] LPS-113497 Content page as home page

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by slnn** [comment]
Hi @tinatian @dantewang 

After https://issues.liferay.com/browse/LPS-129423, the HelloWorld Widget has been deprecated and it also removed the usage in SampleSQLBuilder please see this commit of master: https://github.com/liferay/liferay-portal/commit/b36667826afdce3a9cf78015cdc265de97e216d6, so the home page generated by SampleSQLBuilder with the head of master is broken.

 /cc @GinsonRen

Regards
Lily

**Comment by dantewang** [comment]
@slnn The content page doesn't use Hello World portlet, just Login portlet, right?

**Comment by slnn** [comment]
> @slnn The content page doesn't use Hello World portlet, just Login portlet, right?

Yes, it is. The content page generated by SampleSQLBuilder only contains Login widget, no Hello Word widget.

**Comment by tinatian** [comment]
Conflicts, please resend.

Thanks.
Tina

**Pull request closed without merging**
