### PR TITLE
[TECHNICAL-SUPPORT] LPS-54494 ArrayIndexOutOfBoundsException occurs when there are more result than "index.search.limit" after LPS-44108

### PR DESCRIPTION
**Pull request by NorbertKocsis**
Tibi's comment:
"
https://issues.liferay.com/browse/LPS-54494
Caused by https://issues.liferay.com/browse/LPS-44108 liferay@ae0b424

It doesn't make sense to use the number of total possible hits (numHits) when it's greater than our internal limit, since those results will be unreachable for end-users.
"

Thanks!
Norbert

### CODE REVIEW

**Comment by tinatian** [comment]
Close, see email.

**Comment by lipusz** [comment]
Hi Tina,

Hi Tina,

>Could you please confirm if this is a bug in trunk?

Yes, it is, as I wrote on the LPS.

>Please make sure you actually see the extra results rather that just see " Showing *** results." on page foot. I think there might be a bug on UI, we can check it later.

Those results are reachable when paginating.

>Please note that "total" number here does not mean the number of result entries to be shown on page, it is the number of total hits of a search query. For example, you set "index.search.limit=5", and you did a search, suppose the number of hits should be 10, then "total=10", but the number of documents loaded to be shown is only 5.

I'm absolutely aware of this, the number of entries on a page is controlled by the search.container.default.delta.

So, I cannot see what your real concern is. Can you please explain it? Otherwise, please push it forward.

Thanks,

**Comment by lipusz** [comment]
Attached a reproduction video for master: https://issues.liferay.com/secure/attachment/128180/LPS-54494-master%40ea39faa-lucene-engine-reproduction.ogv

Notes for current (at the time of writing) HEAD of master@ ea39faa

There is a bug that prevents "Sample Data" to be added upon finishing the setup wizard, so instead of adding 25+ users manually, it's easier to set

````properties
    search.container.page.default.delta=5
    index.search.limit=10
````

and 10 plus users (so you'll have 11: Tes Test + 10 new).

Attached is a screencast for this scenario.

**Comment by lipusz** [comment]
ES doesn't use any of "index.*" properties, so the queries are not limited, that's why it works with ES engine.

According to a Zulip message from Mike, those properties & Lucene will be moved to a separate module in the near future, so I didn't spend time to fix something that might be refactored later.

>lucene will be moved to separate module and deprecated (e.g. no longer supported for 7)

**Comment by lipusz** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/1107

**Pull request closed without merging**
