### PR TITLE
LPS-100336 Remove META-INF/version/9/../ModuleUtil.class from jaxb-api

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Only removing this file doesn't seem to break Liferay on JDK11.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:jdk11

**Comment by dantewang** [comment]
ci:reopen

Liferay Continuous Integration <notifications@github.com> 于 2019年8月27日周二
17:29写道：

**Comment by dantewang** [comment]
The integration test failures seem to be irrelevant.
Hi @vicnate5, could you take a look at other results?

**Comment by vicnate5** [comment]
Test results look good to me.
@tinatian @dantewang

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8161

**Pull request closed without merging**
