### PR TITLE
[ResourceAction] LPS-112056 part 1 preparation

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian The goal is to only populate default actions, if needed, right after creating the bag, to make it easier for exposing and applying the ResourceActionsBag class.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
- tck-jdk8 is unique, didn't see this error in other PR, failed at test case V2DispatcherTests_SPEC2_19_DispatchServletEvent_dispatch1:
`     [exec] java.lang.AssertionError: Test case V2DispatcherTests_SPEC2_19_DispatchServletEvent_dispatch1 failed. 
     [exec] Exception: 
     [exec] 	at org.openqa.selenium.support.ui.ExpectedConditions.lambda$findElement$0(ExpectedConditions.java:896)
     [exec] 	at java.util.Optional.orElseThrow(Optional.java:290)
     [exec] 	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
     [exec] 	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44)
     [exec] 	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:206)
     [exec] 	at org.openqa.selenium.support.ui.ExpectedConditions$7.apply(ExpectedConditions.java:202)
     [exec] 	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:248)
     [exec] 	at javax.portlet.tck.driver.TCKTestDriver.processClickable(TCKTestDriver.java:405)
     [exec] 	at javax.portlet.tck.driver.TCKLiferayTestDriver.test(TCKLiferayTestDriver.java:163)`

- functional-upgrade-jboss72-mysql57-jdk8/3 and modules-integration-db2111-jdk8 failures are unrelated.

**Pull request closed without merging**
