### PR TITLE
LPS-87327 UI Fix

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Hai made changes to make the add-sample-data checkbox only be enabled when user tries to change database type, name or username (for Oracle). He made a GIF to show the effect: https://issues.liferay.com/secure/thumbnail/290338/_thumb_290338.png. If this is acceptable, I'll ask CNQA to update the functional tests and resend.

### CODE REVIEW

**Comment by dantewang** [comment]
Previous CI result: https://github.com/dantewang/liferay-portal/pull/909

SetupWizard related functional failures are expected.

**Comment by tinatian** [comment]
@dantewang unable to see the image clearly.

**Comment by dantewang** [comment]
@tinatian Sorry, copied wrong link. https://issues.liferay.com/secure/attachment/290338/after_fix.gif

**Comment by tinatian** [comment]
@dantewang Please fix functional tests and resend.

Tina.

**Pull request closed without merging**
