### PR TITLE
Lps 135570 9 23 3

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test result?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian This breaks non-tomcat app servers

### Wildfly 18
```
 ERROR [io.undertow.request] (default task-1) UT005023: Exception handling request to /web/guest: java.lang.IllegalArgumentException: UT010023: Request com.liferay.portal.web.internal.session.replication.SessionReplicationHttpServletRequestDelegate@1bc3a867 was not original or a wrapper
 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:116)
 	at com.liferay.portal.web.internal.session.replication.SessionReplicationFilter.doFilter(SessionReplicationFilter.java:79)
  ```
  https://testray.liferay.com/reports/production/logs/2021-09/test-1-30/test-portal-acceptance-pullrequest(master)/530/functional-smoke-wildfly180-mariadb104-jdk8/0/0/jenkins-console.txt.gz
  
 How to build Wildfly:
 1. Set app server property `app.server.type=wildfly`
 2. `ant -f build-dist.xml unzip-wildfly`
 3. `ant all`
 
### Weblogic
```
<Sep 24, 2021 7:15:00,095 AM GMT> <Error> <HTTP> <BEA-101020> <[ServletContext@1130571057[app:ROOT module:ROOT path:null spec-version:3.1]] Servlet failed with an Exception
java.lang.ClassCastException: com.liferay.portal.web.internal.session.replication.HttpServletRequestASMWrapper cannot be cast to weblogic.servlet.internal.ServletRequestImpl
	at weblogic.servlet.internal.ServletRequestImpl.getOriginalRequest(ServletRequestImpl.java:1654)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:71)
	at com.liferay.portal.web.internal.session.replication.SessionReplicationFilter.doFilter(SessionReplicationFilter.java:79)
	at com.liferay.shielded.container.internal.proxy.FilterWrapper.doFilter(FilterWrapper.java:79)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	Truncated. see log file for complete stacktrace
```
https://testray.liferay.com/reports/production/logs/2021-09/test-1-30/test-portal-acceptance-pullrequest(master)/530/functional-smoke-weblogic122-mysql57-jdk8/0/0/jenkins-console.txt.gz

 How to build Weblogic:
 1. Set app server property `app.server.type=weblogic`
 2. `ant -f build-dist.xml unzip-weblogic`
 3. `ant all`
  
###  Websphere
 ```
 WARN  [WebContainer : 0][code_jsp:161] {code="500", msg="java.lang.RuntimeException: SRV.8.2: RequestWrapper objects must extend ServletRequestWrapper or HttpServletRequestWrapper", uri=/web/guest}
java.lang.RuntimeException: SRV.8.2: RequestWrapper objects must extend ServletRequestWrapper or HttpServletRequestWrapper
	at com.ibm.wsspi.webcontainer.util.ServletUtil.unwrapRequest(ServletUtil.java:100) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.wsspi.webcontainer.util.ServletUtil.unwrapRequest(ServletUtil.java:64) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.wsspi.webcontainer.util.ServletUtil.unwrapRequest(ServletUtil.java:59) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:187) ~[com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:90) ~[com.ibm.ws.webcontainer.jar:?]
	at com.liferay.portal.web.internal.session.replication.SessionReplicationFilter.doFilter(SessionReplicationFilter.java:79) ~[com.liferay.portal.web.jar:?]
	at com.liferay.shielded.container.internal.proxy.FilterWrapper.doFilter(FilterWrapper.java:79) ~[com.liferay.shielded.container.impl.jar:?]
```
https://testray.liferay.com/reports/production/logs/2021-09/test-1-30/test-portal-acceptance-pullrequest(master)/530/functional-smoke-websphere90-mysql57-jdk8/0/0/jenkins-console.txt.gz

 How to build Websphere:
 1. [Instructions](https://liferay.atlassian.net/wiki/spaces/ENGCOREINFRA/pages/1650101378/Websphere)

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@tinatian This failure is also real https://testray.liferay.com/home/-/testray/case_results/1563870757, but it might be difficult to reproduce locally, could you take a look at [the log](https://testray.liferay.com/reports/production/logs/2021-09/test-1-30/test-portal-acceptance-pullrequest(master)/530/lpkg-startup-jdk8/0/0/jenkins-console.txt.gz) to see if there is an obvious issue?

```
    [junit] java.lang.ClassCastException: [B cannot be cast to com.liferay.portal.kernel.model.User
    [junit] 	at com.liferay.portal.events.ChannelSessionDestroyAction.run(ChannelSessionDestroyAction.java:40) ~[portal-impl.jar:?]
    [junit] 	at com.liferay.portal.kernel.events.SessionAction.processLifecycleEvent(SessionAction.java:28) ~[portal-kernel.jar:?]
    [junit] 	at com.liferay.portal.events.EventsProcessorUtil.process(EventsProcessorUtil.java:80) ~[portal-impl.jar:?]
    [junit] 	at com.liferay.portal.events.EventsProcessorUtil.process(EventsProcessorUtil.java:61) ~[portal-impl.jar:?]
    [junit] 	at com.liferay.portal.servlet.PortalSessionDestroyer.doPortalInit(PortalSessionDestroyer.java:124) ~[portal-impl.jar:?]
    [junit] 	at com.liferay.portal.kernel.util.BasePortalLifecycle.portalInit(BasePortalLifecycle.java:44) [portal-kernel.jar:?]
    [junit] 	at com.liferay.portal.kernel.util.PortalLifecycleUtil.register(PortalLifecycleUtil.java:75) [portal-kernel.jar:?]
    [junit] 	at com.liferay.portal.kernel.util.BasePortalLifecycle.registerPortalLifecycle(BasePortalLifecycle.java:59) [portal-kernel.jar:?]
    [junit] 	at com.liferay.portal.servlet.PortalSessionDestroyer.<init>(PortalSessionDestroyer.java:47) [portal-impl.jar:?]
    [junit] 	at com.liferay.portal.servlet.PortalSessionListener.sessionDestroyed(PortalSessionListener.java:70) [portal-impl.jar:?]
    [junit] 	at sun.reflect.GeneratedMethodAccessor305.invoke(Unknown Source) ~[?:?]
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
    [junit] 	at com.liferay.shielded.container.internal.proxy.ContextClassLoaderInvocationHandler.invoke(ContextClassLoaderInvocationHandler.java:43) [com.liferay.shielded.container.impl.jar:?]
    [junit] 	at com.liferay.shielded.container.internal.proxy.EventListenerInvocationHandler.invoke(EventListenerInvocationHandler.java:64) [com.liferay.shielded.container.impl.jar:?]
    [junit] 	at com.liferay.shielded.container.internal.proxy.HttpSessionListenerInvocationHandlerWrapper.invoke(HttpSessionListenerInvocationHandlerWrapper.java:54) [com.liferay.shielded.container.impl.jar:?]
    [junit] 	at com.sun.proxy.$Proxy3.sessionDestroyed(Unknown Source) [?:?]
    [junit] 	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:806) [catalina.jar:9.0.53]
    [junit] 	at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:660) [catalina.jar:9.0.53]
    [junit] 	at org.apache.catalina.session.ManagerBase.processExpires(ManagerBase.java:608) [catalina.jar:9.0.53]
    [junit] 	at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:591) [catalina.jar:9.0.53]
    [junit] 	at org.apache.catalina.core.StandardContext.backgroundProcess(StandardContext.java:5622) [catalina.jar:9.0.53]
    [junit] 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1365) [catalina.jar:9.0.53]
    [junit] 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1369) [catalina.jar:9.0.53]
    [junit] 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1369) [catalina.jar:9.0.53]
    [junit] 	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1347) [catalina.jar:9.0.53]
    [junit] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
    [junit] 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_121]
    [junit] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_121]
    [junit] 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_121]
    [junit] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
    [junit] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
    [junit] 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.53]
    [junit] 	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
    ```

**Pull request closed without merging**
