### PR TITLE
LPS-145076

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian ,

I removed Remove unused properties "auto.deploy.websphere.wsadmin.properties.file.name"  and "auto.deploy.websphere.wsadmin.app.name.suffixac" (which are removed based on commit 0329a4c1b9dfc0a89c300f2aa9a4a82d5fe86739, see LPS-61201). I also did the SF and update the propskey, propsvalue and verifyproperties.
Thanks for checking for me!

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 Please add this information to your commit message:
`which are removed based on commit e930ab6, see LPS-61201`

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 I did not notice your message was wrong, these two properties are actually removed by 0329a4c1b9dfc0a89c300f2aa9a4a82d5fe86739, not e930ab6f2b44e116a95a6390366a6c88d83d127e. Please resend.

Thanks.
Tina.

**Comment by jeffwu0724** [comment]
> @jeffwu0724 I did not notice your message was wrong, these two properties are actually removed by [0329a4c](https://github.com/tinatian/liferay-portal/commit/0329a4c1b9dfc0a89c300f2aa9a4a82d5fe86739), not [e930ab6](https://github.com/tinatian/liferay-portal/commit/e930ab6f2b44e116a95a6390366a6c88d83d127e). Please resend.
> 
> Thanks. Tina.

sorry my bad, I will resend it now, and will try again to track this file and learn how to find it is 0329a4c1b9dfc0a89c300f2aa9a4a82d5fe86739 instead. 
Thanks for pointing this out!

Best,
Jeff

**Pull request closed without merging**
