### PR TITLE
LPS-128860 Upgrade Report

### PR DESCRIPTION
**Pull request by achaparro**
Hi @tinatian,

Can you take a quick look at the changes and let us know if this a valid approach for the feature we discussed the other day?

Thanks.

cc/ @samziemer

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@achaparro @SamZiemer  
So with the code below, you are going to miss the log event before `UpgradeReport` service is ready, is this what you want? 
`	private static volatile UpgradeReport _upgradeReport =
		ServiceProxyFactory.newServiceTrackedInstance(
			UpgradeReport.class, UpgradeLogAppender.class, "_upgradeReport",
			false);
`

If you can accept the log event missing before `UpgradeReport` service is ready, I would like to do this :
1. Make `portal-upgrade-impl` publish a `LogAppender` service
2. In `DBUpgrader` add a service dependecy logic to wait for `LogAppender` service, once it is ready, add it to root logger.

This way, you won't need to change too much in portal-impl, most of the changes would in your `portal-upgrade-impl` including the switch property "upgrade.report.enabled"

**Comment by SamZiemer** [comment]
Hi @tinatian, thank you for your reply. 

Yes, I think we can accept missing some events before the UpgradeReport service is ready so I will implement your suggestions. I would like to ask for some clarification on step 2 that you mention, I am not sure what you mean by add a service dependency log to wait for the LogAppender service. Can you please elaborate on that?

Secondly, you mention adding the property to portal-upgrade-impl, but I am not sure where the property would go instead of having the usage of the property in DBUpgrader.java. Would you use the property to control whether the UpgradeReport service is ready or not?

**Comment by tinatian** [comment]
Hi @SamZiemer ,
For service dependecy, here is an example https://github.com/liferay/liferay-portal/blob/0d9a313b62bf392e02e5c37b9f14c9f37e075fdc/portal-kernel/src/com/liferay/portal/kernel/search/BaseSearchEngineConfigurator.java#L59 .

So in your `portal-upgrade-impl` module, you can decide to publish the LogAppender service or not based on your own configuration, this way, you can achieve same goal to generate the report or not.

Tina.

**Pull request closed without merging**
