### PR TITLE
[Log4J] LPS-128599 3-5

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian I squashed all the "apply" commits into one. I just got the chance to make sure compiling work by running `modules-compile-jdk8` locally as well as `compile-test` in portal-impl and portal-kernel.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/9829

**Pull request closed without merging**
