### PR TITLE
LPS-89659 Fix pmd: rethrow the exception to fail the test with message

### PR DESCRIPTION
**Pull request by dantewang**
Fix pmd failure: Assert.fail is not allowed in catch block

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Passed pmd-jdk8 in https://github.com/dantewang/liferay-portal/pull/1016#issuecomment-466900769

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
@jpince Wondering what does CI compare when determining which tests to run for ci:test:relevant. This PR has only a change in a unit test compared to liferay-portal/master. Should CI skip functional ones?

cc @tinatian

**Comment by jpince** [comment]
Dante, CI is not smart enough to know what kinds of tests to run. So it
will always run functional, int, and unit tests related to the modules that
have changed.

Ideally we'd be able to do this, but I don't think the CI Infrastructure
team will have bandwidth for this right now.

**Comment by dantewang** [comment]
Thanks @jpince

I thought that was already implemented...

Jason Pince <notifications@github.com> 于 2019年2月25日周一 23:16写道：

> Dante, CI is not smart enough to know what kinds of tests to run. So it
> will always run functional, int, and unit tests related to the modules that
> have changed.
>
> Ideally we'd be able to do this, but I don't think the CI Infrastructure
> team will have bandwidth for this right now.
>
> On Mon, Feb 25, 2019, 1:44 AM Liferay Continuous Integration <

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7396

**Pull request closed without merging**
