### PR TITLE
[portal-test-integration] LPS-101479 BaseLocalServiceTreeTestCase

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
Hi @vicnate5, do you know why this pull gets auto-closed? What does "pulls for reference master" mean?
Thanks!

**Comment by yichenroy** [comment]
ci:test:sf

**Comment by yichenroy** [comment]
@dantewang 
I believe the auto-close was a false alarm, it looks like the data sent from github to our webhook when you issued "ci:test:sf" may have been corrupted for unknown reasons causing it to auto-close.

I tried `ci:test:sf` again and it looked okay, can you also try `ci:test:sf` again to see if it auto-closes again?

cc @vicnate5 @pyoo47

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8283

**Pull request closed without merging**
