### PR TITLE
[Blog tuning] LPS-97259 Avoid massive hashing in PortalCache.get in SoyTofuCacheHandler for Soy-based UI components

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://issues.liferay.com/browse/LPS-97259 Benchmark result https://github.com/slnn/liferay-portal/pull/423#issuecomment-504913637

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @dantewang ,

Basically what you did is to store a specific mapping locally to avoid hashing, it is really weird to have this kind of code. Generally, it is a bad idea to use a list as key in a mapping cause it may be changed, the key is better to be an immutable object like string.

In this case, things we can do:
1) Wrap it in a new class so that you are going to use the default equals/hash from Object class
2) Generate a key based on current List

Please redo and resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7968

**Pull request closed without merging**
