### PR TITLE
Lps x ddm structure

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @slnn,
Please keep an eye on the ci result of this pull, if everything works fine, please run benchmark test with this pull. But I do not have an idea which test case this will affect, you can either debug locally to confirm which test case you should run or run every test case if more simpler to do.

cc @dantewang @shuyangzhou

Thanks.
Tina.

**Comment by dantewang** [comment]
@slnn We build DDM structure for Web Content and DL, please start with these two cases.
@tinatian How's the priority of this? Lily is off today for Women's Day.

**Comment by dantewang** [comment]
@tinatian BTW the Journal integration test failures seem to be real.

**Comment by tinatian** [comment]
Yes, it is. Thanks @dantewang ! I will fix it and send a new pull later.

Tina

**Pull request closed without merging**
