### PR TITLE
LPS-130118 Push down persistence.jar

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result?

Thanks.
Tina.

**Comment by dantewang** [comment]
@zhangyang0701 Could you double check the results? Thanks!

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@dantewang @tinatian Test results look good. Going to also trigger upgrades because we had another regression with one of the pushdowns that we only saw when upgrading.

@koor4356 please review the upgrade results in the morning

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by koor4356** [comment]
Okay

**Comment by koor4356** [comment]
Upgrade have been pending. There is also a file conflict.

**Comment by vicnate5** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
@vicnate5 @koor4356 Rebase and resend at https://github.com/shuyangzhou/liferay-portal/pull/9941.

**Pull request closed without merging**
