### PR TITLE
LPS-128171

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

This is rebased from [#9799](https://github.com/shuyangzhou/liferay-portal/pull/9799)
Hope this time it is correct!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Pull request closed without merging**
