### PR TITLE
LPS-103853 Upgrade JGroups to 4.1.6.Final

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
functional test failures are not related to this change.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8450

**Pull request closed without merging**
