### PR TITLE
[deprecation] LPS-106103 One additional method

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This method is not used by anyone, so instead of removing the deprecation mark we can remove the method.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result?

Thanks.
Tina.

**Comment by tinatian** [comment]
@vicnate5 No need to scan.
@dantewang We do not need this cause the class itself had been deprecated.

**Pull request closed without merging**
