### PR TITLE
LPS-79546 If defaultLogo do not enable "Delete" button, even if they come from a sequence like:

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Comes from https://github.com/shuyangzhou/liferay-portal-ee/pull/416

First commit is to disable delete button when editing the default group logo.
Second commit is because even if it appears as disable you can use change button to add a new logo, select a new one and before saving it the delete button gets enabled. Ideally to delete the recently uploaded, but since it's a temp file it should be enough to use the cancel button.

**Comment by tinatian** [comment]
@dantewang Please take this over.

Thanks.
Tina.

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@tinatian The behavior looks good to me with the bundle built from this pull with dxp profile enabled.

But I wonder if comparing the live group ID with the guest group ID is enough at https://github.com/tinatian/liferay-portal/pull/1707/commits/a6b737500bcabb044ad139e066a87bfe4db0c087#diff-28369baac3304e02952b989f8441788bR53. It's not hard to get the LayoutSet of the guest group and then get the actual logo ID.

cc @marianoalvarosaiz

**Comment by marianoalvarosaiz** [comment]
Hi @dantewang, @tinatian,
 do you have any updates about this issue?
Kind regards.

**Comment by dantewang** [comment]
@marianoalvarosaiz Please see my comment. I'd prefer comparing the actual logo ID against the logo ID of the guest group, instead of comparing live group id against guest group ID. Or do you have a strong evidence that comparing group IDs is enough?

**Comment by marianoalvarosaiz** [comment]
see https://github.com/tinatian/liferay-portal/pull/1717

**Pull request closed without merging**
