### PR TITLE
Lps 111631

### PR DESCRIPTION
**Pull request by mtambara**
This didn't show up in master because of a special case with config files. Kyle is going to add a test to catch this in the future

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:test:search-es7

**Comment by tinatian** [comment]
@mtambara Is the test result for es7 good to go?

Tina

**Comment by mtambara** [comment]
Yes, it’s good to go

**Comment by tinatian** [comment]
ci:forward

**Comment by tinatian** [comment]
FYI @shuyangzhou

**Pull request closed without merging**
