### PR TITLE
[portal-impl-integration] LPS-98029 Cleanup or Move export-import *TestCase from portal-test-integration

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@tinatian Previous ci-test-backend-hypersonic result: https://github.com/dantewang/liferay-portal/pull/1230#issuecomment-514486907; SemVer has been fixed in this pull.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8048

**Pull request closed without merging**
