### PR TITLE
[Log4J] LPS-127261 packageinfo

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian LPS-127261 added a new method to Log4JUtil but didn't update the packageinfo. This causes CI failures, like https://issues.liferay.com/browse/LPS-127485

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/9824

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9825

**Pull request closed without merging**
