### PR TITLE
LPS-122557 git commit

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
@vicnate5 Is the failure real?

Thanks
Tina

**Comment by vicnate5** [comment]
@tinatian This failure looks to be due to the change that Brian made yesterday to strip out the plugins SDK
```
/opt/dev/projects/github/liferay-release-tool-ee/build-release-slim.xml:174: The following error occurred while executing this line:
Target "update-sdk-properties" does not exist in the project "portal".
```

Will send a fix.

**Comment by vicnate5** [comment]
@tinatian Add this to your release tool branch https://github.com/shuyangzhou/liferay-release-tool-ee/pull/42.

**Pull request closed without merging**
