### PR TITLE
LPS-86438

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@tinatian see https://github.com/brianchandotcom/liferay-portal/pull/64948

**Comment by epgarcia** [comment]
Hi @tinatian,

We want to cache the assignments of segments to entities. When either the segment or the entity changes, we want to clean that existing cache entry. Is it correct to remove portal cache like this? Or should I use a PortalCacheIndexer?

Thanks!

**Comment by tinatian** [comment]
Hi @epgarcia,
If you clean cache in this way by adding model listeners, it means if no one is going to use your feature, (nothing is in your cache), as long as your module gets deployed, those listeners are going to be there and invoked for everyone.

My concern is that the cache you added might not work as it supposed to improve performance. 

If you did some kind of performance test to verify this solution works, or at least it improves the performance for your feature, I think this change should be OK, but I would like to run our benchmark tests to verify it won't bring any regression to others before it got merged. 

If you did not do any test and just figured out this way by code analyzing, I would suggest we add the cache when there is a real performance issue.

What do you think? Feel free to let me know if you have any questions.


Thanks.
Tina.

**Comment by epgarcia** [comment]
Hi @tinatian,

Thanks for your prompt response. Indeed I'm anticipating performance issues when calculating the segments the a user is assigned to, but I haven't done any tests, yet. I'm fine with leaving this for later, and providing tests to justify caching. 

Regards

**Comment by tinatian** [comment]
Hi @epgarcia 

If you are going to add the cache later, could you please send a new pull to Brian about your change? I am going to close this pull for now. 

Please feel free to send me pulls about caching later if you are not sure about the change.

Tina.

**Comment by epgarcia** [comment]
@tinatian I will, thanks for your help!

**Pull request closed without merging**
