### PR TITLE
[SampleSQLBuilder] LPS-116679 Move CSV writers out of DataFactory

### PR DESCRIPTION
**Pull request by dantewang**
cc @slnn @GinsonRen please verify functionality

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by slnn** [comment]
Hi @dantewang 

I tested this pull with my laptop on web content test case, the csv files looks normal, @GinsonRen will confirm this pull in our test envs for all test cases.

Regards
Lily

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9243

**Pull request closed without merging**
