### PR TITLE
LPS-91267 Inline Jsr199JavaCompiler | rebase and resend

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @dantewang ,
Let's go on inline the logic of compiler into CompilerWrapper.

After you finished the inline of compiler, you can inline the logic of JavaCompiler into it. This way, we do not need to change JavaCompiler and release a new patch module.

I have not go into all the details you have, but let's move on and see if we have any problems.

 Tina.

**Comment by dantewang** [comment]
@tinatian I'll try it. Just to clarify, do you mean to merge our `JspCompiler` into `CompilerWrapper`?

**Pull request closed without merging**
