### PR TITLE
Lps 115420 4

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@GinsonRen Please run a diff on this pull.

Thanks.
Tina

**Comment by GinsonRen** [comment]
Hi @tinatian , here is the result on QA1 environment.

Login:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 009c90e | 16008 | 200 | 44.9 | -
PR-1861 | - | 15898 | 210 | 47.7 | -0.69%

WebContent:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 009c90e | 19997 | 339 | 131 | -
PR-1861 | - | 19967 | 344 | 134 | -0.15%

MessageBoard:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 009c90e | 8799 | 164 | 265 | -
PR-1861 | - | 8606 | 159 | 269 | -2.19%

Blog:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 009c90e | 5460 | 129 | 361 | -
PR-1861 | - | 5390 | 138 | 374 | -1.28%

DocumentLibrary:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 009c90e | 9046 | 242 | 521 | -
PR-1861 | - | 9112 | 239 | 516 | 0.73%

Wiki:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 009c90e | 5535 | 212 | 555 | -
PR-1861 | - | 5412 | 207 | 545 | -2.22%

AssetPublisher:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 009c90e | 8965 | 210 | 135 | -
PR-1861 | - | 8959 | 199 | 133 | -0.07%

/cc @dantewang @slnn

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result?

Thanks.
Tina.

**Comment by vicnate5** [comment]
Only unique failures were the ES7 poshi tests, re-running to be safe

**Comment by vicnate5** [comment]
ci:test:search-es7

**Comment by tinatian** [comment]
@vicnate5 Are the unique failures listed in the ES7 test result real?

Tina.

**Comment by vicnate5** [comment]
@tinatian Failures not related. This can be pushed forward.

FYI @xbrianlee @joshchong

**Pull request closed without merging**
