### PR TITLE
LPS-146148

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian ,

I remove unused properties "Control.panel.navigation.max.organizations" as you said in https://github.com/liferay-core-infra/liferay-portal/pull/227.

Thanks for checking .
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 This pull looks good to me, please put it into your list, and I am going to close this pull.

Thanks.
Tina

**Pull request closed without merging**
