### PR TITLE
LPS-111757

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Since this change handled the path at its root, I manually reverted some Windows path fixes to take advantage of it. The full coverage of the unit test will take more time, and I'll create a new ticket for it.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@tinatian Hai has tested the additional changes on Windows.

**Comment by tinatian** [comment]
Hi @dantewang @jorgediaz-lr,
I do not like this fix causing it is using magic number (charAt(0) and charAt(2)). This is hard to maintain, we may end up adding more things like this later, which no one knows what it is for.

Also I see some stupid logic in getParentPath(), could you please try to simplify/rewrite it, let's see if we can find a better way to fix this issue.

The goal here is cover different app server on different OS, so we need unit/integration test to protect it, please send a pull with your 100% covered unit test and integration test if needed.

@jorgediaz-lr This seems not a new issue, so I assume it is not urgent. Please let me know if someone is waiting for a fix. This simplify/rewriting is out of the scope of fixing this issue, if you would like to do it, please feel free to send @dantewang a pull for review, if not, our team can take it over. Let us know what is your decision.


Thanks.
Tina.

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 
There isn't any customer waiting for this fix, I detected this problem by my own, because I activated the new Elasticsearch Sidecar in my computer that is Windows.
So Elasticsearch Sidecar shouldn't be activated by default in master until this is fixed to avoid problems with Windows users.

Regards,
Jorge

**Comment by tinatian** [comment]
Hi @jorgediaz-lr , 
So this is the only blocker we have for sidecar?

Tina

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results?

Thanks.
Tina

**Comment by jorgediaz-lr** [comment]
I did some tests in my free time and after fixing this, it seems it is working fine, but I haven't done a lot of tests (I am from Support department, not QA)

**Comment by tinatian** [comment]
Hi @jorgediaz-lr ,
Victor (@vicnate5) also tested sidecar on windows, and it works fine. I am curious how did you test sidecar on windows? Just want to see if we need to refine our test steps.

Tina.

**Comment by jorgediaz-lr** [comment]
Thank you for the information.

I will also try to test it again tomorrow.

**Comment by tinatian** [comment]
@vicnate5 No need to scan the result, sorry for the trouble.

Tina.

**Comment by jorgediaz-lr** [comment]
Hi @tinatian 

I have tested again Elasticsearch Sidecar today:

- I have downloaded lastest master branch, I have enabled Elasticsearch Sidecar and it doesn't work in my Windows machine.
- I am having the same error than LPS-111757:
```
2020-04-16 20:25:30.617 INFO  [main][Sidecar:138] Starting sidecar
2020-04-16 20:25:30.630 ERROR [main][ElasticsearchConnectionManager:93] bundle com.liferay.portal.search.elasticsearch7.impl:2.0.16 (175)[com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionManager(243)] : The activate method has thrown an exception 
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Liferay/Bundles_Builds/portal-master/tomcat-9.0.33/lib/ext/
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
```

Here is my log file: [liferay.2020-04-16.log.zip](https://github.com/tinatian/liferay-portal/files/4489605/liferay.2020-04-16.log.zip)

And this is the branch that I have used to enable Elasticsearch Sidecar: https://github.com/jorgediaz-lr/liferay-portal/commits/elasticsearch7-sidecar_bad

Regards,
Jorge

**Comment by tinatian** [comment]
Hi @jorgediaz-lr ,
Thanks for the update! QA has also confirmed this issue. I will work on this as soon as possible so that it won't be a blocker for sidecar.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@zhangyan0701 You verified this issue on the LPS ticket, but did run into this when writing the Sidecar automation? (https://issues.liferay.com/browse/LRQA-55958) 

We expect this is an old issue, but our previous Windows sidecar testing did not report this.

Can you check if this issue is reproducible with Sidecar on Windows? (both with the branch you used for the automation and Jorge's branch above).

**Comment by tinatian** [comment]
Hi @jorgediaz-lr,
I create a new ticket and a fix for sidecar like what we did before for this issue, please see https://github.com/tinatian/liferay-portal/pull/1791, so that this won't be a blocker for sidecar.

We still need to fix it in the root, that is in ClassUtill, so I will keep this ticket open and we will work on as soon as possible.

Thanks.
Tina.

**Comment by tinatian** [comment]
Hi @vicnate5 @zhangyan0701 
I know why this was passed on windows before, this is caused by one of the SF made by Shuyang. If we did not rerun all the test after Shuyang's review, then we missed it.

Tina.

**Comment by jorgediaz-lr** [comment]
Thank you for the info, Tina.

**Comment by zhangyan0701** [comment]
> @zhangyan0701 You verified this issue on the LPS ticket, but did run into this when writing the Sidecar automation? (https://issues.liferay.com/browse/LRQA-55958)
> 
> We expect this is an old issue, but our previous Windows sidecar testing did not report this.
> 
> Can you check if this issue is reproducible with Sidecar on Windows? (both with the branch you used for the automation and Jorge's branch above).

This is an old issue. I could reproduce with the branch that I used for automation, but Sidecar could startup on that branch.

**Comment by jorgediaz-lr** [comment]
'Just

**Pull request closed without merging**
