### PR TITLE
LPS-144693

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian ,

I remove unused properties ehcache.socket.so.timeout and ehcache.socket.start.port, and also updated them to verifyproperties.java.
Thanks for checking.

Best
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
Ci:test:sf

**Comment by jeffwu0724** [comment]
Ci:test:relevant

**Comment by jeffwu0724** [comment]
Ci:test

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/162

**Pull request closed without merging**
