### PR TITLE
LPS-89050 Integration point test

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian We took an interface whose -UtilTest will be removed. Creating a new interface in test package doesn't work because of package resolving failure from the fake bundle.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@dantewang @ChiZelin 
I saw there are so many methods in that interface, I am wondering if there is a simpler one we can use.

**Comment by dantewang** [comment]
@tinatian The idea was to choose an interface which we know for sure that the related integration point 
 test will be removed. There should be simpler one among that list.

But if we don't care if the interface is tested by other integration point tests which will not be removed, we can use `DisplayContextFactory`.

**Comment by dantewang** [comment]
Resent using `DisplayContextFactory`: https://github.com/tinatian/liferay-portal/pull/1188

**Pull request closed without merging**
