### PR TITLE
[SampleSQLBuilder] COMMERCE-6848 Fix SampleSQLBuilder according to Commerce changes

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@slnn This has conflicts. Please resend and send directly to Tina, thanks!

**Comment by slnn** [comment]
@dantewang 

This issue has been fixed by this commit https://github.com/liferay/liferay-portal/commit/5c521fa6d3b3162880cdf10c4f76057704a683c8 

This pull is not needed at all 

Lily

**Comment by dantewang** [comment]
@slnn Thanks!

**Pull request closed without merging**
