### PR TITLE
Lps 138426 lps 135570

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please trigger the session replicate test?

Thanks.
Tina

**Comment by vicnate5** [comment]
Additional tests at https://github.com/vicnate5/liferay-portal/pull/1838

**Comment by tinatian** [comment]
ci:stop

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@tinatian All upgrade tests failed due to error in log
```
ERROR [http-nio-8080-exec-3][BasePortalLifecycle:69] java.lang.ClassCastException: [B cannot be cast to com.liferay.portal.kernel.model.User
java.lang.ClassCastException: [B cannot be cast to com.liferay.portal.kernel.model.User
	at com.liferay.portal.events.ChannelSessionDestroyAction.run(ChannelSessionDestroyAction.java:40) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.events.SessionAction.processLifecycleEvent(SessionAction.java:28) ~[portal-kernel.jar:?]
	at com.liferay.portal.events.EventsProcessorUtil.process(EventsProcessorUtil.java:80) ~[portal-impl.jar:?]
	at com.liferay.portal.events.EventsProcessorUtil.process(EventsProcessorUtil.java:61) ~[portal-impl.jar:?]
	at com.liferay.portal.servlet.PortalSessionDestroyer.doPortalInit(PortalSessionDestroyer.java:124) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.util.BasePortalLifecycle.portalInit(BasePortalLifecycle.java:44) [portal-kernel.jar:?]
	at com.liferay.portal.kernel.util.PortalLifecycleUtil.register(PortalLifecycleUtil.java:75) [portal-kernel.jar:?]
	at com.liferay.portal.kernel.util.BasePortalLifecycle.registerPortalLifecycle(BasePortalLifecycle.java:59) [portal-kernel.jar:?]
```
https://testray.liferay.com/reports/production/logs/2021-09/test-1-8/test-portal-acceptance-pullrequest(master)/7726/functional-upgrade-tomcat90-mysql57-jdk8/0/8/liferay-log.txt.gz


Additional error occurs on the second cluster node in the actual session replication test
```
INFO  [default-47][ClusterSchedulerEngine:775] Receive notification from master, add memory clustered job {groupName=com.liferay.portal.cluster.multiple.sample.web.internal.SchedulerSampleMessageListener, jobName=com.liferay.portal.cluster.multiple.sample.web.internal.SchedulerSampleMessageListener, storageType=MEMORY_CLUSTERED}
2021-09-14 01:58:08.440 WARN  [http-nio-9080-exec-3][PortalImpl:6686] org.apache.jasper.JasperException: java.lang.ClassCastException: [B cannot be cast to java.util.Map
org.apache.jasper.JasperException: java.lang.ClassCastException: [B cannot be cast to java.util.Map
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:440) ~[jasper.jar:9.0.43]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.43]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377) ~[jasper.jar:9.0.43]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[servlet-api.jar:4.0.FR]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:370) ~[?:?]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:382) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:63) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
```
https://testray.liferay.com/reports/production/logs/2021-09/test-1-28/test-portal-acceptance-pullrequest(master)/263/functional-tomcat90-mysql57-jdk8/0/10/liferay-log-1.txt.gz

**Comment by tinatian** [comment]
@vicnate5 How can I reproduce the issue locally?

Tina

**Comment by vicnate5** [comment]
ci:test:bundle:norebase

**Comment by vicnate5** [comment]
@tinatian Steps to Reproduce the upgrade issue
1. Import [this database dump from 7.4.0](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.4.0/data-archive/data-archive-portal-mysql.zip)
2. Upgrade to master
3. Start portal
4. Login to test@liferay.com
5. Logout (error thrown on logout action)

The second issue will require a full session replication setup (https://issues.liferay.com/browse/LPS-135570) and then attempting to access second node at localhost:9080 (or whatever port the second node is on)

**Pull request closed without merging**
