### PR TITLE
master vw 1813

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LPS-131312

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:clustering

**Comment by kyle-miho** [comment]
@tinatian Brian's requested changes are here: https://github.com/brianchandotcom/liferay-portal/pull/105854#issuecomment-908808712

**Comment by kyle-miho** [comment]
I'm not sure if we wants other SF improvements other than those that he mentioned, could you do a quick lookover to see if there is anything else obvious that needs to be SF'ed before we ask Brian to look over it again?

**Comment by tinatian** [comment]
See https://github.com/tinatian/liferay-portal/pull/2418

**Pull request closed without merging**
