### PR TITLE
[blog tuning] LPS-97532 Avoid using String.format() when possible

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian String.format() uses Regex internally, replace usages in social-bookmark-* with plain String concat.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Benchmark result: https://github.com/slnn/liferay-portal/pull/432#issuecomment-506564493

**Comment by tinatian** [comment]
@dantewang 
Could you please do a full scan on our code base and fix them as possible as you can? Let's try to fix all, so that we can add a source formatter rule to force people not to use it.

Please resend a new pull.

Thanks.
Tina.

**Pull request closed without merging**
