### PR TITLE
LPS-122653 Upgrade spring

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian 
Passed ci-test-relevant see https://github.com/dantewang/liferay-portal/pull/1791#issuecomment-720230879
Performance test results see https://github.com/dantewang/liferay-portal/pull/1791#issuecomment-724628432

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please verify if the unique failures are real?

Thanks.
Tina.

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
@tinatian I was able to identify which backend test failures here are unique, but I am unable to reproduce the failures (modules integration) locally on this PR **or** master head. Re-running the test suite to compare.

There is also a unique failure in 1 of the auto-upgrade tests (upgrade during startup). 
```
java.lang.NoClassDefFoundError: com/liferay/portal/spring/bean/BeanReferenceAnnotationBeanPostProcessor
```
https://testray.liferay.com/reports/production/logs/test-1-19/1605178356317/test-portal-acceptance-pullrequest(master)/7230/functional-upgrade-tomcat90-mysql57-jdk8/0/7/jenkins-console.txt.gz
Since this is inconsistent, maybe a race issue? Upgrading on startup is is obviously heavy.

**Comment by vicnate5** [comment]
@tinatian No unique failures on re-run.

**Comment by tinatian** [comment]
@vicnate5 So this is good to go?

**Comment by vicnate5** [comment]
@tinatian good to go

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9607

**Pull request closed without merging**
