### PR TITLE
[deprecation round2] LPS-104836 modules part 2 | journal related

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://issues.liferay.com/browse/LPS-104836 | @yuhai I excluded import related removals from this pull.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Force pushed to fix CRLF.

**Comment by dantewang** [comment]
ci:reopen

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8615

**Pull request closed without merging**
