### PR TITLE
Lps 106592 lps 103577 62

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
@slnn Please run a diff on Startup and Shutdown with this pull.

Thanks.
Tina.

**Comment by slnn** [comment]
OK, got it.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8909

**Comment by slnn** [comment]
Hi @tinatian 

Here are startup test results on this pull with lpkg release bundle:

Portal Version | Git Id | warmup(ms) | Average Startup (ms) | No.1 | No.2 | No.3 | No.4 | No.5 | Average Shutdown(ms)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | 1d35a1e | 45604 | 23755 | 24,010 | 24,436 | 22,806 | 23,050 | 24,473 | 6927.33
PR | - | 37650 | 25519.8 | 26,172 | 24,842 | 24,365 | 25,828 | 26,392 | 8217.33


Regards
Lily

**Pull request closed without merging**
