### PR TITLE
LPS-97328

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian I saw we're patching Apache Felix FileInstall for language keys, so I went with the patching approach. I tested it and any change to the language.properties can be reflected on the page. If this approach is OK I will also apply to Felix SCR which shares same problem.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @dantewang,

Can you fix this without adding a new module? Since you already patched it, it should be possible to add metatype.xml to the original lib.

The reasons I do not like it are: 
1) Adding a new module will slow down the startup for sure
2) The goal of this module is just to publish a new resource loader as a bridge without any real logic, I did not say this is wrong, but this should be the last resort we will go to.
3) We did not add this kind of module for any other third-party lib.

Please resend.

Thanks.
Tina.

**Comment by dantewang** [comment]
@tinatian 
I tried adding metatype.xml and language resource bundle by patching today (July 15), and found a problem: if the resource bundle (content/Language) is added, the `Provide-Capability` part in the patched jar's MANIFEST.MF will be

```
liferay.resource.bundle;bundle.symbolic.name="org.
 apache.felix.scr";resource.bundle.base.name="content.Language"
```

That means the original `Provide-Capability` is overwriten.

This directly breaks portal startup for `org.apache.felix.scr` because many other bundles require the capability Scr provides.

Actually it seems Bnd creates a brand new MANIFEST.MF during creation of the patched jar, if a resource bundle is added.

Both Event Admin and Scr have `Provide-Capability` in their MANIFEST.MF, so we can't do what is done on `org.apache.felix.fileinstall` unless we can avoid this issue.

**Comment by tinatian** [comment]
@dantewang 
Add the Provide-Capability in original bundle to the bnd.bnd file you created for the thrid-party patching module, it should append the resource bundle capability to it.

Tina.

**Pull request closed without merging**
