### PR TITLE
[Bug fix] LPS-120745 3-17

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
The SF failures also exist in master.

Liferay Continuous Integration ***@***.***> 于 2021年3月17日周三
23:03写道：

**Comment by tinatian** [comment]
See  https://github.com/shuyangzhou/liferay-portal/pull/9858

**Pull request closed without merging**
