### PR TITLE
LPS-105380

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@tinatian, not sure if this is right... up to you...

**Comment by tinatian** [comment]
@dantewang Please confirm if this is expected.

Thanks.
Tina.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@tinatian I think it should be `expectedMessage` here.

**Comment by dantewang** [comment]
FYI @yuhai

**Comment by yuhai** [comment]
@tinatian, @hhuijser, I resend the fix and please see https://github.com/dantewang/liferay-portal/pull/2043

**Comment by dantewang** [comment]
See https://github.com/tinatian/liferay-portal/pull/2322

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
