### PR TITLE
[Sidecar] LPS-103577 test | master

### PR DESCRIPTION
**Pull request by vicnate5**
Based on https://github.com/vicnate5/liferay-portal/pull/1424, added new functional tests

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
See https://github.com/vicnate5/liferay-portal/pull/1425

**Pull request closed without merging**
