### PR TITLE
[Bug fix] LPS-120742 Remove Jetty-server

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the results?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Looks good, no regressions found.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9861

**Pull request closed without merging**
