### PR TITLE
[Bug fix] LPS-135570 Resend: use ASM wrapper

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@tinatian I've manually tested the steps in the related tickets.

**Comment by dantewang** [comment]
@zhangyan0701 Could you take a look at this test result? Thanks!

**Comment by zhangyan0701** [comment]
There are three unique failures.

I think they are related, because they also failed in PR https://github.com/tinatian/liferay-portal/pull/2347 and https://github.com/tinatian/liferay-portal/pull/2345.

1. Changes of Portlet Configuration cannot be saved. Happened in `Documents and Media` and `Web Content Display` widgets.
[LocalFile.PGStaging#ActivateDeactivateRemoteStagingInOnePortal](https://testray.liferay.com/home/-/testray/case_results/1553851612)

2. There is no success message after saving Web Content and Structure.
[LocalFile.WebContentWithCustomStructures#AddWebContentWithRepeatableRichTextField](https://testray.liferay.com/home/-/testray/case_results/1553851612)

3. There is no success message when add Depot in Global Menu > Applications > Asset Libraries.
[LocalFile.DepotEntry#CanAddDepot](https://testray.liferay.com/home/-/testray/case_results/1553851614)

**Comment by dantewang** [comment]
@zhangyan0701 Can I consider these failures same one, if they are all behaving like no response after click "save" button on popup, and no portal side error log?

**Comment by zhangyan0701** [comment]
Hi @dantewang 

Failures 2 and 3 are a same issue, the contents can be created successfully, but there is no success message after creating content.

I think failure 1 is a different issue, that the changes that are made in Portlet Configuration modal don't reflect in portlet immediately after close the modal,  but need to refresh page. I didn't describe very correctly in my previous comment because yesterday I didn't try locally, and the screenshot in Testray looked like the configuration was not saved.

And there is no error in portal log.

**Pull request closed without merging**
