### PR TITLE
LPS-111757 Avoid wrong paths in Windows beginning with /C:/path... that cause Elasticsearch Sidecar to not start correctly

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
"Illegal char <:> at index 2: /C:/path..." error if you run `Paths.get(PortalUtil.getGlobalLibDir())` java code in a Windows machine.

This can be reproduced for example if you activate Elasticsearch Sidecar in a Windows machine.
An **"Illegal char <:> at index 2: /C:/path..."** error is produced in this line of Sidecar.java
* https://github.com/liferay/liferay-portal/blob/4df4c092a3f1158a4d554b9efd60d8655069d80f/modules/apps/portal-search-elasticsearch7/portal-search-elasticsearch7-impl/src/main/java/com/liferay/portal/search/elasticsearch7/internal/sidecar/Sidecar.java#L321

Instead of fixing the problem in Sidecar code, I think it is better to fix the problem in **PropsUtil._getLibDir** to store correct values in both `liferay.lib.global.dir` and `liferay.lib.global.shared.dir` environment variables.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test

**Comment by tinatian** [comment]
@jorgediaz-lr Please add unit test to expose the issue.

Thanks.
Tina.

**Comment by jorgediaz-lr** [comment]
Resent to https://github.com/tinatian/liferay-portal/pull/1770 with unit test

**Pull request closed without merging**
