### PR TITLE
COMMERCE-1079 Fix errors caused by compileInclude and extract SQL for benchmark

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian Basically the idea is to 1) copy the commerce libs to a certain place in portal source dir so that `benchmarks/build.xml` can use it; 2) extract sqls to the same place so benchmark project can [statically reference the sql files](https://github.com/dantewang/liferay-benchmark-ee/pull/364).

**Comment by dantewang** [comment]
ci-test-sf passed in https://github.com/slnn/liferay-portal/pull/461#issuecomment-553702631

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @dantewang ,
Please see https://github.com/shuyangzhou/liferay-portal/pull/8519. I only modified the build script so that it would be easier for us to maintain, please modify corresponding logic in benchmark.

Thanks.
Tina.

**Pull request closed without merging**
