### PR TITLE
LPS-112075 Fix InvalidPathException on windows

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
Hi @zhangyan0701,
Could you please help me verify this on windows? You can use the steps in Jorge's comment, https://github.com/tinatian/liferay-portal/pull/1781#issuecomment-614881366.


Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
FYI @jorgediaz-lr @vicnate5 @dantewang

**Comment by zhangyan0701** [comment]
Hi @tinatian,

I tested on Windows with your fix, and Sidecar could startup.

```
2020-04-17 08:12:34.810 INFO  [main][Sidecar:138] Starting sidecar
2020-04-17 08:12:35.406 INFO  [main][Sidecar:602] Sidecar properties : {bootstrap.memory_lock=false,bootstrap.system_call_filter=false,cluster.initial_master_nodes=liferay,cluster.name=LiferayElasticsearchCluster,cluster.routing.allocation.disk.threshold_enabled=false,http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/,http.cors.enabled=true,node.data=true,node.ingest=true,node.master=true,node.name=liferay,node.store.allow_mmap=false,path.data=F:\masterbundle\data\elasticsearch7\indices,path.logs=F:\masterbundle\logs,path.repo=F:\masterbundle\data\elasticsearch7\repo}
2020-04-17 08:12:48.034 INFO  [main][Sidecar:120] Sidecar liferay is at 127.0.0.1:9200
```

/cc @jorgediaz-lr @vicnate5 @dantewang

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
FYI @shuyangzhou Forward to Brian

**Comment by tinatian** [comment]
FYI search team @joshchong @arboliveira

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
