### PR TITLE
LPS-108588 DB Partition: Listeners

### PR DESCRIPTION
**Pull request by achaparro**
Hi @tinatian,

These are the changes we were talking about yesterday. For the configuration, I have kept the following names:
- excludedMessageBusDestinationNames
- excludedSchedulerJobNames

Because renaming them as globalMessageBusDestinationNames and globalSchedulerJobNames seemed really specific and we use the term global for other things. Also, it's also common to have exclude* properties in other incerceptor or listeners.

Anyway, I have added the global listeners as the default ones for those properties.

Let me know what you think.

Thanks.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
@tinatian the failure we are getting was present in upstream, it's unrelated with the changes

**Comment by tinatian** [comment]
See https://github.com/tinatian/liferay-portal/pull/1829

**Pull request closed without merging**
