### PR TITLE
LPS-91429 Portlet title | Rebase 3-26

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@tinatian In a previous run, PortletTitleTest passed, see https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/153849/testReport/

**Comment by dantewang** [comment]
ci:reopen

Liferay Continuous Integration <notifications@github.com> 于 2019年3月26日周二
22:40写道：

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7513

**Pull request closed without merging**
