### PR TITLE
[Unit Test] LPS-87800 FilterMappingTest

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@mtambara Please take this over!

Thanks!
Tina.

**Comment by mtambara** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7134

**Comment by mtambara** [comment]
ci:close

**Pull request closed without merging**
