### PR TITLE
[Bug] LPS-84318 Method.isAccessible check is redundant

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian 
JIRA https://issues.liferay.com/browse/LPS-84318
JavaDoc https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/AccessibleObject.html

Basically the usage here is wrong.

According to the JavaDoc, the flag is `false` by default on a newly created Method object, so the `if` check will always pass, which is redundant.

I think this `if (isAccessible())` is added under the assumption that the return value indicates whether the method represented by the Method object is `public`, `protected` or `private`. However, the value of `isAccessible` actually has nothing to do with what the modifier is. It means whether the modifier is ignored when the object is used.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:reopen

Service builder CI failure is happening on many other PRs.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/6603

**Pull request closed without merging**
