### PR TITLE
[Bug Fix] LPS-83768

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian See description of the bug: https://issues.liferay.com/browse/LPS-83768?focusedCommentId=1624437&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1624437

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@vicnate5
Those modules-integration failures seems to be upstream, as shown in https://test-1-1.liferay.com//userContent/jobs/test-portal-acceptance-upstream%28master%29/builds/5268/jenkins-report.html

Could you take a look at the functional ones?

**Comment by vicnate5** [comment]
@dantewang Functional test failures are not related to this pull

**Comment by dantewang** [comment]
@vicnate5 Thank you!

**Comment by tinatian** [comment]
Talked with Dante, please resend

**Pull request closed without merging**
