### PR TITLE
[Bug Fix] LPS-134002

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci-test has been executed and no relevant failure: https://github.com/dantewang/liferay-portal/pull/2102#issuecomment-944161737

**Comment by tinatian** [comment]
@dantewang I took a deep look into the issue. There is a bug here with the local cache "_locales". This local map will be populated when "validate" is false, but it will be read when "validate" is true. This is wrong, and our fix based on it can not be right either. 
I will close this pull and we need to figure out another solution.

Thanks.
Tina.

**Pull request closed without merging**
