### PR TITLE
COMMERCE-4993 DataFactory additions/changes

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-4993

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@slnn Please take this over, Thanks!

FYI @dantewang

**Comment by slnn** [comment]
OK, got it

**Comment by slnn** [comment]
Hi @dsitu 

I did some fix and simplify changes in https://github.com/dsitu/liferay-portal/pull/2

Please check and test my last commit:https://github.com/dsitu/liferay-portal/pull/2/commits/0d469dfd8fc52f87c78eee3f1163be62cf79ff90 to see if it broke anything.

I removed the first declaration for `defaultCPInstanceModel` and `defaultCommercePriceEntryModel`  as they did not be used before they are reassigned.

/cc @tinatian @dantewang

Regards
Lily

**Comment by dsitu** [comment]
closing this, new PR here https://github.com/tinatian/liferay-portal/pull/2213

**Pull request closed without merging**
