### PR TITLE
Lps 111929 3

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
@tinatian The failure is real. The message posted by CI bot is not the actual error.

I can reproduce startup errors locally:

```
2020-04-21 10:00:59.165 ERROR [main][PortalInstances:280] com.liferay.portal.kernel.exception.NoSuchResourceActionException: 90#ADD_TO_PAGE
com.liferay.portal.kernel.exception.NoSuchResourceActionException: 90#ADD_TO_PAGE
	at com.liferay.portal.service.impl.ResourceActionLocalServiceImpl.getResourceAction(ResourceActionLocalServiceImpl.java:322)
	at sun.reflect.GeneratedMethodAccessor165.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
	at com.sun.proxy.$Proxy29.getResourceAction(Unknown Source)
	at com.liferay.portal.service.impl.ResourcePermissionLocalServiceImpl._updateResourcePermission(ResourcePermissionLocalServiceImpl.java:2071)
	at com.liferay.portal.service.impl.ResourcePermissionLocalServiceImpl._initPortletDefaultPermissions(ResourcePermissionLocalServiceImpl.java:1936)
	at com.liferay.portal.service.impl.ResourcePermissionLocalServiceImpl.initPortletDefaultPermissions(ResourcePermissionLocalServiceImpl.java:1217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
	at com.sun.proxy.$Proxy28.initPortletDefaultPermissions(Unknown Source)
	at com.liferay.portal.service.impl.PortletLocalServiceImpl.checkPortlet(PortletLocalServiceImpl.java:186)
	at com.liferay.portal.service.impl.PortletLocalServiceImpl.checkPortlets(PortletLocalServiceImpl.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
	at com.sun.proxy.$Proxy25.checkPortlets(Unknown Source)
	at com.liferay.portal.service.impl.CompanyLocalServiceImpl._checkCompany(CompanyLocalServiceImpl.java:1861)
	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.checkCompany(CompanyLocalServiceImpl.java:283)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
	at com.sun.proxy.$Proxy30.checkCompany(Unknown Source)
	at com.liferay.portal.service.impl.CompanyLocalServiceImpl.checkCompany(CompanyLocalServiceImpl.java:260)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
	at com.sun.proxy.$Proxy30.checkCompany(Unknown Source)
	at com.liferay.portal.kernel.service.CompanyLocalServiceUtil.checkCompany(CompanyLocalServiceUtil.java:86)
	at com.liferay.portal.util.PortalInstances.initCompany(PortalInstances.java:277)
	at com.liferay.portal.internal.servlet.MainServlet._initCompanies(MainServlet.java:778)
	at com.liferay.portal.internal.servlet.MainServlet.init(MainServlet.java:418)
```

The cause is https://github.com/tinatian/liferay-portal/pull/1793/commits/f6c9a229729926aad3e1237196d46281023ac9f0. The `MainServlet._initResourceActions()` is not 100% logically equal to `ResourceActionImpl.check(Portlet)`.

`MainServlet` calls `ResourceActionsImpl.getPortletResourceActions(portlet)` which runs `ResourceActionsImpl._checkPortletActions(portlet, actions)` without any condition. The `_checkPortletActions` method adds some additional ones to the portlet resource action list.

On the other hand, `ResourceActionsImpl.check(Portlet)` directly calls `_getPortletResourceActions(name, portlet)` which then only does `_checkPortletActions` for portlets whose name is not `90` (`PortletKeys.PORTAL`).

As a result, with this change, the portlet actions of "90" is not completely initialized, causing errors in company initialization and other places.

I didn't get a clue about why it skips "90" when reading/getting and then check it without condition in a method. I'll try to see what happens if I remove the "90" skipping.

**Pull request closed without merging**
