### PR TITLE
[SampleSQLBuilder] LPS-116679 resend

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Applied petra-io, removed flush() overriding, and rearranged commits based on https://github.com/shuyangzhou/liferay-portal/pull/9243

### CODE REVIEW

**Comment by dantewang** [comment]
cc @slnn @GinsonRen please verify

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
I checked the generated sql data, it works well. /cc @dantewang

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9247

**Pull request closed without merging**
