### PR TITLE
Lps 130041 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:reevaluate:1027401_320

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please scan the test results?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@kyle-miho can you analyze this one? There is results for the full ci test too.

**Comment by kyle-miho** [comment]
@tinatian All of the failures are unique, possibly a large amount caused by the JSONWS Changes, For example, we used to use this curl in our poshi tests: 
`Executing commands: curl -X POST -u 'test@liferay.com:test' -d 'parentGroupId=0' -d 'liveGroupId=0' -d 'nameMap={"en_US":"Test Site Name"}' -d 'descriptionMap={}' -d 'type=1' -d 'manualMembership=true' -d 'membershipRestriction=0' -d 'friendlyURL=' -d 'site=true' -d 'inheritContent=false' -d 'active=true' http://localhost:8080/api/jsonws/group/add-group`
, but the JSON Response is now a Group Key Exception, likely due to these changes. This should be causing most if not all of the failures in the pull
`     [exec] 2021-04-06 18:03:05.171 ERROR [http-nio-8080-exec-4][JSONWebServiceServiceAction:126] com.liferay.portal.kernel.exception.GroupKeyException`
     
(There are also indexing errors that should not be occuring upstream as i am aware of that are happening in this pull 2021-04-06 
```
10:09:38.043 ERROR [http-nio-8080-exec-7][BulkDocumentRequestExecutorImpl:63] failure in bulk execution:
[0]: index [liferay-47827-workflow-metrics-sla-task-results], type [WorkflowMetricsSLATaskResultType], id [WorkflowMetricsSLATaskResult605111598c016a83497437773df812abccf6e34f903994921ebd9c4ce8e09217], message [[liferay-47827-workflow-metrics-sla-task-results] ElasticsearchException[Elasticsearch exception [type=index_not_found_exception, reason=no such index [liferay-47827-workflow-metrics-sla-task-results]]]]
)     
```

Example Log: https://testray.liferay.com/reports/production/logs/2021-04/test-1-14/test-portal-acceptance-pullrequest(master)/8001/functional-tomcat90-mysql57-jdk8/0/12/liferay-log.txt.gz

**Comment by tinatian** [comment]
@kyle-miho Could you please list the steps to reproduce it locally?

Thanks.
Tina

**Comment by kyle-miho** [comment]
@tinatian running this curl in console should be enough to reproduce it, you should get an error
curl -X POST -u 'test@liferay.com:test' -d 'parentGroupId=0' -d 'liveGroupId=0' -d 'nameMap={"en_US":"Test Site Name"}' -d 'descriptionMap={}' -d 'type=1' -d 'manualMembership=true' -d 'membershipRestriction=0' -d 'friendlyURL=' -d 'site=true' -d 'inheritContent=false' -d 'active=true' http://localhost:8080/api/jsonws/group/add-group

**Pull request closed without merging**
