### PR TITLE
[deprecation] LPS-106325 ClusterGroup and related things

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian The ClusterGroup related code are deprecated by LPS-97774, as of 7.2. In this pull all the things deprecated in LPS-97774 are removed. If you think we should postpone the removal, please close the ticket.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:reopen

Liferay Continuous Integration <notifications@github.com> 于 2019年12月26日周四
18:53写道：

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8669

**Pull request closed without merging**
