### PR TITLE
LPS-138426 SessionMessages

### PR DESCRIPTION
**Pull request by dantewang**
I extracted some logic and applied to SessionErrors.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10267

**Pull request closed without merging**
