### PR TITLE
LPS-160370 System and default company are the same so they must use the same Sharded cache

### PR DESCRIPTION
**Pull request by achaparro**
Hi @tinatian,

The cache for the default company should be the same that the one for the system company (0) since they are considered the same. Otherwise, we would need to populate the companyThreadLocal in more places.

Thank you,

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:db-partition

**Comment by vicnate5** [comment]
@lucasperj Please check this PR, I see some possible unique failures.

**Comment by achaparro** [comment]
Closing to check the regression

**Pull request closed without merging**
