### PR TITLE
LPS-72054

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
It's CI issue.

**Comment by dantewang** [comment]
ci:retest

**Comment by tinatian** [comment]
@dantewang @ChiZelin 

1) Please separate the adding new language key entry and adding new language.propertie file into two commits.
2) Please fix the order of the new entry key you added, all the keys should be in alphabetic order.

Tina.

**Comment by dantewang** [comment]
Got it.

**Pull request closed without merging**
