### PR TITLE
[bug fix] LPS-105095 Sybase: sp_dropkey only removes keys defined by system procedures

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian See comment in https://issues.liferay.com/browse/LPS-105095; this is also a blocker of investigation on https://issues.liferay.com/browse/LPS-95571. cc @Preston-Crary

### CODE REVIEW

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8588

**Pull request closed without merging**
