### PR TITLE
[bug fix] LPS-89497 Add support for upgrading factory configs

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian This pull includes a major version bump in portal-configuration-persistence-api.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang @yuhai 
Let's merge the factory pid logic into current one, basically the upgrade logic will be:
1. treat the passed in pid as a single pid
2. if not found as a single pid, treat it as a factory pid

This way, you do not need an new API method, and also users are easier to use the API, they do not have to know if the pid is factory or not.

Please resend.

Thanks.
Tina.

**Pull request closed without merging**
