### PR TITLE
Lps 72939 & lps 79508

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
@tinatian,
I have merged some of the related commits. And the failing tests dont seem to be related to this ticket.

From:https://github.com/shuyangzhou/liferay-portal/pull/5966

Thanks

**Comment by tinatian** [comment]
Hi @arthurchan35 ,
According to your test:
`Assert.assertEquals(
			"http://foo.com",
			_httpImpl.removeProtocol("http://http://foo.com"));`

This should not be right, you should return "foo.com" after removing protocol.

Could you please take a look at it?

Thanks.
Tina.

**Comment by samuelkong** [comment]
ci:reopen

**Comment by samuelkong** [comment]
@tinatian 
`Assert.assertEquals( "http://foo.com", _httpImpl.removeProtocol("http://http://foo.com"));`
This behavior is is correct. This is a weird and confusing URL, but it's a perfectly valid URL and there is only one protocol in this URL.

To make things a little less confusing, I'm going to use the URL `https://http://foo.com` instead:
* `https://` is the protocol + protocol separator
* `http` is the host name
* `:` is the port separator followed by a blank port
* `//foo.com` is the path

This URL is syntactically the same as http://localhost://image.jpg

**Comment by arthurchan35** [comment]
Thanks @samuelkong 
Hi @tinatian, again here is a reference to valid URL syntax: 
https://en.wikipedia.org/wiki/URL#Syntax
Here we would only consider schemes that ends with "://", since it'll be consitent with previous portal behavior.

**Comment by arthurchan35** [comment]
ci:retest

**Comment by tinatian** [comment]
@samuelkong Thanks for the explanation.
@arthurchan35 You change failed CI unit test 
`Error Message

expected:<foo.com[:8080]> but was:<foo.com[]>
Stacktrace

junit.framework.AssertionFailedError: expected:<foo.com[:8080]> but was:<foo.com[]>
	at com.liferay.portal.util.HttpImplTest.testGetDomainWithValidURLs(HttpImplTest.java:188)
	at com.liferay.portal.kernel.test.rule.CodeCoverageAssertor$1.evaluate(CodeCoverageAssertor.java:85)`

Could you please fix it?

Thanks.
Tina.

**Comment by arthurchan35** [comment]
@tinatian,
Oops, forgot to remove port from test. Corrected.
See https://github.com/tinatian/liferay-portal/pull/880

**Pull request closed without merging**
