### PR TITLE
Lps 74658 3

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:retest

**Comment by tinatian** [comment]
ci:retest

**Comment by dantewang** [comment]
@tinatian I rechecked the API and I think it's better to hold this until we implement the 3.0 method `StateAwareResponse#getRenderParameters()`, and then we can delegate this to that method.

**Comment by tinatian** [comment]
OK, then let's hold off for now, please comment on the google doc.

Thanks.
Tina

**Pull request closed without merging**
