### PR TITLE
[Bug fix] LPS-137136 Remove jdom 1

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test result? Thanks!

**Comment by tinatian** [comment]
Please rebase and resend

**Comment by zhangyan0701** [comment]
@dantewang Really sorry, I missed you mention yesterday!

**Comment by dantewang** [comment]
@zhangyan0701 No problem, and please discard this pull. I'll send a new pull and notify you on that.

**Pull request closed without merging**
