### PR TITLE
LPS-128599 Fix NPE in LogAssertionTestRule

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian @vicnate5 With this fix to `LogAssertionTestRule` the error in https://github.com/shuyangzhou/liferay-portal/pull/9874 can be reproduced on master.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9878

**Pull request closed without merging**
