### PR TITLE
[bug fix] LPS-129773

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian The bundle event of a bundle being installed may be processed by `BundleBlacklist` first, and then `PortalFragmentBundleWatcher`.
If `BundleBlacklist` uninstalls this bundle, the bundle's state will become "UNINSTALLED"; then in `PortalFragmentBundleWatcher` the NPE happens as uninstalled bundle can't adapt to `BundleRevision`.

@vicnate5 ci-test-liferay-online passes at https://github.com/dantewang/liferay-portal/pull/1954#issuecomment-808019949

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:license

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9889

**Pull request closed without merging**
