### PR TITLE
LPS-146270 Remove portal-template-xsl

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian I created a new ticket for removal of module portal-template-xsl because the changes has become bigger.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/272

**Pull request closed without merging**
