### PR TITLE
LPS-92372 | master

### PR DESCRIPTION
**Pull request by vicnate5**
@dantewang https://issues.liferay.com/browse/LPS-92372

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
CI Relevant results at https://github.com/tinatian/liferay-portal/pull/1617#issuecomment-559715669

**Comment by vicnate5** [comment]
@dantewang The extra test I ran for Document import fails on Weblogic for `odt` types
https://gist.github.com/vicnate5/43da5d57d269b3df41280da843eb92ab

Steps to Reproduce:
1. Add "Documents and Media" widget to a page
2. Add the this file to Documents and Media https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/dependencies/Document_1.odt
3. Assert expected Metadata: "Automatically Extracted Metadata"

Actual Result: No metadata

Full log: https://testray.liferay.com/reports/production/logs/test-1-7/1575306438952/test-portal-acceptance-pullrequest(master)/4651/functional-smoke-weblogic122-mysql57-jdk8/11/0/jenkins-console.txt.gz

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@vicnate5 @tinatian See https://github.com/tinatian/liferay-portal/pull/1622

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
