### PR TITLE
LPS-146151

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian, 

Resend, resolve the conflicts with Brian's master.
I have removed unused properties "My.sites.display.style", and updated to propskeys.java, propsvalues.java and verifyproperties.java.

It was renamed from "MY_PLACES_DISPLAY_STYLE" to "MY_SITES_DISPLAY_STYLE" in commit 6499e686a841a36519ece17031f5acc3d5e07786, see LPS-16333.
It was added to use in based on commit 7151e62ad916dac5595857bd7f196c38456e13e4, see LPS-16333.
It was finally deleted in commit fff96c7a6da205fd359a3d6b82c7a89560ec49e1, see LPS-69899.
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 This looks good to me. Please put it into your list. I am going to close this pull.

**Pull request closed without merging**
