### PR TITLE
[deprecation] LPS-103157 portal-kernel part 1

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please help me check if there is any real failure?

Thanks.
Tina

**Comment by tinatian** [comment]
Hi @vicnate5,
I checked all the integration tests and it should be fine, I will go ahead to forward this pull, please let me know if you found any real failures.

Thanks.
Tina.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8387

**Comment by vicnate5** [comment]
Functional test failures are not related.

**Comment by tinatian** [comment]
Thanks @vicnate5 !

**Pull request closed without merging**
