### PR TITLE
LPS-145076

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian ,

Resend
I removed Remove unused properties "auto.deploy.websphere.wsadmin.properties.file.name" and "auto.deploy.websphere.wsadmin.app.name.suffixac" (which are removed based on commit 0329a4c, see LPS-61201). I also did the SF and update the propskey, propsvalue and verifyproperties.
Thanks for checking for me!

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/184

**Pull request closed without merging**
