### PR TITLE
LPS-145063

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian ,

As we discuss last week, I removed the unused properties "verify.patch.levels.disabled". 
It was only used in MainServlet.java, and was removed based on commit 0a6c8783ca2c0ccdc17ff920f5a809e03965e177, see LPS-137936.
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 Please add this information to your commit message:
`It was only used in MainServlet.java, and was removed based on commit 0a6c878, see LPS-137936.`

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724  SF failed because of the commit message of https://github.com/tinatian/liferay-portal/pull/2479/commits/cc1eca74c7672d19a19c380c6e8844d32519b19d. Please resend.

Tina

**Pull request closed without merging**
