### PR TITLE
LPS-135570 9 27

### PR DESCRIPTION
**Pull request by yuhai**
@tinatian, this is just update. The pr can solved the mentioned wildfly issue (I didn't test on websphere and weblogic) from the [link](https://github.com/tinatian/liferay-portal/pull/2404#issuecomment-926836887).

For the [issue ](https://github.com/tinatian/liferay-portal/pull/2404#issuecomment-926848375), I set session.timeout=2 to test. Sometimes, I can reproduce the issue. But I don't find the fixed way to reproduce the issue. Some infos for the issue. When the issue happens, see the [code](https://github.com/yuhai/liferay-portal/blob/LPS-135570-9-27/portal-impl/src/com/liferay/portal/events/ChannelSessionDestroyAction.java#L36), 

not work when httpSession is 
com.liferay.shielded.container.internal.proxy.HttpSessionDelegate@15979741     the value is HttpSessionAMSWrapper.

work when httpSession is SessionReplicationHttpSessionWrapper.

cc @vicnate5

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by vicnate5** [comment]
Wildfly and Jboss are working on this PR. Weblogic and Websphere are still broken for [the same reason](https://github.com/tinatian/liferay-portal/pull/2404#issuecomment-926836887) as before

**Comment by yuhai** [comment]
@vicnate5 thanks.

@tinatian, I encounter one block issue.

For **weblogic**:
```
<Sep 24, 2021 7:15:00,095 AM GMT> <Error> <HTTP> <BEA-101020> <[ServletContext@1130571057[app:ROOT module:ROOT path:null spec-version:3.1]] Servlet failed with an Exception
java.lang.ClassCastException: com.liferay.portal.web.internal.session.replication.HttpServletRequestASMWrapper cannot be cast to weblogic.servlet.internal.ServletRequestImpl
	at weblogic.servlet.internal.ServletRequestImpl.getOriginalRequest(ServletRequestImpl.java:1654)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:71)
	at com.liferay.portal.web.internal.session.replication.SessionReplicationFilter.doFilter(SessionReplicationFilter.java:79)
	at com.liferay.shielded.container.internal.proxy.FilterWrapper.doFilter(FilterWrapper.java:79)
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
	Truncated. see log file for complete stacktrace
```
The method getOriginalRequest()
```
 public static ServletRequestImpl getOriginalRequest(ServletRequest rq) {
        if (rq == null) {
            return null;
        }
        while (rq instanceof ServletRequestWrapper) {
            rq = ((ServletRequestWrapper)rq).getRequest();
        }
        if (rq == null) {
            throw new AssertionError((Object)"Original request not available");
        }
        return (ServletRequestImpl)rq;
    }
```
It will cast our request to ServletRequestImpl. This will cause the error. If we use SessionReplicationHttpServletRequestDelegate design, it should be not passed based on my knowledge. The similar issue happens in **websphere**.

websphere related code as the below:
```
 public static <T extends ServletRequest, V extends ServletRequest> T unwrapRequest(final V req, final Class<T> requestClass, final boolean logWarning) {
        ServletRequest r = req;
        while (!requestClass.isInstance(r)) {
            if (logWarning && ServletUtil.logger.isLoggable(Level.WARNING)) {
                ServletUtil.logger.logp(Level.WARNING, "com.ibm.wsspi.webcontainer.util.ServletUtil", "unwrapRequest", MessageFormat.format(ServletUtil.nls.getString("servletrequestwrapper.is.not.an.instance.of.so.wrapped.logic.may.be.bypassed", "ServletRequestWrapper [{0}] is not an instance of [{1}] so wrapped logic may be bypassed."), r, requestClass));
            }
            if (TraceComponent.isAnyTracingEnabled() && ServletUtil.logger.isLoggable(Level.FINE)) {
                ServletUtil.logger.logp(Level.FINE, "com.ibm.wsspi.webcontainer.util.ServletUtil", "unwrapRequest", " unwrap the request [" + r + "]");
            }
            if (r instanceof ServletRequestWrapper) {
                r = ((ServletRequestWrapper)r).getRequest();
            }
            else if (r instanceof HttpServletRequestProxy) {
                r = ((HttpServletRequestProxy)r).getRequest();
            }
            else {
                if (!(r instanceof IServletRequestWrapper)) {
                    if (TraceComponent.isAnyTracingEnabled() && ServletUtil.logger.isLoggable(Level.FINE)) {
                        ServletUtil.logger.logp(Level.FINE, "com.ibm.wsspi.webcontainer.util.ServletUtil", "unwrapRequest", " request   [" + r + "]");
                    }
                    throw new RuntimeException("SRV.8.2: RequestWrapper objects must extend ServletRequestWrapper or HttpServletRequestWrapper");
                }
                r = ((IServletRequestWrapper)r).getWrappedRequest();
            }
        }
        return (T)r;
    }
```
I decompiled their jar. You can download them from the [link](https://drive.google.com/drive/folders/18xCSMJb3PVEhF-8ordjLlxwrMYAQX1hc?ths=true).

If we revert the [commit ](https://github.com/tinatian/liferay-portal/pull/2408/commits/381a291d404de1e867ef72f01eda49ece9e84c81), it will exist some issues as the commit info explained. For example, access http://localhost:8080, the issue will happen.

**Comment by tinatian** [comment]
Thanks @yuhai! 
It seems we need to avoid wrapping http request to fix these issues. I will take it over from here, you can go back work on your current task.

Tina.

**Pull request closed without merging**
