### PR TITLE
COMMERCE-4993

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-4993

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:stable

**Comment by dsitu** [comment]
ci:test:stable

**Comment by dsitu** [comment]
ci:test:stable

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:stable

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:reopen

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:reevaluate:1067401_8332

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9943

**Pull request closed without merging**
