### PR TITLE
[portal-impl-integration] LPS-95016 roles-test

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7750

**Comment by tinatian** [comment]
@dantewang 
I added a commit to move base class out of portal-test-integration, basically we want to remove portal-test-integration in future and use ***-test-util pattern instead. Please move classes out if it is only used by modules.

Thanks.
Tina.

**Comment by dantewang** [comment]
@tinatian Got it, thanks!

**Pull request closed without merging**
