### PR TITLE
[portal-test-integration] LPS-102243 | 12-31

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:reopen

Liferay Continuous Integration <notifications@github.com> 于 2019年12月31日周二
11:56写道：

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8685

**Pull request closed without merging**
