### PR TITLE
[WC Tuning] LPS-97069 Reduce request attribute get/set in JournalContentDisplayContext

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This change is not related to business logic.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang Please recheck the usage of JournalContentDisplayContext.create in JournalContentConfigurationAction

Tina

**Pull request closed without merging**
