### PR TITLE
Lps x findercache 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by slnn** [comment]
Hi @tinatian 

Here are test results on Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Log Out | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | 948a1968f | 38199 | 272 | 81.2 | -
PR | - | 38364 | 264 | 78.1 | 0.4319484803

Other ones are on the way.

Lily

**Comment by slnn** [comment]
Test results for other test cases

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | 948a1968f | 12226 | 248 | 999 | -
PR | - | 12506 | 299 | 902 | 2.290201211


MB:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | 948a1968f | 16156 | 482 | 544 | -
PR | - | 16295 | 303 | 295 | 0.8603614756


DL:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | 948a1968f | 25204 | 258 | 312 | -
PR | - | 25515 | 281 | 328 | 1.233931122


WC:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | 948a1968f | 53828 | 702 | 209 | -
PR | - | 53309 | 785 | 230 | -0.96418221

**Comment by slnn** [comment]
Hi @tinatian 

As the server room will have electricity cut off, so I have shut down all of the servers by my end of today, For Blog and AssetPublisher test results I will update next Monday when I got them.

Lily

**Comment by slnn** [comment]
Hi @tinatian 

Here are results for Blog:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | 948a1968f | 14193 | 41.5 | 115 | -
PR | - | 14204 | 351 | 104 | 0.07750299443

When run test with the baseline of this pull, I found SampleSQLBuilder has some problems with AssetPublisher sample data, I am working on fixing it, if you still need the result on AP, I will run later.

Lily

**Comment by slnn** [comment]
Here are results for AssetPublisher:


Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change (%)
-- | -- | -- | -- | -- | --
BaseLine | 948a1968f | 21613 | 394 | 177 | -
PR | - | 21550 | 399 | 177 | -0.2914912321

**Pull request closed without merging**
