### PR TITLE
[Bug fix] LPS-120256

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang @yuhai 
What is the root reason we see the ClassCastException? and why this is going to fix it?

Tina.

**Comment by yuhai** [comment]
@tinatian, the issue is when the bundle gets redeployed, the CTStore instance of StoreFactory didn't get refreshed, so it is still holding the old instance of CT*LocalService from the class loader of the undeployed bundle. The fix can let the CTStore instance of StoreFactory get refreshed when the bundle redeploys.

**Comment by tinatian** [comment]
Hi @dantewang @yuhai 
See https://github.com/shuyangzhou/liferay-portal/pull/9439.

I did not take your solution because no one is going to use CTStoreFactory#create, it should not be an factory at all. The right way is to create a new marker interface, and implement it in module which will publish all the CTStore. We need a new interface here is to add dependency to ensure the CTStore has been published before using. These are a lot changes compared to my solution.

Tina.

**Comment by yuhai** [comment]
Hi @tinatian, I have checked your solution, thanks.

**Pull request closed without merging**
