### PR TITLE
[For Review Only] LPS-87059

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This is for review of changes and (possible) discussion only. I haven't updated the ClassLoaderResourceParserTest to cover added logic.

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian Sorry just saw some issues... Need to take a deeper look.

**Comment by dantewang** [comment]
@tinatian Reopen, previous issue I saw was due to my corrupted local data.

- In this PR I tried to decouple `ClassLoaderResourceParser` usages to make it possible to be a pure OSGi component and move it also to `portal-template-impl`.
- I didn't manage to remove the two `*BundleResourceParser` because they are needed for templates like `FTL_liferay.ftl`. I didn't find a way to make `ClassLoaderResourceParser` able to handle such templates on its own. So I changed the `*BundleResourceParser` classes to extend directly from `URLResourceParser`.

**Comment by dantewang** [comment]
@tinatian CI doesn't work at the moment so this PR hasn't been checked.

**Comment by tinatian** [comment]
Hi @dantewang @yuhai, 
Please see my changes in this pull : https://github.com/shuyangzhou/liferay-portal/pull/7238.

I removed the dependencies of ClassLoaderTemplateResource, and deprecate it. Please modify your code here based on my change and send me a new pull.

Thanks.
Tina.

**Pull request closed without merging**
