### PR TITLE
LPS-102995

### PR DESCRIPTION
**Pull request by Preston-Crary**
Leaving the serialization problems for later.  I think it makes sense to keep those changes in a separate ticket.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:backend

**Comment by tinatian** [comment]
ci:help

**Comment by tinatian** [comment]
ci:test:help

**Comment by tinatian** [comment]
Hi @vicnate5 
`ci:test:backend` is removed from ci commands? Any replacement?


Tina

**Comment by vicnate5** [comment]
ci:test:backend

**Comment by vicnate5** [comment]
AFAIK, no test commands were removed, there have been some outages, could be related https://loop.liferay.com/home/-/loop/feed/20287376

**Comment by vicnate5** [comment]
ci:test:backend

**Comment by vicnate5** [comment]
ci:test:backend

**Comment by Preston-Crary** [comment]
ci:reopen

**Comment by Preston-Crary** [comment]
ci:test:backend

**Comment by Preston-Crary** [comment]
ci:stop

**Comment by Preston-Crary** [comment]
Please see https://github.com/tinatian/liferay-portal/pull/1627

**Pull request closed without merging**
