### PR TITLE
[Bug fix] LPS-105037 Sybase does not support DROP TABLE IF EXISTS | resend with unit test fix

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please help me scan the result?

Thanks.
Tina

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8598

**Pull request closed without merging**
