### PR TITLE
LPS-143633 Avoid using LicenseManagerUtil, RawMetadataProcessorUtil, PatcherUtil directly in modules

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

Main Task: [LPS-143403](https://issues.liferay.com/browse/LPS-143403)
Sub Task 6: [LPS-143633](https://issues.liferay.com/browse/LPS-143633)
Removes LicenseManagerUtil, RawMetadataProcessorUtil, and PatcherUtil from modules components

From sub task 6 and onwards, tasks no longer depend on previous tasks.

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@vicnate5 Hi Victor, I've gone through the relevant test and it seems like it has some unique failures.
[com.liferay.document.library.search.test.DLFileEntryIndexerIndexedFieldsTest](https://testray.liferay.com/home/-/testray/case_results/1609161682)
[LocalFile.MultiFactorAuthentication#LoginWithOTPEnabled
](https://testray.liferay.com/home/-/testray/case_results/1609161325)
[LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive621021](https://testray.liferay.com/home/-/testray/case_results/1609161503)
[LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7310](https://testray.liferay.com/home/-/testray/case_results/1609161523)
Could you please help me check on this?
Thank you!

**Comment by vicnate5** [comment]
@julschong There is a startup error here on all enviornments
`com.liferay.portal.kernel.exception.NoSuchResourceActionException: There are no actions associated with the resource com.liferay.dynamic.data.mapping.model.DDMStructure-com.liferay.portal.kernel.metadata.RawMetadataProcessor`
https://testray.liferay.com/reports/production/logs/2022-02/test-1-31/test-portal-acceptance-pullrequest(master)/2071/functional-smoke-tomcat90-mysql57-jdk8_stable/0/0/liferay-log.txt.gz?authuser=0

**Comment by julschong** [comment]
@tinatian Hi Tina,
This PR has issues I will need to resolve. 
I sent the next PR for review first [liferay-coreinfra#312](https://github.com/liferay-core-infra/liferay-portal/pull/312)

**Pull request closed without merging**
