### PR TITLE
Lps 111752

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:reopen

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@kyle-miho @mtambara 
Please make "testConfigurationAllDataTypes" more clear what it is testing and resend. It is hard to tell difference by looking at the values passed in.

Thanks.
Tina.

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Pull request closed without merging**
