### PR TITLE
[TS] LPS-111076

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-111076

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Common random upgrade failure, testing again

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@ChrisKian @achaparro Please add the unit test to expose this issue then it would be easy to tell if this is fixed.

Thanks.
Tina.

**Comment by ChrisKian** [comment]
Resent here: https://github.com/tinatian/liferay-portal/pull/1758

**Pull request closed without merging**
