### PR TITLE
Lps 70241 next

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by tinatian** [comment]
hi @shuyangzhou  with your change, I can not find any csv files generated. Did you modify the path or something might related to this?

**Comment by tinatian** [comment]
@shuyangzhou  I see, the file is generated, but without ".csv" as postfix

**Comment by shuyangzhou** [comment]
Yeah, see https://github.com/brianchandotcom/liferay-portal/pull/46357. 

I had it fixed, but somehow failed to commit it.

**Comment by shuyangzhou** [comment]
Force pushed the fix

**Pull request closed without merging**
