### PR TITLE
Lps 97259 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@slnn Please run a diff on blog.

@dantewang
If the performance is not good enough, try to use a constant as the template id for all soy template resources, this way the string will be much smaller than before.


Tina.

**Comment by dantewang** [comment]
@tinatian Thanks!

**Comment by tinatian** [comment]
ci:help

**Pull request closed without merging**
