### PR TITLE
[Bug fix] LPS-92372 Weblogic | 2

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:environments

**Comment by vicnate5** [comment]
@tinatian @dantewang Test results look good. Issue in https://github.com/tinatian/liferay-portal/pull/1621#issuecomment-560722250 is now fixed.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8603

**Pull request closed without merging**
