### PR TITLE
[Technical Support] 	LPS-66858 Avoid executing jobs twice after losing connectivity between nodes 

### PR DESCRIPTION
**Pull request by achaparro**
More information here:
https://issues.liferay.com/browse/LPS-66858

Thanks!

### CODE REVIEW

**Comment by achaparro** [comment]
Hi @tinatian,

Did you have the chance to review the pull request? One customer is waiting for the fix and we need your approval taking into account that it's complex.

Thanks.

cc @marianoalvarosaiz, @shuyangzhou

**Comment by tinatian** [comment]
Yes, I have reviewed the code, and I am still working on it, trying to figure out if the fix is right. I know you might have tested your fix and the result showed the problem is fixed. What I am worried about is it might cause other potential problems, especially the usage of the hard code "_EPSILON".

Tina.

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian,
 the _EPSILON_ is only used as a safe measure to check if the trigger has been initially configured to execute in the pass (which should be done only in a clustered environment). The value of 10 seconds was considered enough to discard a delay in the execution of the code and not stablish every trigger as delayed.

cc @achaparro, @shuyangzhou

**Comment by tinatian** [comment]
For "which should be done only in a clustered environment" I did not see you have done any checking about cluster. How should you do this in your code?

Tina.

**Comment by marianoalvarosaiz** [comment]
Sorry if I didn't explain myself correctly. 

In a non clustered environment it will not be possible to create a trigger with an old nextFireTime because the startTime is not created in the pass (nextFireTime cannot be less than startTime because of the own definition of startTime), so an additional checking is not needed. But in a clustered environment, because the trigger information is saved between transitions from master to slave, the start time can be setted to a pass time and the nextFireTime is established by quartz to now because it detects a misfire when setting old dates in triggers.

**Comment by tinatian** [comment]
So you mean if I can make the start date not be a pass time, then the problem is solved, right?

Here are my changes, https://github.com/marianoalvarosaiz/liferay-portal-ee/pull/2. What I am doing is to make the start date be now each time it is scheduled. Could you please test if this fixes your problem?

As far as I can tell, the problem isn't solved even if the start date is now, the reason is, though there is no misfire, the first fire time would also be now, then the job is executed anyway.

Tina.

**Pull request closed without merging**
