### PR TITLE
[SampleSQLBuilder] COMMERCE-7342 Add ability to not add certain portlets to page

### PR DESCRIPTION
**Pull request by dantewang**
cc @slnn @dsitu I changed the 2 boolean properties into a comma delimited list of portlet names. The outcome should be same.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
FYI @shuyangzhou

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
