### PR TITLE
LPD-41116 Update of client extensions through the UI can randomly fail in clustered environments

### PR DESCRIPTION
**Pull request by izaera**
Hey @tinatian, I'm sending you this PR for review as requested by @brianchandotcom here -> https://github.com/brianchandotcom/liferay-portal/pull/155874#issuecomment-2456944101

This is the PR to fix [LPP-56124](https://liferay.atlassian.net/browse/LPP-56124) and it follows the strategy [we already discussed there](https://liferay.atlassian.net/browse/LPP-56124?focusedCommentId=2779539).

Thx :-)

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@izaera there's no test?

**Comment by izaera** [comment]
Hey @tinatian, since we need to test this, can you help me in writing integration tests for this? The setup is fairly complex and the failure is intermitent so not sure how we can tackle this...

Thank you :-)

**Comment by tinatian** [comment]
@izaera I do not think the following is correct by analyzing the code. Your commit message is saying removing undeployClientExtensionEntry is OK as it will be finally invoked by _startWorkflowInstance. Did you debug and test this? What I can see is https://github.com/liferay/liferay-portal/blob/3fd0ca3859793cc5f52b821944ac7706243b5c47/modules/apps/client-extension/client-extension-service/src/main/java/com/liferay/client/extension/service/impl/ClientExtensionEntryLocalServiceImpl.java#L360 is only invoked when oldStatus is WorkflowConstants.STATUS_APPROVED, but in the current case, the old status is what you set here https://github.com/liferay/liferay-portal/blob/3fd0ca3859793cc5f52b821944ac7706243b5c47/modules/apps/client-extension/client-extension-service/src/main/java/com/liferay/client/extension/service/impl/ClientExtensionEntryLocalServiceImpl.java#L319.

> the invocation of _startWorkflowInstance() will get executed after a few lines
> and it will end up triggering an invocation of updateStatus() which will in turn
> deploy or undeploy the CX cluster wide and it will be that process which will
> take care of correctly doing the proper steps in each cluster node atomically.



For integration test, it is hard for me to write it for you. We do not have an integration test support for cluster yet.

**Comment by izaera** [comment]
> Did you debug and test this? 

Yep, I saw it working twice. But maybe I didn't cover all possibilities :thinking: 

Let me recheck it again... Thx

**Comment by izaera** [comment]
Let's see...

So this code:

image

has two explicit branches and a third possibility that does nothing:

1. If the CX is being approved -> it is deployed
2. If the CX was approved but has changed to any other workflow status (DRAFT, DENIED, IN_TRASH, ...) -> it is undeployed

That is exhaustive I think. Meaning that CX will only be deployed when it is approved and undeployed whenever it stops being APPROVED. Right? :thinking: 

Then, this code -> https://github.com/liferay/liferay-portal/blob/3fd0ca3859793cc5f52b821944ac7706243b5c47/modules/apps/client-extension/client-extension-service/src/main/java/com/liferay/client/extension/service/impl/ClientExtensionEntryLocalServiceImpl.java#L319 sets the **new** status to DRAFT and runs the workflow handler after that -> https://github.com/liferay/liferay-portal/blob/3fd0ca3859793cc5f52b821944ac7706243b5c47/modules/apps/client-extension/client-extension-service/src/main/java/com/liferay/client/extension/service/impl/ClientExtensionEntryLocalServiceImpl.java#L326 which invokes `updateStatus()`.

However, let me run it again to make sure, because looking now at the code in `WorkflowHandlerRegistryUtil` it's not 100% clear to me...

**Comment by izaera** [comment]
> For integration test, it is hard for me to write it for you. We do not have an integration test support for cluster yet.

Oh, I see :-( 

@brianchandotcom  told me you wrote integration tests with help of mocking support targetted at clusters, that's why I asked...

@brianchandotcom any other idea on how to reproduce this problem in a test in a meaningful way? I mean, I could write different tests that would look like they are testing something vaguely related to this, but the root cause of the LPP is that *two remote cluster calls are being invoked in parallel in the secondary cluster nodes*, and apparently we cannot simulate that in a test... :thinking: 

I will try to think of some sort of test that adds value, but any suggestion you may think of would be very helpful :-)

**Comment by izaera** [comment]
Continues at https://github.com/liferay-frontend/liferay-portal/pull/4548

**Pull request closed without merging**
