### PR TITLE
[Bug fix] LPS-89886 Patch asm*.jar for Wildfly and JBoss

### PR DESCRIPTION
**Pull request by dantewang**
@tiantian It's actually Wildfly/Glassfish side bug which is not yet fixed, so patch the jars to workaround it following what we did in https://issues.liferay.com/browse/LPS-86863

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang @ChiZelin 
Close as the fix is already merged.

Thanks.
Tina

**Comment by tinatian** [comment]
@dantewang @ChiZelin My bad, reviewing it now

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7374

**Pull request closed without merging**
