### PR TITLE
LPS-111208 Upgrade netty-all in core

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian According to Yuxing, the usage in elasticsearch modules will be addressed in another ticket for search team to handle/review.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
FYI, previous relevant run passed in https://github.com/dantewang/liferay-portal/pull/1598#issuecomment-620497392

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8998

**Pull request closed without merging**
