### PR TITLE
[Bug] LPS-87825 UpgradeStepRegistratorTracker is not using correct configuration

### PR DESCRIPTION
**Pull request by dantewang**
https://issues.liferay.com/browse/LPS-87825; previous ci-test-relevant: https://github.com/dantewang/liferay-portal/pull/897#issuecomment-442385619

### CODE REVIEW

**Comment by tinatian** [comment]
@Preston-Crary Please take this over! 

Thanks!
Tina.

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7127

@yuhai whenever fixing a bug make sure to think if there may be other similar bugs.  It's much better to fix a bunch of bugs of the same type and prevent them then it is to fix them one by one as they are reported.

**Comment by Preston-Crary** [comment]
ci:close

**Comment by yuhai** [comment]
@Preston-Crary, got it, thanks.

**Pull request closed without merging**
