### PR TITLE
Lps 72939 fix

### PR DESCRIPTION
**Pull request by arthurchan35**
@tinatian, @shuyangzhou,
cc @samuelkong,

I added url = url.trim() to getDomain() method to make it consistent with getProtocol() for url with leading/trailing whitespaces. 
It may look duplicate with the the code inside _getProtocolDelimiterIndex(), but it's wont have any performence impact, because after url is trimed in getDomain(), it will be a constant time checking on url when url.trim() called again in _getProtocolDelimiterIndex().

And the current(or original) impl of getProtocol() seems return a protocol with leading whitespaces, that does not look right.

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test

**Review by tinatian — COMMENTED** [review]
Hi @arthurchan35 and @samuelkong,
If you allow leading/trailing white space when getting domain, we should also allow it in PortalImpl.escapeRedirect, right? The behavior should be consistent. 
Could you please take a look at it?

Thanks.
Tina.

**Comment by arthurchan35** [comment]
ci:reopen

**Comment by arthurchan35** [comment]
Hi @tinatian,
I have attached an additonal commit to trim the input for escapeRedirect, but I just want to say that, the previous(current) implementation of getDomain() trims input while escapeRedirect() does not. It was not consistent to begin with though.

**Comment by arthurchan35** [comment]
ci:retest

**Comment by shuyangzhou** [comment]
ci:close

See https://github.com/brianchandotcom/liferay-portal/pull/57824

**Pull request closed without merging**
