### PR TITLE
[DB Paritioning] LPS-108590 Additional places found by benchmark testing

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian So far fixing these two places can make portal work on our generated database.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Close it as Alberto will take care of it. Please use this workaround for setting up db partition test.

Tina.

**Comment by tinatian** [comment]
@dantewang @slnn Please send the reproduce steps to Alberto including the database you used, he would like to fix this all together with other issues.

Thanks.

Tina.

**Pull request closed without merging**
