### PR TITLE
Lps 111696

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@mtambara Looks like a unique failure here, can you take a look?
```
ERROR [com.liferay.portal.events.test-executor-thread][SearchPermissionCheckerImpl:159] com.liferay.portal.kernel.exception.NoSuchRoleException: No Role exists with the key {companyId=0, name=Guest}
```
https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1,label_exp=!master/137406//consoleText

**Comment by tinatian** [comment]
@mtambara I am going to close this pull as @vicnate5 's comment. Please fix and resend.

Thanks.
Tina.

**Pull request closed without merging**
