### PR TITLE
[TS] LPS-115438

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-115438

From @wanderlast:

> When using a beta or partially supported language/locale in Liferay some language keys may still be displayed with the words "Automatic Copy" or "Automatic Translation" appended to them. When we fail to find a key-value match in our given locale (which is likely when it comes to our beta languages since we don't have full language.properties coverage for them), we check the aggregate bundle. However, after retrieving from the aggregate bundle, we do not do the same processing (e.g. running fixValue()) that we do when retrieving using LanguageUtil. This adds that missing check to ensure we properly strip the automatically added notations from the displayed value.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@ChrisKian Could you please add unit or integration test for it?

Thanks.
Tina.

**Comment by ChrisKian** [comment]
Resent here: https://github.com/tinatian/liferay-portal/pull/1881

**Pull request closed without merging**
