### PR TITLE
Lps 78225 journal service part3

### PR DESCRIPTION
**Pull request by tomwang2011**

### CODE REVIEW

**Comment by tomwang2011** [comment]
ci:test

**Comment by tomwang2011** [comment]
@tinatian I double checked https://github.com/tinatian/liferay-portal/pull/848/commits/ec948343e15dfd5c1639a72acd6ac9bd9084b7d3 and I think we shouldn't use reflection to get the method in this case. 

Because `JournalArticleLocalServiceUtil` cannot directly call the `JournalArticleLocalServiceImpl: protected void checkStructure(JournalArticle, DDMStructure) ` method (original logic).  We use `JournalArticleLocalServiceUtil` to call the `JournalArticleLocalServiceImpl: public void checkStructure(long, String, double)`, it will call `protected void checkStructure(JournalArticle)` and that method will call `protected void checkStructure(JournalArticle, DDMStructure)` (which is the same method as original logic above)

The reason we are asserting the log is that during the middle step ([protected void checkStructure(JournalArticle)](https://github.com/liferay/liferay-portal/blob/13b9a1d7d77a447c802721809fe7ff63f6a75c31/modules/apps/web-experience/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L6965)), it catches the Expected exception and logs it instead, so we will just assert the log.

This way the logic is the same and we do not need to do reflection for the method. 

Thanks!

**Comment by tinatian** [comment]
@tomwang2011 what I mean is to get the object of JournalArticleLocalServiceImpl and invoke its protected method by reflection. It should have nothing to do with the JournalArticleLocalServiceUtil.

We can get the object of JournalArticleLocalServiceImpl by Inject annotation, right?

Tina.

**Comment by tomwang2011** [comment]
I see, i think I know what you mean now, I will make that change and repush as CI is broken to test right now anyway, thanks!

**Comment by tomwang2011** [comment]
@tinatian I am looking at trying to make this change, I can't seem to get JournalArticleLocalServiceImpl by injection of JournalArticleLocalService, I think this is because JournalArticleLocalServiceImpl isn't a component right? JournalArticleServiceImpl doesn't seem to be a component either.

**Comment by tomwang2011** [comment]
nevermind I don't think that was the issue, going to debug it a bit to see why the Inject isn't working

**Pull request closed without merging**
