### PR TITLE
[deprecation] LPS-106167 UploadHandler, HashUtil and StringPool

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
The SF failure is irrelevant, the class is not touch by LPS-106167.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8666

**Pull request closed without merging**
