### PR TITLE
LPS-83764 LiferayObjectWrapperTest

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian 
Most of the assertions follow the procedure below:
```
call LiferayObjectWrapper method -> assert result instanceof -> cast result to actual template model -> assert content of the actual template model
```

A method is added to encapsulate this procedure and applied to all the tests matching this procedure.

cc @caixiangyue

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
ci:retest

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:stop

**Comment by tinatian** [comment]
@dantewang @caixiangyue 
I think we need to refine the logic in LiferayObjectWrapper first.

For example, handleUnknownType() also handles TemplateNode, this part of code is not going to be invoked, because we already handled TemplateNode in warp().

By the way, I do not like the _assertLiferayObjectWrapperAction method in test class, it is too complicate and hard to understand, we do not have to do this kind of abstraction for test. It is better that it is easy to read and maintain.

Tina.

**Pull request closed without merging**
