### PR TITLE
LPS-111762 Use new create method to avoid generating duplicate JournalDisplayContext per request.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian,
 should I sent this PR to you?
Kind regards.

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
FYI @shuyangzhou Forward to Brian

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
