### PR TITLE
Lps 10588 12

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
There are a couple of unique poshi failures here, will look into them.

**Comment by vicnate5** [comment]
@tinatian See also Calendar failures: https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/394827/

**Comment by vicnate5** [comment]
Functional Regression, shows up in 2 places:

### Adding an Organization Site
1. Go to Control Panel > Users > Users and Organizations
2. Select "Organizations" tab
3. Add a new Organization > Input required "Name" > Save
4. Go to "Organization Site" on the sidebar
5. Switch "Create Site" to "Yes"
6. Set "Public Pages" to "Community Site"
7. Save

Expected Result: User given success message
Actual Result: Page never stops loading (Site looks to be created successfully)

### Adding a User Group
1. Go to Control Panel > Users > User Groups
2. Add new User Group
3. Input Name
4. Set "My Profile" to "Community Site"
5. Save

Expected Result: User given success message
Actual Result: Page never stops loading

Error seen in logs
```
2020-05-26 22:19:14.131 ERROR [liferay/export_import_lifecycle_event_sync-3][JDBCExceptionReporter:234] Lock wait timeout exceeded; try restarting transaction
2020-05-26 22:19:14.135 ERROR [liferay/export_import_lifecycle_event_sync-3][ExportImportProcessCallbackLifecycleListener:73] Unable to execute export import process callback
org.springframework.dao.CannotAcquireLockException: Could not execute JDBC batch update; SQL [insert into ResourcePermission (mvccVersion, ctCollectionId, companyId, name, scope, primKey, primKeyId, roleId, ownerId, actionIds, viewActionId, resourcePermissionId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; nested exception is org.hibernate.exception.LockAcquisitionException: Could not execute JDBC batch update
	at org.springframework.orm.hibernate3.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:651)
	at org.springframework.orm.hibernate3.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:800)
	at org.springframework.orm.hibernate3.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:671)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:744)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:712)
	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.commit(DefaultTransactionExecutor.java:41)
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:77)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
	at com.liferay.portal.spring.aop.RetryAdvice.invoke(RetryAdvice.java:100)
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
	at com.sun.proxy.$Proxy28.setResourcePermissions(Unknown Source)
	at com.liferay.portal.kernel.service.ResourcePermissionLocalServiceUtil.setResourcePermissions(ResourcePermissionLocalServiceUtil.java:995)
	at com.liferay.exportimport.internal.util.ExportImportPermissionUtil.updateResourcePermissions(ExportImportPermissionUtil.java:142)
	at com.liferay.exportimport.internal.util.ExportImportPermissionUtil.updateResourcePermissions(ExportImportPermissionUtil.java:119)
	at com.liferay.exportimport.internal.lar.PortletDataContextImpl.importPermissions(PortletDataContextImpl.java:1450)
	at com.liferay.exportimport.internal.lar.PortletDataContextImpl.importPortletPermissions(PortletDataContextImpl.java:1465)
	at com.liferay.comment.page.comments.web.internal.exportimport.data.handler.PageCommentsPortletDataHandler$ImportCommentsCallable.call(PageCommentsPortletDataHandler.java:216)
	at com.liferay.comment.page.comments.web.internal.exportimport.data.handler.PageCommentsPortletDataHandler$ImportCommentsCallable.call(PageCommentsPortletDataHandler.java:197)
	at com.liferay.exportimport.internal.lifecycle.ExportImportProcessCallbackLifecycleListener.onProcessSucceeded(ExportImportProcessCallbackLifecycleListener.java:70)
	at com.liferay.exportimport.lifecycle.DefaultProcessAwareExportImportLifecycleListener.onProcessSucceeded(DefaultProcessAwareExportImportLifecycleListener.java:222)
	at com.liferay.exportimport.lifecycle.DefaultProcessAwareExportImportLifecycleListener.callProcessHandlers(DefaultProcessAwareExportImportLifecycleListener.java:98)
	at com.liferay.exportimport.lifecycle.DefaultProcessAwareExportImportLifecycleListener.onExportImportLifecycleEvent(DefaultProcessAwareExportImportLifecycleListener.java:47)
	at com.liferay.exportimport.lifecycle.BaseExportImportLifecycleMessageListener.doReceive(BaseExportImportLifecycleMessageListener.java:45)
	at com.liferay.portal.kernel.messaging.BaseMessageListener.doReceive(BaseMessageListener.java:48)
	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:31)
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
	at com.liferay.portal.messaging.internal.SynchronousDestination.lambda$dispatch$0(SynchronousDestination.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.hibernate.exception.LockAcquisitionException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:107)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:275)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:268)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:184)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:321)
	at com.liferay.portal.dao.orm.hibernate.event.NestableFlushEventListener.onFlush(NestableFlushEventListener.java:61)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:383)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:133)
	at org.springframework.orm.hibernate3.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:663)
	... 29 more
Caused by: java.sql.BatchUpdateException: Lock wait timeout exceeded; try restarting transaction
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.util.Util.handleNewInstance(Util.java:192)
	at com.mysql.cj.util.Util.getInstance(Util.java:167)
	at com.mysql.cj.util.Util.getInstance(Util.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLError.createBatchUpdateException(SQLError.java:224)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:855)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchInternal(ClientPreparedStatement.java:437)
	at com.mysql.cj.jdbc.StatementImpl.executeBatch(StatementImpl.java:814)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:125)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:70)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:268)
	... 37 more
Caused by: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:123)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1094)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeBatchSerially(ClientPreparedStatement.java:834)
	... 43 more
```

**Comment by achaparro** [comment]
Hi @tinatian @vicnate5,

I have added this [commit](https://github.com/achaparro/liferay-portal/pull/580/commits/3b1170bb71eb9a1c92b62c61e85d9fc6a28ddee6) to this pull and the issues related to stale errors and others are solved:
https://github.com/achaparro/liferay-portal/pull/580

@tinatian since now we commit the transaction when we call to Syncronized Destinations ([here](https://github.com/achaparro/liferay-portal/pull/580/commits/e351bcd94eb63901cc4ee776035ff1c19c4deb56)) we can get stale object exceptions when we modified several times the same object because the mvccVersion is updated in the session but the entity cache remains the same (first update). I don't know if this the proper solution but it only affect the tests.

**Comment by tinatian** [comment]
Fix and resend at https://github.com/tinatian/liferay-portal/pull/1841

**Pull request closed without merging**
