### PR TITLE
LPS-145919

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian ,

I remove unused properties "scripting.jruby.compile.mode", and updated to propskeys.java, propsvalues.java and verifyproperties.java.
It was created in commit aebeb0615bbec153de9de580be2df9b64973791b, see LPS-15289
It was moved to modules/portal/portal-scripting-ruby/src/com/liferay/portal/scripting/ruby/internal/RubyExecutor.java based on commit ea717633d0a221e785c059faa717b4b51e6fe9a9, see LPS-55505.
It was moved to modules/portal/portal-scripting-ruby/src/com/liferay/portal/scripting/ruby/configuration/RubyScriptingConfiguration.java based on commit 6393d1b9415eefb7528154e27e438a3dd182f5f9, see LPS-55505
It was deleted the used in commit 80ab259b5bbb3024906b446858a7c5b6b59cc2ed, see LPS-96677
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/tinatian/liferay-portal/pull/2493#issuecomment-1023750175

**Pull request closed without merging**
