### PR TITLE
Lps 122190 lps 122225 6

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@GinsonRen I updated the pull, please run MB and WC again.

FYI @dantewang
Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:stable

**Comment by slnn** [comment]
Hi @tinatian 

Here are test results for WC and MB:

WC:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Changes(%)
-- | -- | -- | -- | -- | --
BaseLine | 51d5565 | 52104 | 758 | 231 | -
PR-2006 | - | 52711 | 757 | 222 | 1.164977737


MB:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB THread | Session Count Changes(%)
-- | -- | -- | -- | -- | --
BaseLine | 51d5565 | 16524 | 90.5 | 133 | -
PR-2006 | - | 16566 | 79.8 | 119 | 0.2541757444


Lily

**Pull request closed without merging**
