### PR TITLE
LPS-88710 Scheduler 3

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Hai has tested with both OSGi jar and WAB war.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Comment by yuhai** [comment]
please see https://github.com/tinatian/liferay-portal/pull/1159

**Comment by dantewang** [comment]
Closing since it's rebased and resent at https://github.com/tinatian/liferay-portal/pull/1159

**Pull request closed without merging**
