### PR TITLE
LPS-145345

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian ,

I remove unused properties "default.guest.public.layout.column-", which included "default.guest.public.layout.column-1
default.guest.public.layout.column-2, default.guest.public.layout.column-3, default.guest.public.layout.column-4".

"DEFAULT_GUEST_PUBLIC_LAYOUT_PREFIX" was used in "GroupLocalServiceImpl.java" in commit c7cf42ba0a3bdbd227fbbf39479fc7354dc9bf75, see LPS-40387, and was moved to "AddDefaultLayoutPortalInstanceLifecycleListener.java" in commit da7a3b118cfa58d0441c5b00dc90c466f9ef98cd, see LPS-109350. It was finally deleted the use in commit 93f861d864b6c24ace7bdc6f7b16a855d2e07b6d, see LPS-124483.

Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 Code looks good to me, please put it into your list, I am going to close this pull.

Thanks.
Tina

**Pull request closed without merging**
