### PR TITLE
LPS-X Unit test for EntityCacheImpl

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
The following lines are not covered:

> [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl line 77 is not covered
> [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl line 203 is not covered
> [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl line 276 is not covered
> [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl line 277 is not covered

Line 77 can only be fully covered after [LPS-83545](https://github.com/tinatian/liferay-portal/pull/940)
Line 276 and 277 will be covered by the test I added for [LPS-83597](https://issues.liferay.com/browse/LPS-83597).

Line 203, I'm not sure how to cover it.

**Comment by dantewang** [comment]
@tinatian 

The following lines are not covered:

> [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl line 77 is not covered
> [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl line 203 is not covered
> [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl line 276 is not covered
> [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl line 277 is not covered

Line 77 can only be fully covered after LPS-83545
Line 276 and 277 will be covered by the test I added for LPS-83597.

Line 203, I'm not sure how to cover it.

**Comment by tinatian** [comment]
@dantewang I did not Line 203 is not covered, here are my result:
`com.liferay.portal.cache.internal.dao.orm.EntityCacheImplTest STANDARD_OUT

    [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl is not fully covered.
    [Whip]Branch coverage rate : 0.99, line coverage rate : 0.99.
    [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl line 77 is not covered 
    [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl line 278 is not covered 
    [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl line 279 is not covered 
    [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl$LocalCacheKey is fully covered.
`

I am using 5eff7fcaabee0e37bd8262bc72905a30dae0fe34

**Comment by dantewang** [comment]
@tinatian I'm still getting it (sorry it should be line 205):

```
    [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl is not fully covered.
    [Whip]Branch coverage rate : 0.99, line coverage rate : 0.98.
    [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl line 77 is not covered 
    [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl line 205 is not covered 
    [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl line 278 is not covered 
    [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl line 279 is not covered 
    [Whip] com.liferay.portal.cache.internal.dao.orm.EntityCacheImpl$LocalCacheKey is fully covered.
```

I executed the test using `../gradlew :apps:portal-cache:portal-cache-impl:test --tests=com.liferay.portal.cache.internal.dao.orm.EntityCacheImplTest`.

**Pull request closed without merging**
