### PR TITLE
LPS-110862 UnsyncStringWriter and StringBundler

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
According to Echo team, the content & fragment test failures should be fixed by [87678](https://github.com/brianchandotcom/liferay-portal/pull/87678), and have been merged.

Rerun relevant test and to check the new results.

**Comment by zhangyan0701** [comment]
Testray results:
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1114068955

Site Template test failures will be fixed in https://issues.liferay.com/browse/LRQA-57955.
App Builder test failures are not related,  pushed forward to  App Builder team QA to take care of this.
https://issues.liferay.com/browse/LRQA-57932

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Close as code conflicts, please resend

**Pull request closed without merging**
