### PR TITLE
LPS-108588 DB Partition: Listeners

### PR DESCRIPTION
**Pull request by achaparro**
Hi @tinatian,

After analyzing all cases I think the results are simpler than expected.

We have three kinds of listeners:
1. Global, they don't need to be executed in a specific database
2. Portal, they need to be executed in all partitions
3. Object, they need to be executed in a single partition

And two ways to execute them:
- Scheduled jobs
- Sending a message to a destination

This pull covers all possible cases.

For the case 1, we just need to exclude then with the configuration. We can exclude the destination or the listeners in case they use the scheduled_dispatch:
https://github.com/tinatian/liferay-portal/pull/1817/commits/a3f90b6b57c8271f31fd7942c314061808794d65#diff-1330ab12672c16a9931f208a8d33ac9aR29

For the case 2, they will be intercepted and executed once per company except for those cases that already run over the companies that need to be excluded. I have created a base class for them:
https://github.com/tinatian/liferay-portal/pull/1817/commits/058e87e993d090f724d2d94cda43abe884aba3d0#diff-59146f1adbec647e6b2c6b7a9120396eR28

For the case 3, we always set the companyId in the message using the companyThreadLocal when we call sendMessage so this is already cover. When we schedule them, we need to set it manually as you can see here:
https://github.com/tinatian/liferay-portal/pull/1817/commits/bf3f90e61dec945e0822a65894b5ecf49877d265

Please, let me know if you have any question.

Thanks.

PS: The tests passed in my repo.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
@tinatian error is unrelated, it is present in all pull requests

**Comment by achaparro** [comment]
Hey @tinatian,

Did you have the chance to look at this? I have to focus on other features of DB Partition and depending on the resolution for this case I would have to take one approach or another.

Thanks.

**Comment by tinatian** [comment]
@achaparro Sorry, was blocked by other stuff, I will review this the first thing next week.

**Comment by tinatian** [comment]
@achaparro By the way, there are failures on ci:test:relevant, is it related to your change?

Tina

**Comment by achaparro** [comment]
ok @tinatian, no worries, thanks for the update, have a nice weekend

**Comment by achaparro** [comment]
Hi @tinatian,

Regarding the error on ci:test:relevant, it's unrelated, I already mentioned it here:
https://github.com/tinatian/liferay-portal/pull/1817#issuecomment-624723613

Last week someone missed to execute semver and all the pulls got the same error.

**Comment by tinatian** [comment]
According to our talk, I close this and please resent.

Thanks.
Tina.

**Pull request closed without merging**
