### PR TITLE
[Bug fix] LPS-129172 jackson-databind

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This is for upgrading jackson-databind in core and unify the jackson-databind dependencies across the portal. I will send another pull to apply the pattern to other patching modules that removes files from original jar.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang The latest version of jackson-databind is 2.12.2, but you are upgrading to 2.10.5.1, any reason stops you upgrading to the latest?

Tina

**Comment by dantewang** [comment]
See https://github.com/tinatian/liferay-portal/pull/2199

**Pull request closed without merging**
