### PR TITLE
Lps 135570 9 29 test

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results?

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian Session replication logging showing ClassNotFoundException.
```
SEVERE [Tribes-Task-Receiver[Catalina-Channel]-3] org.apache.catalina.ha.session.DeltaManager.deserializeSessions ClassNotFoundException while loading persisted sessions: [java.lang.ClassNotFoundException: com.liferay.portal.kernel.util.TransientValue]
     [exec]     	java.lang.ClassNotFoundException: com.liferay.portal.kernel.util.TransientValue
     [exec]     		at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [exec]     		at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [exec]     		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [exec]     		at java.lang.Class.forName0(Native Method)
     [exec]     		at java.lang.Class.forName(Class.java:348)
     [exec]     		at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:677)
     [exec]     		at org.apache.catalina.tribes.io.ReplicationStream.resolveClass(ReplicationStream.java:77)
     [exec]     		at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1819)
     [exec]     		at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1713)
     [exec]     		at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1986)
     [exec]     		at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
     [exec]     		at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
     [exec]     		at org.apache.catalina.ha.session.DeltaSession.doReadObject(DeltaSession.java:867)
     [exec]     		at org.apache.catalina.ha.session.DeltaSession.readObjectData(DeltaSession.java:638)
     [exec]     		at org.apache.catalina.ha.session.DeltaManager.deserializeSessions(DeltaManager.java:682)
     [exec]     		at org.apache.catalina.ha.session.DeltaManager.handleALL_SESSION_DATA(DeltaManager.java:1391)
     [exec]     		at org.apache.catalina.ha.session.DeltaManager.messageReceived(DeltaManager.java:1236)
     [exec]     		at org.apache.catalina.ha.session.DeltaManager.messageDataReceived(DeltaManager.java:997)
     [exec]     		at org.apache.catalina.ha.session.ClusterSessionListener.messageReceived(ClusterSessionListener.java:77)
     [exec]     		at org.apache.catalina.ha.tcp.SimpleTcpCluster.messageReceived(SimpleTcpCluster.java:821)
     [exec]     		at org.apache.catalina.ha.tcp.SimpleTcpCluster.messageReceived(SimpleTcpCluster.java:803)
     [exec]     		at org.apache.catalina.tribes.group.GroupChannel.messageReceived(GroupChannel.java:345)
     [exec]     		at org.apache.catalina.tribes.group.ChannelInterceptorBase.messageReceived(ChannelInterceptorBase.java:96)
     [exec]     		at org.apache.catalina.tribes.group.ChannelInterceptorBase.messageReceived(ChannelInterceptorBase.java:96)
     [exec]     		at org.apache.catalina.tribes.group.interceptors.TcpFailureDetector.messageReceived(TcpFailureDetector.java:118)
     [exec]     		at org.apache.catalina.tribes.group.ChannelInterceptorBase.messageReceived(ChannelInterceptorBase.java:96)
     [exec]     		at org.apache.catalina.tribes.group.ChannelCoordinator.messageReceived(ChannelCoordinator.java:288)
     [exec]     		at org.apache.catalina.tribes.transport.ReceiverBase.messageDataReceived(ReceiverBase.java:272)
     [exec]     		at org.apache.catalina.tribes.transport.nio.NioReplicationTask.drainChannel(NioReplicationTask.java:229)
     [exec]     		at org.apache.catalina.tribes.transport.nio.NioReplicationTask.run(NioReplicationTask.java:103)
     [exec]     		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]     		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]     		at java.lang.Thread.run(Thread.java:745)
     [exec]     30-Sep-2021 20:00:58.889 SEVERE [Tribes-Task-Receiver[Catalina-Channel]-3] org.apache.catalina.ha.session.DeltaManager.messageReceived Manager [localhost#]: Unable to receive message through TCP channel
     [exec]     	java.lang.ClassNotFoundException: com.liferay.portal.kernel.util.TransientValue
```
[Full log from CI ](https://testray.liferay.com/reports/production/logs/2021-09/test-1-29/test-portal-acceptance-pullrequest(master)/362/functional-tomcat90-mysql57-jdk8/0/10/jenkins-console.txt.gz)

This is being thrown after starting both 2 cluster nodes under session replication configuration.

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
@tinatian See https://testray.liferay.com/reports/production/logs/2021-10/test-1-25/test-portal-acceptance-pullrequest(master)/467/functional-tomcat90-mysql57-jdk8/0/10/jenkins-console.txt.gz

**Pull request closed without merging**
