### PR TITLE
pull-request-69260

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@tinatian came to me from https://github.com/brianchandotcom/liferay-portal/pull/69260

**Comment by tinatian** [comment]
Hi @topolik @csierra,
You kept everything in the master, what if the master died? can you afford the missing of those data? If not, you need a way to backup the data and restore it when master died.

Please refer to logic in https://github.com/tinatian/liferay-portal/blob/master/modules/apps/portal-scheduler/portal-scheduler-multiple/src/main/java/com/liferay/portal/scheduler/multiple/internal/ClusterSchedulerEngine.java, the field "_memoryClusteredJobs" has same problem like you here.

I am currently full of load with kind of release blockers, please try it first, any question, please feel free to let me know.

By the way, is this related to the email you guys asked about setting replicatePutsViaCopy=true for modules? If yes, is possible that you wait for some time for this feature?


Tina.

**Comment by topolik** [comment]
Hi Tina, we are fine loosing them, the tokens are temporary. Can this be
merged or how should we proceed?

Thanks.

-- tom +

**Comment by tinatian** [comment]
Forward to Brian at https://github.com/brianchandotcom/liferay-portal/pull/69407.

**Comment by tinatian** [comment]
@topolik 
Just curious, you said you are fine losing data, suppose I have a cluster of three, node1, node2, node3.
At the begining, node1 is master, and node3 can get something from it by a key.
Later, master is changed to node2, which has nothing data in its queue, and node3 try to get something by same key, but get nothing.

This means the behavior on node3 is inconsistent, it does not seem right for me, but I am not sure if this is OK under your case.


Thanks.
Tina.

**Pull request closed without merging**
