### PR TITLE
[Bug Fix] LPS-135589

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@tinatian Just to clarify, my change on `DLAppServiceWhenAddingAFileEntryTest` is not attempting to fix the failure of test case `DLAppServiceWhenAddingAFileEntryTest.testShouldCallWorkflowHandler`. I just apply the same pattern since `testShouldSucceedWithConcurrentAccess` case creates a new thread.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10371

**Pull request closed without merging**
