### PR TITLE
LPS-145920

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian ,

I remove unused properties "calendar.publish.to.live.by.default", and updated to propskeys.java, propsvalues.java and verifyproperties.java.
It was added in commit 2ab2852ca6f67753b23774adfac6b7644b42a5f7, see LPS-38573, and it was used in "CalendarPortletDataHandler.java".
It was removed the usage in commit db73f08fdc16766c36bb41c237614293b1b19673, see LPS-43918
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/tinatian/liferay-portal/pull/2493#issuecomment-1023750175.

**Pull request closed without merging**
