### PR TITLE
[TS] LPS-110895

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-110895

From @wanderlast:

> This is the fix from tinatian#1757, now with an integration test that should cover it as well as the other stores' implementations of getFileVersions().

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@ChrisKian @wanderlast The failure is real, please fix and resend.

Thanks.
Tina.

**Pull request closed without merging**
