### PR TITLE
[portal-impl-integration] LPS-97911 com.liferay.portal.spring tests

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang  @yuhai
I think you are using a wrong ticket number in the last commit, fixed it in my pull. See https://github.com/shuyangzhou/liferay-portal/pull/8008.

Also, I did not merge the bug expose and fix, please create a new ticket and resend to me.

Thanks.
Tina.

**Comment by dantewang** [comment]
@tinatian Thanks!

@yuhai Please create a new ticket as Tina said and resend that part.

**Comment by yuhai** [comment]
@dantewang, @tinatian
Got it, I will resend it after the fix is merged to master.

**Pull request closed without merging**
