### PR TITLE
[TS] LPS-123755

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @tinatian ,

Ticket: [LPS-123755](https://issues.liferay.com/browse/LPS-123755)

Can you help review this PR?

**Context**
This PR is a fix for Velocity and is similar to the Freemarker ticket you worked on recently: [LPS-123728](https://issues.liferay.com/browse/LPS-123728). 

**Proposed Fix**
The main solution is based on the changes you made for Freemarker.
The additional change is to attempt to handle a race condition.

The fix can be broken up into two parts: 
- Apply your changes to centralize managing **_secondLevelPortalCache** within **VelocityTemplateResourceCache**
- Tweak the **`@modified`** implementation to re-activate only if necessary

**Edge Case - Still Reproducible**
Even with this change, the NPE is still reproducible, if you continuously switch the **modificationCheckInterval** from **0** to **another number** and vice-versa.
- Since this results in the deactivate + activate methods to be called.

----

For additional notes of our testing and approach, please see my latest comment in: [PTR-2285#comment-2389442](https://issues.liferay.com/browse/PTR-2285?focusedCommentId=2389442&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2389442)

Please let us know if there's anything you would like us to change on our end and if you have any questions.
Thanks!

/cc @noornajj

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@ericyanLr For the edge case you mentioned:

> Edge Case - Still Reproducible
Even with this change, the NPE is still reproducible, if you continuously switch the modificationCheckInterval from 0 to another number and vice-versa.

Does it happen on freemarker or velocity or both?

Tina.

**Comment by ericyanLr** [comment]
@tinatian From my testing, I was only able to reproduce w/ Velocity. 
The changes I made to Freemarker are just for consistency.

**Comment by tinatian** [comment]
@ericyanLr 
If you can still reproduce it on velocity, most probably you did not fix all the dependencies it refers to, please set a break point at  `TemplateManagerUtil` to see if someone is still trying to remove velocity template engine, then you would know what to fix.

Also you do not need to tweak @Modified method, it is only invoking deactivate() and activate() methods, it won't introduce any lifecyle related logic from osgi service, and it should be safe. 

Your current change has a potential leaking, suppose I have the cache enabled, then I disable the cache by setting to 0, I will still have the related portal cache and its second level cache alive even if no one is using it, and when the service is deactivated, the caches can not be removed as it is marked as "disabled".


Tina.

**Comment by ericyanLr** [comment]
Hi @tinatian ,

Just wanted to follow-up on your comment.

**Game Plan**
As discussed, the game plan will be to first handle this issue for Freemarker in [LPS-128866](https://issues.liferay.com/browse/LPS-128866). We can also use [PTR-2285](https://issues.liferay.com/browse/PTR-2285) for further discussions as well.

**Regarding:**

> If you can still reproduce it on velocity, most probably you did not fix all the dependencies it refers to, please set a break point at TemplateManagerUtil to see if someone is still trying to remove velocity template engine, then you would know what to fix.

I was able to resolve the **TemplateManager** NPE errors, after including the @modified annotation to **VelocityTemplateResourceCache.java**

This then revealed other race-condition errors, which the other commits try to handle.

**Regarding:**
> Also you do not need to tweak @Modified method, it is only invoking deactivate() and activate() methods, it won't introduce any lifecyle related logic from osgi service, and it should be safe.

The issue is that **deactivate()** causes the **_secondLevelPortalCache** to be removed, leaving it in a shutdown status. And since we allow other classes to retrieve this via **getSecondLevelPortalCache()**, the other classes can still hold a reference to this cache and attempt to use it in it's shutdown state, which is what leads to the exceptions.

**Regarding:**
> Your current change has a potential leaking, suppose I have the cache enabled, then I disable the cache by setting to 0, I will still have the related portal cache and its second level cache alive even if no one is using it, and when the service is deactivated, the caches can not be removed as it is marked as "disabled".

For my proposed change, if the **modificationCheckInterval** is set to **0**, it should actually go through the normal **deactivate()** and **activate()** methods, unless I missed something.

----

I'll leave this PR open for now, feel free to change the status.

Please let me know if you have any questions or if you would like to change the game plan.
Thanks!

**Comment by tinatian** [comment]
@ericyanLr Please see https://github.com/shuyangzhou/liferay-portal/pull/9848. I am not sure if my fix also covers what's need for velocity, please send me a a pull based on it if not, I am going to close this pull.

Thanks.
Tina.

**Pull request closed without merging**
