### PR TITLE
LPS-74116 Modify method signature, add "throws"

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:reopen

**Comment by tinatian** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/4689

**Comment by tinatian** [comment]
@dantewang @ChiZelin Do we really need to modify signature of DummyPortletURL?

Tina.

**Comment by tinatian** [comment]
@dantewang @ChiZelin Could you please explain how TCK is checking the signature? Is it doing by reflection? A thing I am worried about is if there is some customer add a wrapper on our code, and forgot to define the exceptions, is it going to fail on TCK checking?

**Comment by dantewang** [comment]
@tinatian Yes it uses reflection.

See https://github.com/liferay/portals-pluto/blob/master/portlet-tck_3.0/common/src/main/java/javax/portlet/tck/beans/ClassChecker.java

Also see the usage in test cases:

https://github.com/liferay/portals-pluto/blob/master/portlet-tck_3.0/V2SigTestsEnv/src/main/java/javax/portlet/tck/portlets/SigTestsEnv_PortletSession_SIGRender.java#L115

Shouldn't a wrapper be added to wrap a javax.portlet interface instead of our specific impl?

**Comment by tinatian** [comment]
@dantewang So if DummyPortletURL is not used at runtime, it will not fail the TCK checking, right?

**Comment by dantewang** [comment]
@tinatian Yes I think so. The TCK test is actually checking this via a portlet deployed to portal at runtime; as long as there's no way for the portlet to get an instance of DummyPortletURL, it won't fail.

**Comment by tinatian** [comment]
@dantewang OK, could you please retest and confirm it?

**Comment by dantewang** [comment]
@tinatian Sure

**Pull request closed without merging**
