### PR TITLE
[SampleSQLBuilder] LPS-131273 resend

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Sort parameters according to service.xml and resend as per https://github.com/brianchandotcom/liferay-portal/pull/102813#issuecomment-855166056

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang @slnn Conflicts, please rebase and resend to Brian directly, cc me and shuyang. 

Thanks.
Tina.

**Comment by slnn** [comment]
Rebase and resend in https://github.com/dantewang/liferay-portal/pull/1999

**Pull request closed without merging**
