### PR TITLE
LPS-115394 If there's a trigger for same jobName, groupName persisted, reuse it, instead of scheduling it, since it can already exist.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian,
 did you have time to take a look to this PR?
Kind regards.

**Comment by tinatian** [comment]
@marianoalvarosaiz I closed the ticket, and please see my comment https://issues.liferay.com/browse/LPS-115394?focusedCommentId=2183951&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2183951. 

Thanks.
Tina.

**Pull request closed without merging**
