### PR TITLE
LPS-145344

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian , 

I remove unused properties "look.and.feel.modifiable", and it was finally deleted the use based on commit 5106ccbe3b6ec648b2cfd768460f76023db002cf, see LPS-15178.
Thanks for checking!

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 The property is not removed by 5106ccbe3b6ec648b2cfd768460f76023db002cf. Please modify the commit message and resend to **liferay-core-infra**.

Thanks.
Tina.

**Pull request closed without merging**
