### PR TITLE
Lps 135570 9 10

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result?

**Comment by vicnate5** [comment]
Triggered additional testing at https://github.com/vicnate5/liferay-portal/pull/1837 with the unmerged session replication functional test.

**Comment by vicnate5** [comment]
@tinatian real failures here.

Some redirects are not working in the UI with `portlet.session.replicate.enabled=true` (Set in https://github.com/tinatian/liferay-portal/pull/2387/commits/06309efdf1e0c073e1d0d488bace3a6ec051267d).

**Steps to Reproduce 1**
1. Go to Global Menu > Control Panel > Users and Organizations
2. Add new user. Input required fields
3. Click "Save"

*Expected Result:* Redirected to User edit page with UI message "The user was created successfully. You can now add additional information about the user." This result is seen when I set `portlet.session.replicate.enabled=false`

*Actual Result:* Redirected to blank new user creation creation screen

**Steps to Reproduce 2**
1. Go to Global Menu > Commerce > Channels
2. Add new channel. Input required fields
3. Click "Add"
4. Click "Save"

*Expected Result:* User given success message. This result is seen when I set `portlet.session.replicate.enabled=false`

*Actual Result:* No success message on Save.

**Comment by vicnate5** [comment]
Results from https://github.com/vicnate5/liferay-portal/pull/1837#issuecomment-917308563 show that session replication is working, but the Gogo shell portlet also has a similar redirect issue, which causes other cluster test failures.

**Pull request closed without merging**
