### PR TITLE
LPS-112056 Fix headless

### PR DESCRIPTION
**Pull request by dantewang**
Fix the headless failure seen in https://github.com/shuyangzhou/liferay-portal/pull/9152. It turns out to be a bug in headless, passing wrong parameters.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by jacobcerda** [comment]
Error ([Full Log](https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/325661/consoleText)):
     [exec] com.liferay.calendar.service.test.CalendarBookingLocalServiceTest > testDeleteStagingCalendarBookingDeletesLiveCalendarBooking FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at com.liferay.portal.service.permission.GroupPermissionImpl.contains(GroupPermissionImpl.java:96)
     [exec]     	at com.liferay.portal.service.permission.GroupPermissionImpl.contains(GroupPermissionImpl.java:118)
     [exec]     	at com.liferay.portal.service.permission.GroupPermissionImpl.check(GroupPermissionImpl.java:64)

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9159

**Pull request closed without merging**
