### PR TITLE
LPS-122988 Always try to check resource actions during startup

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

Lily has verified that this change works with our generated SQL.

For startup performance:

Version|Thread/Create Count|Open File Number|Open Count of PreparedStatement|The Open Count of SQL|Warmup time(ms)|Average Time(ms)
-------|-------------------|----------------|-------------------------------|---------------------|---------------|---------------- 
99d5e0e3db6567853292ce00ec0b44dab79f7fec|111|132|254|389|50502|22910.6
This pull|111|132|294|403|49347|22973.6

There are prepared statement & SQL increase, but the final result is only 63ms slower with the pull. I think it's acceptable.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9581

**Pull request closed without merging**
