### PR TITLE
LPS-111929

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by dantewang** [comment]
It seems a wrong commit is removed from the pull. The cause is "Save one service call" (https://github.com/tinatian/liferay-portal/pull/1810/commits/ab3e547bc57693c817a8c9d3a1f9348b7ac61734).

**Comment by dantewang** [comment]
@tinatian I feel this seems like a bug in portal, revealed by your change.

There are 3 places which may cause "**ACCESS_IN_CONTROL_PANEL**" to be added to a portlet by calling `_checkPortletActions(Portlet, Set<String>)` in `ResourceActionsImpl`: 1) `_readPortletResource(String, Element)`, 2) `_getPortletResourceActions(String, Portlet)` and 3) `getPortletResourceActions(Portlet)`.

Without your change, these logic during OSGi portlet deployment looks like below:

**First**, 1) is called by `PortletTracker`, but **addition of the action is skipped**, because the `portlet` object is null at that stage.

**Second**, 2) is called in this chain: `PortletTracker.deployPortlet()` -> `PortletLocalServiceImpl.deployRemotePortlet()` -> `ResourceActionsImpl.check()`. 2) will only run `_checkPortletActions()` when the bag returns an empty list of portlet actions, **so here it won't do the addition, either**.

Here the `check()` method gets the portlet actions from `_getPortletResourceActions()` method, and then gives the portlet actions to `ResourceActionLocalServiceUtil`.

**Third**, `ResourcePermissionLocalServiceImpl` also calls 2) through `getPortletResourceActions(String)`, and the result is same with above.

So, on master, the portlet action `ACCESS_IN_CONTROL_PANEL` is never added to a portlet by our checking logic, even if its [`portlet.getControlPanelEntryCategory() != null`](https://github.com/liferay/liferay-portal/blob/b3173da81b62430f7150b695d5e944b224279580/portal-impl/src/com/liferay/portal/security/permission/ResourceActionsImpl.java#L665) is true (which means this portlet SHOULD have this action).

[Your change](https://github.com/tinatian/liferay-portal/pull/1810/commits/ab3e547bc57693c817a8c9d3a1f9348b7ac61734#diff-51cd5f9fbcc6ed07a7738ff9d85e9fefR1211) replaced invocation of `ResourceActionsImpl.getPortletResourceActions(String)` with 3) `getPortletResourceActions(Portlet)`. This method calls `_checkPortletActions()` without any condition. This change only affects the "**Third**" step above. As a result, the portlet actions list `ResourcePermissionLocalServiceImpl` obtains has one more action than what `ResourceActionLocalServiceUtil` knows for the portlet. That's way we see https://testray.liferay.com/reports/production/logs/test-1-2/1587785655910/test-portal-acceptance-pullrequest%28master%29/6181/functional-smoke-jboss71-mysql57-jdk8/0/0/liferay-log.txt.gz.

I think this is a bug of portal revealed by your pull because the portlets that have this error should have this action. I also see a lot of portlets explicitly declare this action in their xml files.

**Pull request closed without merging**
