### PR TITLE
LRQA-66277 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-66277

### CODE REVIEW

**Comment by kyle-miho** [comment]
ci:test:sf

**Comment by kyle-miho** [comment]
ci:test:relevant

**Comment by kyle-miho** [comment]
Tested locally, this is used to test various properties available for scheduler, let me know if there are any problems

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10343

**Pull request closed without merging**
