### PR TITLE
LPS-135983 Make sure one portlet can only be associated to one root m…

### PR DESCRIPTION
**Pull request by tinatian**
…odel resource

### CODE REVIEW

**Comment by tinatian** [comment]
Hi @AliciaGarciaGarcia,
We are going to add restriction that one portlet can only be associated with one root model resource, and the permission support you added for translation portlet in LPS-114310 breaks it. Could you please take a look at it?

Step to reproduce it:
1. Build portal on this pull and start it
2. You will see `More than one root model resources are defined for com_liferay_translation_web_internal_portlet_TranslationPortlet: com.liferay.translation.ar_SA, com.liferay.translation.bg_BG
`

Thanks.
Tina.

**Comment by jpince** [comment]
@tinatian I would suggest extending the exception to include something like `", see LPS-135983"`, so developers who run into this error can go straight to the JIRA ticket to understand the issue, rather than having to trace the exception.

Also, can you please review what I wrote in the description of https://issues.liferay.com/browse/LPS-135983 for accuracy?

**Comment by adolfopa** [comment]
@tinatian This change will break translations in a pretty fundamental way; given the amount of time we have prior to the release I don't think we'll be able to make it.

Would it be possible to make the error a warning for the moment? Also, we're going to need some support from you guys in order to find a solution for this.

**Comment by adolfopa** [comment]
I've sent a tentative fix in https://github.com/liferay-lima/liferay-portal/pull/2079 (last commit).

**Comment by jpince** [comment]
@adolfopa please bring up the topic with Brian tomorrow. He asked Tina to enforce the rule, and I think he would be the best one to ask about priority.

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@tinatian Adolfo's change was merged, so you should be able to proceed with this change.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10181

**Pull request closed without merging**
