### PR TITLE
[SampleSQLBuilder] LPS-119985 part 1: Asset

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @dantewang @slnn :
This pull seems not completed to me.

For example, newAssetCategoryModels will generate the modules and store it in a local map, the goal is to make it only generate the modules, and then pass in it as a parameter to other methods which need it.

Please resend.

Thanks.
Tina.

**Comment by slnn** [comment]
OK, will resend.

**Comment by slnn** [comment]
Resend in https://github.com/dantewang/liferay-portal/pull/1768

**Pull request closed without merging**
