### PR TITLE
LPS-94560 expect certain logs in the test

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:backend

**Comment by dantewang** [comment]
ci:reopen

Liferay Continuous Integration <notifications@github.com> 于 2019年4月29日周一
18:28写道：

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7702

**Pull request closed without merging**
