### PR TITLE
[portal-test-integration] LPS-102243 Move test rules and related classes to portal-test | resend

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@dantewang @ChiZelin 
Please modify the comment of deprecate, make it deprecate as of 7.3.

Thanks.
Tina.

**Comment by tinatian** [comment]
Hi @dantewang, @ChiZelin 
Let's confirm with Hugo which version number we should use for deprecation.

Thanks.
Tina.

**Pull request closed without merging**
