### PR TITLE
LPS-82545 Avoiding hard coded path (asked by Brian)

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://github.com/brianchandotcom/liferay-portal/pull/60805\#issuecomment-400401253

This is the simplest way I can find. Our build process guarantees existence of SystemOut.log and WAS will keep the JAVA HOME part in the log even if it's set to rotation.

All other ways requires executing .bat or .sh and parsing the output.

### CODE REVIEW

**Comment by tinatian** [comment]
Hi @dantewang 
I think we can find the value in websphere/profile/liferay/config/cells/liferay-cell/nodes/liferay-node/variables.xml.
There is an entry with named JAVA_HOME which using the value of another entry named JAVA_LOCATION_1.8.64.

Could you please modify script and try if it would work?

Thanks
Tina.

**Comment by dantewang** [comment]
@tinatian 
A problem is, all the nodes are `<entries>` which have different attribute values. Neither Ant's built-in tasks, nor `<xmltask>` can resolve one `<entries>` node's `value` attribute value, which references to another node's `symbolicName` attribute value, into that node's `value` attribute value.

There is no direct way to parse this that I can find. It may need to use XLST or custom Ant task.

**Comment by dantewang** [comment]
@tinatian There's another problem, where the JAVA_HOME in variables.xml points to `$WAS_HOME/java_1.8_64` but the JAVA_HOME actually being used when starting the server is `$WAS_HOME/java_1.8_64/jre`.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/6402

**Pull request closed without merging**
