### PR TITLE
Lps 102736 1

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please help me verify if there is any other real failure except the semantic versioning one?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Integration test failure rate is very high
https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/295848/#showFailuresLink

I do not see these failures elsewhere.

**Comment by vicnate5** [comment]
Functional tests are fine.

**Comment by tinatian** [comment]
Thanks @vicnate5 ! I will take a look at it.

Tina

**Pull request closed without merging**
