### PR TITLE
LPS-73947 _memoryClusteredJobs should only be deleted after being demanded to master and no exception in execution thrown.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by tinatian** [comment]
@marianoalvarosaiz Please see my comment on the ticket.

For your code, if you really want to do this, I can only take the lazy deletion part of _memoryClusteredJobs.

But not "addMemoryClusteredJob(schedulerResponse);" in doMasterTokenReleased(), since it is wrong to do this, the data in trigger is inconsistent with master, and it will cause another issue later, we did this on purpose to fix another issue.

Tina.

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian,
 I don't totally understand this point: 
> But not "addMemoryClusteredJob(schedulerResponse);" in doMasterTokenReleased(), since it is wrong to do this, the data in trigger is inconsistent with master, and it will cause another issue later, we did this on purpose to fix another issue.

The _addMemoryClusteredJob(schedulerResponse);_ means adding the jobs that are currently scheduled on master (so they're supposed to valid at that moment). After that synchronization with master happens in _initMemoryClusteredJobs_ where two things can occur:

1. The call to master is sucessful so the jobs just added aren't important because they're deleted and replaced by master information.
2. Call to master fails, so data in trigger (if ever transitioned to master again) cannot be inconsistent because more or less the sequence must have been like this:
2.1. Node 1 gets started. Node 1 trigger information is the master one.
2.2 Node two gets started. Node 2 triggers get their information from node 1, so both nodes are synchronized.
2.3. Lost of visibility. Both nodes become master
2.4. One of both nodes releases token master having as memoryClusteredJobs the ones that they scheduled previously in Quartz (supposed to already be syncrhonized)
2.5. If slave node is promote to master LPS-66858 code will prevent to misfire triggers to be executed again.

**Comment by tinatian** [comment]
@marianoalvarosaiz 

Let me explain this with an example:
There are 3 nodes, node1, node2, node3. 
1. At some point, node1 and node2 can not see node3, and node3 can not see node1 and node2. This means node1 and node2 are in a sub-cluster, node3 in another sub-cluster
2. Node1 and node2 will have its own master, let's say it is node1.
3. Node3 is separated, so it is also master
4. Later at some point, node3 can see other nodes, and other nodes can see node3, then a merge will happen, and our master/slave node transfer will happen
5. Let's say the new master node is node1, and node3 will do "master to slave", and it will try to initMemoryClusteredJobs from node1.
6. Bad thing happen again, node1 is out of connect, and node3 can not load memory clustered jobs.
7. Here a new master will be elected. It could be node3, if that's the case, you changes seems OK. But what if the new master is node2? How could you know if the trigger in node3 is consistent with node2? 
8. Suppose node2 is new master, and node3 is slave. With your code, at this point, node3 will have its own jobs info (which was once running on node3), and node2 is running with the old node1's jobs info. And they are not consistent.
9. Another point, node2 is out of connect, and node3 becomes new master. Things like what described in LPS-66858 may happen. 

The reason LPS-66858 works is it is based on all slave nodes have same copy of jobs running on master, especially the start date of the trigger using in master. That's why we need to make jobs consistent across cluster.

Like I said in the comment of the ticket, you are not fixing the problem, you are transferring it from one to another. If we can not fix the problem in root, it's better that we tell customer as soon as possible, so that customer can do something in response. At first sight, your changes make sense, but when you look into it, it is not. In fact, it is covering the problem (some jobs are running, some are missing), customer might not see things are wrong at beginning, but when there is something wrong happens in future, it is really hard to figure out why. So I would like to keep our code clean, and let people handle those rare cases.

Thanks.
Tina.

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian,
 ok, I see your point, but really what you're reporting in step 8 is another bug (that we could also fix as part of this LPS) in _ClusterMasterExecutorImpl.getMasterClusterNodeId_ code. The bug resides in the fact that we only synchronize jobs when there's a _COORDINATOR_ADDRESS_UPDATE_ event and node changes state (from slave to master or vice versa), but it should be synchronized (initMemoryClusteredJobs() called) when node remains slave, but coordinator changes.

In your example, with my solution (and adding sync "previous code") the steps would be like the follwing:
1-6. Same as yours. At this point node 3 is out of sync with nodes 1 and 2.
7. Node2 becomes elected as master. Then node3 should ask again for the scheduled jobs to node 2. If it goes OK now jobs are synchronized, if it fails they wouldn't, but is an understable situation (it would happen with any code) because synchronization couldn't happen.

To stress the fact that synchronization should happen in a slave even if it doesn't change to master, but master changes address, I'm going to use your example:

After step 3 there are two subclusters: [node1, node2] and [node3]. Instead of your step 4, what happens if node3 is elected as master? As code is now node1 changes  from master to slave and synchronizes code with node3 (so both nodes are expected to be synchronized), but node2 doesn't attempt to synchronize with node3 because it remains from not being master to not being master. At the end of the step we have node1 and node3 with "same information" and node2 synchronize with old node1 information (which is incorrect).

Regards.

**Comment by tinatian** [comment]
@marianoalvarosaiz 
Yes, I agree we should do sync when master node is changed no matter if there is a master-to-slave or slave-to-master. But this has nothing to do with your changes here(add current running code to _memoryClusterSchedulerJobs when do master-to-slave).
1. In [node1, node2] and [node3], if node3 is master, then node1 and node2 updated jobs from node3, no matter what you stored in node1 (the old master) is going to be updated.
2. In [node1, node2] and [node3], if node1 is master, then node3 and node2 updated jobs from node1, if node3 can not update data, and later node2 becomes master, then node3 will update data from node2, no matter what you store in node3 is going to be updated.

Your changes here are not helping at all.

What I want to stress is your local storage of current running jobs on master is a potential risk of non-consistent, we should never do that. This is just an example of 3 nodes, what would happen if we have more nodes than 3? There would be lots of different cases out there, we can not list all of them and also we can not handle all of them. This kind of robustness is not we can provide.

If you want to add the sync for slave node, it should not include in this ticket, it is another issue since doing that can not address your problem described in the ticket. Again, the issue you described in the ticket is not we should fix, at lease not now. Maybe we will do refactor and use another model (not master-slave model) later, but again, each model has its own pros and cons, there is no perfect one. 


Thanks.
Tina.

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian,
 I think the cases can be reduced to practically three: 

* If while nodes in subcluster no changes on jobs are done.
* If while nodes in subcluster non equivalent changes are done.
* If while nodes in subcluster equivalent changes are done.

In the following, objetive table, you can see the pros and cons of either solutions in different situations while lost of visibility happens, so that in a way alternatives can be rated. A value of 1 means that the solution does work, a value of zero is the opposite:


|               | Everything goes OK | No changes in Subcluster-Join Fails | Equivalent changes in Subclusters-Join fails  | Changes in Subcluster-Join fails |
| ------------- | ------------------ | ----------------------------------- | --------------------------------------------- | -------------------------------- |
| Current Code  | 1                   | 0                                  | 0                                             | 0                                |
| With this LPS | 1                   | 1                                  | 1                                             | 0                                |

* **Everything goes OK**: If after subclusters join initiMemoryClusterJobs doesn't fail both solutions work as expected because they synchronize old master with master jobs.
* **No changes in subcluster-Join Fails**: Situation where nodes are splitted in subclusters, but while this visibility is lost no changes in jobs are produced. If after that, when joining subclusters synchronization fails with current code the status is unacceptable because all jobs are lost in old master. With the proposed solution everything will work as expected.
* **Equivalent changes in subclusters-Join fails**: Some as before. Current code ends in an unnaceptable state which will require stopping at least one or maybe all nodes (depending when the problem is detected). With the proposed solution everything will work as expected.
* **Changes in Subcluster-Join fails**: With current code the final status is unacceptable. With LPS changes in the code if synchronization fails with old master nodes changes that were produced during the lost of visibility will be lost. Of course this is not the desired behaviour but is a defendable one. Is exactly the same behaviour that will happen if for example you schedule a task and the notifySlave fails. The state is inconsistent but as a result of the failing call(s), but what was synchronized before doesn't get lost. Anyway what is totally indefensible in front of a customer is that after a failure the node (and maybe the whole cluster) is unrecoverable (what happens with current code). 

Please, reconsider this because customer has rejected that we won't fix the code, and their position is totally understable. Not having nodes synchronized because of a network failure can be attributable to customer infrastructure, but loosening everything, even tasks that haven't been updated, hence not needed to synchronize, can be only attributable to Liferay code.

Thanks.

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian,
 did you have chance to consider last explanation?
Thanks a lot.

**Comment by tinatian** [comment]
@marianoalvarosaiz Sorry for late response, hopefully I can take a look at it tomorrow, there are some urgent stuff in hand today.
I have not take a look at your comment in details yet, but if you really want to fix this kind of issue because of pressure from customer, I need some time to figure out a new solution. Any deadline about this?

Tina.

**Comment by tinatian** [comment]
See https://github.com/marianoalvarosaiz/liferay-portal/pull/59

**Comment by tinatian** [comment]
See final pull on https://github.com/shuyangzhou/liferay-portal/pull/4752

**Pull request closed without merging**
