### PR TITLE
LPS-106517 git commit

### PR DESCRIPTION
**Pull request by alee8888**

### CODE REVIEW

**Comment by alee8888** [comment]
ci:test:license

**Comment by alee8888** [comment]
ci:test:license

**Comment by tinatian** [comment]
ci:test:license-cluster

**Comment by tinatian** [comment]
@vicnate5 Is this good to move forward?

Tina

**Comment by vicnate5** [comment]
@tinatian Looks good.

Screenshot of the new license activation page
PostLPS106517

**Pull request closed without merging**
