### PR TITLE
[SampleSQLBuilder] LPS-74148 Part 2, DL, Journal | resend

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Force pushed just for SF.

**Comment by slnn** [comment]
Rebase and resend this part in https://github.com/dantewang/liferay-portal/pull/1494

**Comment by dantewang** [comment]
See https://github.com/tinatian/liferay-portal/pull/1673

**Pull request closed without merging**
