### PR TITLE
Lps x finder cache 13

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@GinsonRen Please wait for ci result, and if no major issue, run a diff on this pull.

Thanks.
Tina.

**Comment by GinsonRen** [comment]
@tinatian Still can see the "Failures unique to this pull", not sure it is related to this pull. could you take a look at it?

**Comment by tinatian** [comment]
@GinsonRen This is not a major issue, most of the tests passed, please run the diff, I would like to see how bad it is.

Thanks.
Tina.

**Comment by tinatian** [comment]
@GinsonRen Never mind, I will send out a new pull and comment you.

Thanks.
Tina.

**Pull request closed without merging**
