### PR TITLE
Lps 88872 Remove unnecessary mocks in wiki-editor-configuration

### PR DESCRIPTION
**Pull request by lanceji92674957**
Hi Tina,

All tests modified in this pull have been tested locally.

Thanks.

Lance

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@Preston-Crary, please take this over!

Thanks!
Tina

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/7252

**Comment by Preston-Crary** [comment]
ci:close

**Pull request closed without merging**
