### PR TITLE
LRQA-45990 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Adds ci:test:unit and ci:test:relevant

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:unit

**Comment by vicnate5** [comment]
ci:test:integration

**Comment by vicnate5** [comment]
ci:test:integration

**Comment by tinatian** [comment]
FYI @lanceji92674957

**Comment by tinatian** [comment]
FYI @dantewang,
This is a temp solution to run unit test and integration test faster on CI, you can use it when you only touch the test classes.

We are going to change the logic in ci:test:relevant so that it can save time for everyone, QA is working on that. Before that, you can just cherry pick this change and use these commands. 

Thanks.
Tina.

**Comment by dantewang** [comment]
@vicnate5 @tinatian Thanks!

**Comment by tinatian** [comment]
Hi guys @vicnate5 @dantewang @lanceji92674957,
The change in "ci:test:relevant" is live on Ci now (See https://issues.liferay.com/browse/LRQA-45992), we do not need this temp solution any more.

Thanks.
Tina.

**Comment by lanceji92674957** [comment]
Cool, @tinatian @vicnate5 Thank you!

**Comment by dantewang** [comment]
@vicnate5 @tinatian Thanks!

**Pull request closed without merging**
