### PR TITLE
LPS-125382 Upgrade groovy in portal-scripting-groovy

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@ChiZeLin Please double check https://issues.liferay.com/browse/LPS-112840 on Websphere for this pull. Please backport the change once it's merged. Thanks!

**Comment by ChiZelin** [comment]
@dantewang This pull works well on websphere. The issue of https://issues.liferay.com/browse/LPS-112840 does not appear.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9702

**Pull request closed without merging**
