### PR TITLE
[SampleSQLBuilder] LPS-74148 Part 2, DL, Journal

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang @slnn Please see https://github.com/slnn/liferay-portal/pull/466.

In your first two commits, to remove "_defaultDLFileEntryTypeModel" and related get method from DataFactory, you have to add a new parameter in macro method, and making ftl more complex than before. This is not worthy, cause we all know that ftl is harder to maintain than java code.

Removing default related attributes from DataFactory is to simplify the logic in init method, so that it would help us to decouple later. When you making a decision, please always think comparing to what we would get if it worthy to do this.

Tina

**Comment by slnn** [comment]
OK, got it.

**Pull request closed without merging**
