### PR TITLE
[portal-impl-integration] LPS-96692 CounterLocalServiceTest | resend

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:backend

**Comment by dantewang** [comment]
@tinatian 

1. Removed the test rule from AggregateTestRule's order list
2. After lookinig into properties in portal-test.properties as well as portal-test-ext.properties which is generated on CI, we decide to not migrate any of the property.

For 2, most of the properties are obviously irrelevant, but I'd like to explain for some of the properties:

portal-test.properties:

- `scheduler.enabled=false` is irrelevant because the sub-processes does not start module framework at all. We should not apply it to the main process either because it's a real portal process and may run many other Arquillian tests.

portal-test-ext.properties (see build-test.xml `<macrodef name="set-portal-impl-portal-test-ext-properties">`):

- `jdbc.default.*` and `jdbc.counter.*`: these properties were added to make it easier to detect database connection leaks (https://github.com/brianchandotcom/liferay-portal/pull/29292). The portal-ext.properties for Arquillian tests also have these properties and it will be read by sub-processes thanks to https://github.com/tinatian/liferay-portal/pull/1478/commits/6a3e700e128c7077a9bfc61362c124d28612ae0c.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8104

**Pull request closed without merging**
