### PR TITLE
LPS-123329

### PR DESCRIPTION
**Pull request by yuhai**
Hi @tinatian,

The pr is based on https://github.com/tinatian/liferay-portal/pull/2030#issuecomment-725750640 requirement. 

cc @dantewang

Thanks.

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9602

**Pull request closed without merging**
