### PR TITLE
Lps 93870 Remove deprecated methods

### PR DESCRIPTION
**Pull request by lanceji92674957**
portal.kernel.settings
portal.kernel.trash
portal.kernel.upload
portal.kernel.workflow

### CODE REVIEW

**Comment by lanceji92674957** [comment]
ci:test:relevant

**Comment by lanceji92674957** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@lanceji92674957 
The test failure is caused by some modules clearly set up the dependency package version range, I fixed similar issue here: https://github.com/shuyangzhou/liferay-portal/pull/7615/commits/2b5f4469b286968c520fe38ce7c232676ee48fc8

**Comment by lanceji92674957** [comment]
@tinatian thanks Tina, I applied a fix and resent at https://github.com/tinatian/liferay-portal/pull/1335, 
gonna wait for the ci result

**Pull request closed without merging**
