### PR TITLE
LPS-143628

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina @tinatian 
this pull is built on top of #2467 LPS-143420
removing CurrentConnectionUtil, EditorConfigurationFactoryUtil, and GhostscriptUtil
Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by tinatian** [comment]
@julschong I will wait for the first pull merged then review the following, you still can keep sending me pulls based on your earlier pulls.

Tina

**Comment by julschong** [comment]
Hi Tina, this will need to be sent again. I will close and resend.

**Pull request closed without merging**
