### PR TITLE
[Bug fix] LPS-132380 Register dummy service for SchedulerEngine and TriggerFactory when scheduler is disabled

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian Dummy service for `TriggerFactory` is enough to resolve all the unsatisfied references, but `SchedulerEngine` can also be referenced by others if they want. So I added both.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10022

**Pull request closed without merging**
