### PR TITLE
[Bug fix] LPS-94771 Fix wrong declaring class

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
ci:reopen

Liferay Continuous Integration <notifications@github.com> 于 2019年4月26日周五
18:17写道：

**Comment by tinatian** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/7693

**Pull request closed without merging**
