### PR TITLE
LPS-82603

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-82603

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @holatuwol ,
Just an update that I may not have time to review it this week, hopefully I can do it next week.

Thanks.
Tina.

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
@tinatian: That's fine! I know things are busy with the release coming up.

**Pull request closed without merging**
