### PR TITLE
[Bug fix] LPS-127348 DB2, question mark

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian After discussion with Hai we decide to split the previous pull https://github.com/tinatian/liferay-portal/pull/2334 to 2 tickets. This ticket will focus on DB2. The Hypersonic change in last pull was just to move the compatibility logic to a more common place, and we've created another ticket for it.

### CODE REVIEW

**Comment by dantewang** [comment]
@yuhai I rearranged the commits.

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@yuhai Is there any official doc about this change?

**Comment by yuhai** [comment]
@tinatian, I referred to the [doc](https://www.ibm.com/docs/en/db2/11.1?topic=design-parameters-markers).

> Table 1. Restrictions on parameter marker usage
> 
> Expression: Alone in a select list | Error
> Expression: Both operands of an arithmetic operator | Error
> Predicate: Left-hand side operand of an IN predicate | Error
> Predicate: Both operands of a relational operator | Error
> Function: Operand of an aggregation function | Error

**Comment by tinatian** [comment]
@dantewang @yuhai Please see my changes at https://github.com/shuyangzhou/liferay-portal/pull/10215.

@yuhai Please add comment to the ticket about the root cause of this issue and the doc link you depend on.

Thanks.
Tina

**Pull request closed without merging**
