### PR TITLE
[deprecation] LPS-103614 fix sem ver

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by tinatian** [comment]
Hi @dantewang,
Please send to Brian directly, and cc me and @shuyangzhou .

For pulls **exactly** like this one in the future, please also send it directly to Brian, and cc us.

The goal is to simplify review process, but I can not list all the cases you can send directly now, so let's do it one by one. Please send pulls to me as before and I will comment on the pulls if I think they are simple enough and you can send out directly.

Thanks.
Tina.

**Comment by dantewang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/80218

**Pull request closed without merging**
