### PR TITLE
LPS-120376 Support to load sample sql to DB on portal side

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Moved logic from benchmark project to portal to create SQL that can be inserted into DB.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@slnn Please remove the logic to insert the sql to database, just build a sql which is ready for inserting is enough, please resend.

cc @dantewang 

Thanks.

**Comment by slnn** [comment]
OK, please see https://github.com/dantewang/liferay-portal/pull/1756

**Pull request closed without merging**
