### PR TITLE
LPS-120376 Sample SQL for others | 11-12

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang @slnn 
I do not like you remove the support of  "benchmarks.${user.name}.properties", as this is a traditional way to override properties across portal.  To me, you new way of reading "-Dsample.sql.properties.file" is only for benchmark project.

I would like to highlight one more time, forget benchmark project usages when you made the change, please always do:
1) make any reasonable change to liferay repo benchmarks
2) apply the changes to benchmark project


Please fix and resend.

Tina.

**Comment by dantewang** [comment]
@tinatian This change was made due to the way SampleSQLBuilder reads the
properties, which is, reading a properties file directly.

The overriding just loads properties into the Ant context, and it allows
people to define their properties with multiple files, each overriding some
of the properties. This is not compatible with SampleSQLBuilder.

To keep the overriding support, we'll either

- make SampleSQLBuilder support reading from multiple properties files
- generate a temp properties file from Ant context and feed it to
SampleSQLBuilder.

Tina Tian <notifications@github.com> 于 2020年11月13日周五 02:37写道：

**Comment by tinatian** [comment]
You can go with either way, I am OK with both.

**Comment by slnn** [comment]
Will resend later.

Lily

**Comment by slnn** [comment]
Please see https://github.com/dantewang/liferay-portal/pull/1802

**Pull request closed without merging**
