### PR TITLE
Lps 106592 2

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:search-es7

**Comment by joshchong** [comment]
ci:test:search-solr

**Comment by joshchong** [comment]
ci:stop

**Comment by joshchong** [comment]
ci:stop

**Comment by joshchong** [comment]
ci:stop

**Comment by joshchong** [comment]
ci:test:search

**Comment by joshchong** [comment]
ci:test:search-es7

**Comment by joshchong** [comment]
ci:test:search-solr

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8878

**Pull request closed without merging**
