### PR TITLE
[portal-impl-integration] LPS-98626 Move Subscription test cases from portal-test-integration to module

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian After this there will be no class in portal-test-integration depending on LayoutTestUtil. Some variables are not inlined since order matters in those cases.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8051

**Pull request closed without merging**
