### PR TITLE
LPS-71619

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by hhuijser** [comment]
@tinatian just checking if this one is somewhere on your radar...

**Comment by tinatian** [comment]
Sorry @hhuijser, have been busy with some other stuff, will work on this next week.

**Comment by hhuijser** [comment]
no problem, thanks @tinatian

**Comment by tinatian** [comment]
@hhuijser I have a question about your change: 
is it going to check only the files which contains "<portlet:defineObjects />" ?

If that's the case, it might be wrong, since most time we define "<portlet:defineObjects />" in init.jsp or other header jsp, and then use the variables in another jsp.

I think the logic for checking should be in a recursion:
1) For a file, if it contains "<portlet:defineObjects />", check if it uses any variables defined by it, if false, go to 2)
2) Find all the files which includes the first file, and check everyone for the variables, if false, go to 2) until all the files are checked or find any variable


Tina.

**Comment by hhuijser** [comment]
@tinatian 

It does do the recursive searching as you describe.

**Comment by tinatian** [comment]
@hhuijser  But according to your logic in this method _removeUnusedPortletDefineObjects, you will return if you did not find "<portlet:defineObjects />". It won't work in the following case:
1) I have a init.jsp, which contains "<portlet:defineObjects />", but not contains any variables
2) I have a test.jsp which includes init.jsp and use the variables defined by PortletDefineObjects

According to your logic, you will remove the "<portlet:defineObjects />" in init.jsp, but in fact we should keep it.

**Pull request closed without merging**
