### PR TITLE
Free marker async

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
FYI @shuyangzhou

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the results?

Tina

**Comment by tinatian** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@tinatian Issues are similar to the last PR.

1. Wildfly/JBoss NPE accessing localhost:8080 in browser
https://testray.liferay.com/reports/production/logs/test-1-23/1607153489219/test-portal-acceptance-pullrequest(master)/7066/functional-smoke-wildfly140-mariadb102-jdk8/0/0/jenkins-console.txt.gz
2. Dropdowns not loading in Widgets on a page (will confirm steps manually once I have the bundle)
3. Freekmarker unit tests failures
https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/428761/

**Comment by vicnate5** [comment]
I can not reproduce Issue 2 locally, even with the Poshi test. Will need to check new CI results.

**Comment by tinatian** [comment]
@vicnate5 Can you reproduce #1 Wildfly/JBoss NPE accessing localhost:8080 in browser locally?

I tested wildfly locally and everything is fine.

Tina

**Comment by vicnate5** [comment]
@tinatian I cannot reproduce 1 locally either. I will just analyze the new results when they come in.

**Comment by tinatian** [comment]
@vicnate5 Could you please check the new results?

Tina

**Comment by vicnate5** [comment]
@tinatian New results show the same problems on CI, but I am unable to reproduce locally yet. Will keep looking.

**Comment by vicnate5** [comment]
@tinatian Reproduced the Wildfly problem locally, requires the configuration set for CI https://github.com/tinatian/liferay-portal/pull/2057/commits/cfd29c1a8e991c08eec71e6bfafc183dff82ff81. I can reproduce with this config file. I cannot reproduce without this config.

**Comment by vicnate5** [comment]
Steps to Reproduce widget dropdown issue locally
1. Add file osgi/configs/com.liferay.portal.template.freemarker.configuration.FreeMarkerEngineConfiguration.config `asyncRenderTimeout=L"7200000"`
1. Start portal
1. Add a new "**Widget** page" (unable to reproduce with default page type)
1. Navigate to new page
1. Add a Blogs widget to the page
1. Click "New Entry" and publish a new blog entry
1. Attempt to click blog options dropdown (3 dots)
1. If dropdown shows, click blog title to view blog, and then go back. Dropdown will no longer open.

**Comment by tinatian** [comment]
ci:help

**Pull request closed without merging**
