### PR TITLE
LPS-134986 Facet Permission Flattening

### PR DESCRIPTION
**Pull request by joshuacords**
https://issues.liferay.com/browse/LPS-134986

Hello Tina,
Here's the current progress I have on LPS-134986. I want to get your input early and often on changes as it takes me some time to make refactorings and I want to make sure I'm going in the correct direction. What I want to go over is the structure of the code and what needs to change before submitting it for final review.

To debug through this code, what you want to do is create a Web Content Folder and a Web Content Article inside that folder. Set a breakpoint at SearchPermissionFieldsFactory ln 64. This should return the roleIdSets that the search team with indexing under other tickets. After this, try changing the permissions of the Web Content Article.

Here's a very basic outline of the code structure. Each asset type will implement their own permission contributors under their SearchPermissionDefinition. (This copies the same structure used by DynamicInheritancePermissionLogic already in the portal but with a different goal. DynamicInheritancePermissionLogic would only return a boolean, but RoleSetContributors will return a complete flattening of the role combinations allowed to view the asset.) When an asset is being indexed, it will call SearchPermissionFieldsFactory.createSearchPermissionFields() which will find the asset contributors associated with the asset and apply them. I have yet to implement any Contributors except DynamicInheritanceRoleSetContributor. 

DynamicInheritanceRoleSetContributor.apply needs to calculate 2 sets of roleIds, one for Access permissions, and one for View permissions. It does this by recursively taking its current set of roleIds (contained and controlled by dynamicInheritanceRoleSetContributorContext) and combining it with the current level's parent's roleIds.

Here's an example what it should return for just view roles:
A JournalArticle permissioned for Role1 and Role2 is inside a folder permissioned for Role1 and Role3.
(Role1 = 11111, Role2 22222, Role3 33333)
Then the desired output for indexing would be [ [11111], [22222, 33333] ] which describe that either the user needs to be Role1 OR both Role2 AND Role3.

After the DynamicInheritanceRoleSetContributorContext and been taken through the entire parent chain, it's final set of role ids is assigned to the RoleSetContributorContext to be combined with other (less complicated) contributors, such as Workflow.

### CODE REVIEW

**Comment by joshuacords** [comment]
Hello @tinatian,

Here's the Epic which all this work falls under: [LPS-134878](https://issues.liferay.com/browse/LPS-134878).
Here's this individual ticket for the work on this pull: [LPS-134986](https://issues.liferay.com/browse/LPS-134986)
Here's the spike where I tested the indexing of the solution against the search engine: [LPS-134867](https://issues.liferay.com/browse/LPS-134867)

My goal for this review is:
1. Verification of the solution's direction 
2. Rough structures/apis review

Also, I have a list of tests I'm manually testing through JournalFolders and JournalArticles. I can give you an export of them with and explanation so you can debug through the logic. (Once I we get through the goals of this review I want to get automatic tests setup.)

Let me know if you have any questions, thank you.

**Comment by lipusz** [comment]
>Then the desired output for indexing would be [ [11111], [22222, 33333] ] which describe that either the user needs to be Role1 OR both Role2 AND Role3.

I believe the correct desired output is just `11111, 33333` as Role 2 (22222) does not have VIEW permission on the parent folder so there is no point in indexing its ID in the Document of the JournalArticle entry. :thinking:

**Comment by lipusz** [comment]
:bulb: So to me the problem comes down to the following desired behavior: when indexing the permissions of entities supporting dynamic inheritance (has a parent), the parent object should be considered/used to produce the `roleId` array, not the child entity.

**Comment by lipusz** [comment]
I might be wrong, but @joshuacords you may want to explore the idea of
1. Introduce a new DocumentContributor which adds the `classPK` of the top parent object into the documents (or just extend the contributors/indexers of the affected types directly with the logic) using a standard field name
2. In `SearchPermissionCheckerImpl._addPermissionFields(long, long, String, long, String, Document)`, when this field is present, use the parent's classPK (obtained from the field) to get the `roleIds`. 

Thoughts?

/cc @arboliveira fyi.

**Comment by joshuacords** [comment]
> I believe the correct desired output is just 11111, 33333 as Role 2 (22222) does not have VIEW permission on the parent folder so there is no point in indexing its ID in the Document of the JournalArticle entry. :thinking:

Role 3 doesn't have a view permission on the Journal Article itself, so just having Role 3 won't be enough to view the article. (And having just Role 2 won't be enough either, because the Journal Folder would deny the permission.) It has to be the combination of Role 2 AND Role 3. (You can test this permission behavior easily in the portal.)

**Comment by joshuacords** [comment]
> I might be wrong, but @joshuacords you may want to explore the idea of
> Introduce a new DocumentContributor which adds the classPK of the top parent object into the documents (or just extend the contributors/indexers of the affected types directly with the logic) using a standard field name
> In SearchPermissionCheckerImpl._addPermissionFields(long, long, String, long, String, Document), when this field is present, use the parent's classPK (obtained from the field) to get the roleIds.
> Thoughts?

The problem can't be simplified to just the parent's roleIds, it needs to consider each parent and the final child asset. Any of the parents or the child can add a role requirement to be able to view the child. 

Example: Folder 1 (Role 1 Permission) > Folder 2 (Role 1 Permission) > Article (Role 1 Permission) This only needs to index Role 1. BUT change it to: Folder 1 (Role 1 Permission) > Folder 2 (Role **2** Permission) > Article (Role 1 Permission) Now Role 1 is not enough, because Folder 2 has been scoped to necessitate having Role 2. And Role 2 isn't enough because both Folder 1 and the Article necessitate Role 1. Changing either Folder 1's View roles or the Article's View roles to Role 2 also demonstrates the same combination will be needed of having both Role 1 AND Role 2 to View the Article. 

@lipusz

**Comment by lipusz** [comment]
:thinking: 

image

**Comment by tinatian** [comment]
Close this pull as solution got changed.

Tina.

**Pull request closed without merging**
