### PR TITLE
[portal-impl-integration] LPS-93516 user related tests to user-test

### PR DESCRIPTION
**Pull request by yuhai**
Hi @tinatian, 

The PR is based on https://github.com/tinatian/liferay-portal/pull/1354. I just add the last commit to solve SF error, no other changes.

cc @dantewang

Thanks,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:backend

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@tinatian Upstream failure at the moment, also happening in Brian's pulls. // cc @yuhai

**Comment by yuhai** [comment]
ci:test:backend

**Comment by yuhai** [comment]
ci:test:backend

**Comment by yuhai** [comment]
ci:reopen

**Comment by yuhai** [comment]
The related test errors should be not related with the PR.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7713.

@dantewang @yuhai 
Please note that I did not merge this commit:https://github.com/tinatian/liferay-portal/pull/1355/commits/9f5d7c7074a657ecac85587991ebc836583cd354.

The reasons are:
1) test logic itself is simple and it is better we keep it in the test method itself to improve readability
2) after extracting into a separate method, it is hard to know if the user created in this test method got cleaned up. Generally when you create something, if it needs a destroy/close/remove, you should do it in the same method to show people that you clean up necessary resources rather than do cleaning in a method invoked in current method.
3) For test, the readability is more important than code duplication

Tina.

**Pull request closed without merging**
