### PR TITLE
[deprecation round2] LPS-104613 portal-impl part 1

### PR DESCRIPTION
**Pull request by dantewang**
https://issues.liferay.com/browse/LPS-104613

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Review by tinatian — COMMENTED** [review]
@dantewang Why we can remove modules/apps/document-library/document-library-service/src/main/java/com/liferay/document/library/internal/service/DLFileRankDLAppLocalServiceWrapper.java safely? Could you please add more comments about this removal?

Thanks.
Tina.

**Review by tinatian — COMMENTED** [review]
@dantewang @ChiZelin 
Could you please make it clear how you fix the usages? For example, using the replaced method to fix usages?

Thanks.
Tina.

**Comment by tinatian** [comment]
@dantewang @ChiZelin When you removing deprecations, let's remove the usages first then remove corresponding deprecated methods, this way I will be clear that the usages of deprecated methods.

Please resend.

Thanks.
Tina

**Pull request closed without merging**
