### PR TITLE
LPS-87064 deprecate JSP template in theme

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
`modules-integration-hypersonic20-jdk8` and `functional-tomcat90-mysql57-jdk8/10` should be random since it never happened in previous run: https://github.com/dantewang/liferay-portal/pull/906#issuecomment-444019563

`functional-tomcat90-mysql57-jdk8/32`, `source-format-jdk8`, `unit-jdk8` and other `modules-integration-*` & `integration-*` failures can also be seen in upstream.

**Comment by tinatian** [comment]
@dantewang 
Do we need to remove this line too? https://github.com/tinatian/liferay-portal/blob/37bd05bf13721b689f474535b6879860b98f60d9/portal-impl/src/com/liferay/portal/template/ThemeResourceParser.java#L37

In your second commit, some checking of extension kept, some removed, do you have any special reason to do this?

Thanks.
Tina.

**Comment by tinatian** [comment]
@dantewang Please resend

**Pull request closed without merging**
