### PR TITLE
[bug fix] LPS-92372 Force WebLogic to use portal's Apache XmlBeans

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://issues.liferay.com/browse/LPS-92372

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian I'm not sure which CI command can trigger related test, but I tries manually and there was no error shown when uploading docx. cc @vicnate5

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
Resent https://github.com/tinatian/liferay-portal/pull/1621

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
