### PR TITLE
LPS-114661 Rename UpgradeResourceActions to UpgradeResourceAction to match table name

### PR DESCRIPTION
**Pull request by dantewang**
Renamed class names as Brian requested.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9132

**Pull request closed without merging**
