### PR TITLE
LPS-73955

### PR DESCRIPTION
**Pull request by Ithildir**

### CODE REVIEW

**Comment by Ithildir** [comment]
ci:reopen

**Comment by Ithildir** [comment]
ci:retest

**Comment by pyoo47** [comment]
ci:stop (This test has frozen)

**Comment by Ithildir** [comment]
Hi @tinatian, you don't need this anymore?

**Comment by tinatian** [comment]
@Ithildir  Yes, sorry I closed it by mistake

**Comment by tinatian** [comment]
@Ithildir Is it working right now? or should I test it on CI again?

**Comment by Ithildir** [comment]
ci:retest Let's retest it!

**Comment by tinatian** [comment]
@Ithildir  Seems most tests failed, do you know if it is related to these changes?

**Comment by Ithildir** [comment]
I'll look into it 😕

**Comment by Ithildir** [comment]
ci:retest

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/4644

**Pull request closed without merging**
