### PR TITLE
[bug fix] LPS-105126 Sybase: Implicit conversion from datatype 'NUMERIC' to 'VARCHAR' is not allowed

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://issues.liferay.com/browse/LPS-105126; this is the last blocker of https://issues.liferay.com/browse/LPS-95571.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8587

**Pull request closed without merging**
