### PR TITLE
[Bug Fix] LPS-129842

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results?

Thanks.
Tina.

**Comment by vicnate5** [comment]
ci:test:lpkg

**Comment by vicnate5** [comment]
@tinatian I was just worried about the LPKG failures, but they are passing on re-run. This should be good.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9922

**Pull request closed without merging**
