### PR TITLE
Lps x cache field over clean

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@GinsonRen
Please run a diff on all test cases and startup.

Thanks.
Tina.

**Comment by GinsonRen** [comment]
@tinatian Here is the startup diff result, runtime diff is running I will update the result later.

Portal Version | Git Id | warmup(ms) | No.1 | No.2 | No.3 | No.4 | No.5 | Average Startup (ms) | Change
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | a5f3fe337 | 50039 | 26140 | 25962 | 25573 | 25886 | 25954 | 25903 | -
PR-2361 | - | 50640 | 25963 | 26017 | 25919 | 25793 | 25906 | 25919.6 | 0.06%

**Comment by GinsonRen** [comment]
@tinatian Here is the runtime diff result, there is an error on mb test case, I need more time to figure it out.

Login:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | a5f3fe337 | 30262 | 255 | 71.6 | -
PR-2361 | - | 30230 | 256 | 71.8 | -0.11%

WC:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | a5f3fe337 | 41924 | 307 | 100 | -
PR-2361 | - | 42100 | 293 | 96 | 0.42%

Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | a5f3fe337 | 12330 | 60.4 | 175 | -
PR-2361 | - | 12289 | 85.8 | 195 | -0.33%

DL:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | a5f3fe337 | 21120 | 262 | 422 | -
PR-2361 | - | 21506 | 270 | 420 | 1.83%

Wiki:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | a5f3fe337 | 11909 | 294 | 773 | -
PR-2361 | - | 11923 | 272 | 760 | 0.12%

AP:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | a5f3fe337 | 18345 | 400 | 182 | -
PR-2361 | - | 18152 | 379 | 179 | -1.05%

**Comment by GinsonRen** [comment]
@tinatian Here is the result of mb:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | a5f3fe337 | 15454 | 132 | 181 | -
PR-2361 | - | 15347 | 477 | 473 | -0.69%

**Pull request closed without merging**
