### PR TITLE
LPS-109015 Semantic Versioning.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by tinatian** [comment]
@dantewang Please take this over.

Thanks.
Tina

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@tinatian I'll get back to this pull after some discussion with @marianoalvarosaiz on Slack.

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
See https://github.com/tinatian/liferay-portal/pull/1723

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
