### PR TITLE
LPS-88710 Scheduler | 5

### PR DESCRIPTION
**Pull request by yuhai**
Hi @tinatian 

The PR is based on https://github.com/tinatian/liferay-portal/pull/1171. Rebase it with no logic changes.

cc @dantewang

Thanks,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang @yuhai 

Looking at `SchedulerEngineHelperImpl`, it is still complex and hard to understand, there is still room we can make it simple, that is remove two ways to register a schedule job, only keep one of them.

The first step, let's remove all the usages of `SchedulerEventMessageListenerWrapper` in modules, I found two usages:
modules/apps/portal-workflow/portal-workflow-kaleo-runtime-impl
modules/apps/export-import/export-import-service
The reason they need `SchedulerEventMessageListenerWrapper` is because they did not refactor their scheduler code to follow the current usage pattern. Let's do the refactor, make their listener a  `SchedulerEventMessageListener` directly like all other usages in modules.

The second step, add an implementation for `SchedulerEventMessageListener` in kernel to replace the usage of `SchedulerEventMessageListenerWrapper`.

The third step, make `SchedulerEventMessageListenerWrapper` wrap a `SchedulerEventMessageListener` rather than `MessageListener`. Remove the setter of `_schedulerEntry` and `_messageListener`. Add new setter of `SchedulerEventMessageListener`. Basically, in this wrapper, you only deal with `SchedulerEventMessageListener`. Then move `SchedulerEventMessageListenerWrapper` out of core into internal package of module.

Final, redo your change in this pull, this time you only need one service tracker.


Thanks.
Tina.

**Comment by tinatian** [comment]
@yuhai @dantewang 
Please send me pull for each step.

Thanks.
Tina.

**Pull request closed without merging**
