### PR TITLE
[TS] LPS-92726 - Upgrade jgroups.jar library from 3.6.4.Final to 3.6.16.Final version

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-92726

Hi @tinatian ,

The goal of this update is to include a bug fix in JGroups to resolve a slow cluster startup time.

For additional information, please see my comment on the ticket: [LPS-92726#comment-1750301](https://issues.liferay.com/browse/LPS-92726?focusedCommentId=1750301#comment-1750301)
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:clustering

**Comment by ericyanLr** [comment]
ci:test:clustering

**Comment by ericyanLr** [comment]
ci:test:clustering

**Comment by ericyanLr** [comment]
Hi @tinatian ,

For the latest test results, the failure appears to be for the test: `LocalFile.ClusteringConfigs#StartupJDBCPING`

- I asked Victor and he mentioned this is a known failure and is tracked here: [LPS-92491](https://issues.liferay.com/browse/LPS-92491)
- As for the semantic versioning issue, I don't think that is related to our fix.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7549

**Pull request closed without merging**
