### PR TITLE
LPS-102872 Create MessagingAdvice

### PR DESCRIPTION
**Pull request by Preston-Crary**
Based on https://github.com/shuyangzhou/liferay-portal/pull/8360 to avoid rebase conflicts with workflow-spring.xml

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:backend-hypersonic

**Comment by tinatian** [comment]
Hi @Preston-Crary,
Please see https://github.com/tinatian/liferay-portal/pull/1553, this is pretty much what I want to do.
Since we are going to remove the whole framework support of proxy bean, no need to do any clean up.

Here I am using same destination as other Async service, we can also modify Async annotation to support customized destination later. There may be other requirements coming from other use cases of proxy bean pattern, we can decided how to deal with it later.

I would like to keep this local first, and once we removed all the use cases, and know what the API would like, then start committing. I did not get enough time to finish this, if you got time and would like to work on it, please let me know.

Thanks.
Tina.

**Comment by Preston-Crary** [comment]
@tinatian, you want this to be part of Async annotation? Or a new annotation?

I think I did pretty much what you were asking for with 7e65c8711a45959f31baf061d5d65ca4b449e052...57fd1bb589ae9ef974339d46e3f0f3c2451310c1

The cleanup is just showing we only need the destinationName, that can be on a new annotation or the Async one. I think it's cleaner to make a new annotation so the async advice does not become too complex.

**Comment by tinatian** [comment]
@Preston-Crary 
maybe I did not make it clear enough, the goal is to remove the whole proxy bean pattern, which is going to stop all api related including the SchedulerEngineProxyBean, in your changes here, you’re still using it, so I created a pull just to highlight this goal.

we can decide if we are going to create a new annotation later, depending on how much change we need to make on current annotation, after we removing all the usages.

you can send a pull about your clean up part to Shuyang if you like, but after removing all the proxy bean pattern usages, the BaseProxyBean is going to be deprecated.

tina

**Comment by Preston-Crary** [comment]
In 57fd1bb589ae9ef974339d46e3f0f3c2451310c1 you can see I'm not using the BaseProxyBean and that class can be renamed without any problem.  The cleanup changes are not required, just helping me know that destination name is the only thing we need for all of them.  If you want I can resend after applying the same change to all of them and remove the BaseProxyBean class.

**Comment by tinatian** [comment]
my point is we do not need this SchedulerEngineProxyBean class at all. why we have it implements the SchedulerEngine and having all methods throwing unsupported exceptions?
we already have the real scheduler engine impl named QuartzSchedulerEngine, why not make it aop service directly?

Tina

**Comment by Preston-Crary** [comment]
Oh right, I should have removed that class.... for some reason I thought that one was the real impl.  I'll resend.

**Pull request closed without merging**
