### PR TITLE
[Bug fix] LPS-132399 Filter in MBeanRegistry is too strict, causing service published by core not being tracked

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This is found when doing Hibernate upgrade. The current HibernateStatisticsService is not tracked and registered as MBean due to this filter.
I didn't find any reason for this filter from the history and the current context. Asked in backend-dev channel and Ray said it could be an oversight.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang Please register HibernateStatisticsService as DynamicMBean to fix this issue. Any other service published by core has same issue?

Tina.

**Comment by dantewang** [comment]
@tinatian This is the only one I found. To publish it as `DynamicMBean` we need to let it implement `DynamicMBean`. This adds extra methods to the class that I'm not sure whether to implement or keep empty. All other services, in modules and published as `DynamicMBean`, are subclasses of `StandardMBean` which provides default implementation of `DynamicMBean`.

**Comment by dantewang** [comment]
See https://github.com/tinatian/liferay-portal/pull/2249

**Pull request closed without merging**
