### PR TITLE
Lps 133895

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@GinsonRen Please run a diff on startup.

Thanks.
Tina.

**Comment by GinsonRen** [comment]
@tinatian Here is the result:

Portal Version | Git Id | warmup(ms) | No.1 | No.2 | No.3 | No.4 | No.5 | Average Startup (ms) | Change
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
BaseLine | 109e8971 | 45618 | 22804 | 22980 | 22118 | 22550 | 23075 | 22705.4 | -
PR-2206 | - | 45024 | 22662 | 23059 | 22175 | 23008 | 22829 | 22746.6 | 0.18%

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results?

Thanks
Tina.

**Comment by vicnate5** [comment]
@koor4356 can you check the results here for regressions?

**Comment by koor4356** [comment]
@tinatian @vicnate5 Looks good, no unique failures. Thanks!

**Pull request closed without merging**
