### PR TITLE
LPS-130063 Upgrade Javassist

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Explanation about the last commit:

This commit aims to resolve the following error under Java 11:

```
Javassist Enhancement failed: com.liferay.document.library.content.model.DLContentDataBlobModel
java.lang.NoClassDefFoundError: org/hibernate/proxy/HibernateProxy
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.System$2.defineClass(System.java:2123)
	at java.base/java.lang.invoke.MethodHandles$Lookup.defineClass(MethodHandles.java:962)
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:295)
	at javassist.util.proxy.DefineClassHelper$Java11.defineClass(DefineClassHelper.java:48)
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:260)
	at javassist.util.proxy.FactoryHelper.toClass(FactoryHelper.java:154)
	at javassist.util.proxy.ProxyFactory.createClass3(ProxyFactory.java:640)
	at javassist.util.proxy.ProxyFactory.createClass2(ProxyFactory.java:624)
	at javassist.util.proxy.ProxyFactory.createClass1(ProxyFactory.java:560)
	at javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:481)
	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.getProxyFactory(JavassistLazyInitializer.java:162)
	at org.hibernate.proxy.pojo.javassist.JavassistProxyFactory.postInstantiate(JavassistProxyFactory.java:65)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.buildProxyFactory(PojoEntityTuplizer.java:185)
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.<init>(AbstractEntityTuplizer.java:167)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.<in...
```

Javassist is used by Hibernate to create lazy proxy of certain things. The proxy being created in the error message will be subclass of `DLContentDataBlobModel` and implement `HibernateProxy`.

Before upgrading, when defining the proxy class, Javassist uses the class loader of the interface `HibernateProxy` to define the class. In Liferay, this class loader will be a `PreloadClassLoader` and explicitly knows the needed classes.

In the latest version of Javassist, it has logic to avoid warnings/errors of invoking protected methods in class loader by using `MethodHandles` (See `DefineClassHelper$Java11`). However, with other Java 11 related logic, the class loader used to define the proxy becomes the class loader of the "neighbor" class of the proxy class (a class in the same package of the proxy class, here it's `DLContentDataBlobModel`). This class loader is dl-api module's class loader and doesn't import classes from `javassist.util.proxy` and `org.hibernate.proxy`. As a result, the `NoClassDefFoundError` is thrown.

Since Javassist is called from Hibernate code and we're about to upgrade Hibernate, and any module may encounter this, I added the packages to the bootdelegation so that they are visible to all module class loaders.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
This pull + jodd relevant run passed at https://github.com/dantewang/liferay-portal/pull/1965#issuecomment-820909014

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9953

**Pull request closed without merging**
