### PR TITLE
[ResourceAction] LPS-122059 Move portlet resource name processing to WAB processor | 2

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang This pull is not completed, let's have a talk about this when you got up.

**Comment by tinatian** [comment]
close, please resend

**Pull request closed without merging**
