### PR TITLE
LPS-84182 Apply Petra-String StringBundler to method argument and return value part1

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please help me scan the test result?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Looks good.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8875

**Pull request closed without merging**
