### PR TITLE
LRQA-53786 Cache Config integration test

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
https://issues.liferay.com/browse/LRQA-53786

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@kyle-miho 
Please inline the test xmls (for example `module-multi-vm-updated.xml`), that is to generate the content in the `PortalCacheExtenderTest` instead of including separate files.

Please resend.

Thanks.
Tina.

**Pull request closed without merging**
