### PR TITLE
[TS] LPS-111332

### PR DESCRIPTION
**Pull request by crodriguezy**
/cc @dacousalr

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@tinatian See discussion on https://issues.liferay.com/browse/LPS-111332. I tested this manually at head and on this PR. The new behavior makes sense. The user is re-directed to the new site's default URL instead of attempting to append the "guest" site's language (e.g. en). The user is still blocked from manually accessing the new site's URL with `/en/` added - The `locale.use.default.if.not.available=false` behavior is still working.

I do not like that navigating back to the "guest" site changes the locale to `fr` on that site too, but this is a different problem and also reproducible at head.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/tinatian/liferay-portal/pull/1805

**Pull request closed without merging**
