### PR TITLE
LPS-88685 --add-opens and SurvivorRatio

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian 
I made JDK version specific configs for these GC properties, but after a second thought in this pull I only changed the values of `-XX:SurvivorRatio` in `junit.java.integration.gc` and `junit.java.unit.gc` directly.

We have 2 arguments related to survivor zone. From my understanding:

- `-XX:TargetSurvivorRatio=0` makes no object go into survivor zone
- `-XX:SurvivorRatio=65536` makes the actual space taken by survivor zone as small as possible as a large value is assigned

So `-XX:SurvivorRatio` is mainly to avoid the waste of space. **With our heap settings, `65536` makes the survivor zone around 1~2KB, while my changed values make it about 32KB**. I think it's still acceptable, and easier to maintain.

By the way, the limit is not fixed and is dependent on GC methods. For 512M heap, for `ParallelOldGC` the limit is 1024, while for `CMS`, the limit would be `512`.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @dantewang,
I prefer a separate property for java 11, it is possible that we would like to set some special configs for 11 which can not apply to earlier version of jdk, making it a separate property will make things clear and easy to maintain. Also, we did same thing for a test property : test.batch.app.server.tomcat.setenv.gc.new[1.11].



Please resend.

Thanks.
Tina.

**Comment by dantewang** [comment]
see https://github.com/tinatian/liferay-portal/pull/1150

**Pull request closed without merging**
