### PR TITLE
TCK3 LPS-74658

### PR DESCRIPTION
**Pull request by dantewang**
This fixes 1 test failure.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:reopen

**Comment by tinatian** [comment]
@dantewang any portlet spec reference about this change?

**Comment by dantewang** [comment]
@tinatian See
https://portals.apache.org/pluto/portlet-3.0-apidocs/javax/portlet/EventResponse.html#setRenderParameters(javax.portlet.EventRequest)
and
https://portals.apache.org/pluto/portlet-3.0-apidocs/javax/portlet/StateAwareResponse.html#setRenderParameters(java.util.Map)

**Comment by tinatian** [comment]
close, hold off for now

**Pull request closed without merging**
