### PR TITLE
Lps 110686

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/mtambara/liferay-portal/pull/972.
I added test logic for updating a system property, but it is failed, is this the expected behavior or not?

`com.liferay.portal.file.install.deploy.test.FileInstallDeployTest > testConfigurationSystem FAILED
    org.junit.ComparisonFailure: expected:<testValue[2]> but was:<testValue[1]>
    	at org.junit.Assert.assertEquals(Assert.java:115)
    	at org.junit.Assert.assertEquals(Assert.java:144)
    	at com.liferay.portal.file.install.deploy.test.FileInstallDeployTest.testConfigurationSystem(FileInstallDeployTest.java:166)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$2.evaluate(TestExecutorRunnable.java:234)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:143)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:181)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
    	at java.lang.Thread.run(Thread.java:748)
`

Tina

**Comment by mtambara** [comment]
I believe this is correct, it seems like the system property substitution happens only when the configuration is installed, so it can't dynamically update if the system properties are updated.

**Comment by tinatian** [comment]
@mtambara 
I think this should be a bug, and we need to fix it. The current behavior does not make sense to me.

If you set a property by referencing a system property, it should always reflect the current value of the system property.
If you only allow people to use it to load for the first time, then when people open the config file after the first load, it should show the value of the system property instead of a reference to it.

What do you think?

Tina.

**Comment by mtambara** [comment]
@tinatian I don't think I would call it a bug, but I do agree that the behavior should change to update the configuration value with whatever the current system property is.

Would it be alright to leave it for now and change the behavior when I start making functional changes to fileinstall? Right now I just want to have the test assert current behavior so I know nothing's breaking as I pull the code in. Patching this in now would be a pretty big change and it will probably just need to change again in the near future

**Comment by tinatian** [comment]
@mtambara Sure, it is fine, I will move it forward. Thanks!

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8988

**Pull request closed without merging**
