### PR TITLE
Lps 115420 8

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@GinsonRen Please run a diff on this pull.

Thanks.
Tina.

**Comment by GinsonRen** [comment]
Hi @tinatian ,  I ran DL and wiki twice, still can see regression on them, here is the result.
Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 438ede3 | 44,492 | 283 | 82.8 | -
PR-1864 | - | 44327 | 261 | 77.9 | -0.37%

WC:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 438ede3 | 55,250 | 496 | 150 | -
PR-1864 | - | 55169 | 494 | 149 | -0.15%

MB: 
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 438ede3 | 16782 | 27.5 | 75.1 | -
PR-1864 | - | 16725 | 26.7 | 75.8 | -0.34%

Blog:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 438ede3 | 14,655 | 843 | 595 | -
PR-1864 | - | 14371 | 1080 | 663 | -1.94%

DL:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 438ede3 | 25,318 | 241 | 335 | -
PR-1864 | - | 24542 | 278 | 362 | -3.07%
PR-1864 | - | 24701 | 228 | 326 | -2.44%

Wiki:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 438ede3 | 15322 | 237 | 453 | -
PR-1864 | - | 14818 | 288 | 509 | -3.29%
PR-1864 | - | 14782 | 270 | 492 | -3.52%

AP:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 438ede3 | 25,289 | 426 | 178 | -
PR-1864 | - | 24912 | 418 | 177 | -1.49%

**Comment by tinatian** [comment]
@GinsonRen Could you please gather the profiles on DL with and without my changes?

Thanks.
Tina

**Comment by GinsonRen** [comment]
@tinatian I uploaded the profiles to google driver, please check your email. Thanks.

/cc @dantewang @slnn

**Pull request closed without merging**
