### PR TITLE
[TS] LPS-73210 Wait until there is some factory to parse configurations

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-73210

Hi Tina,

I have updated the LPS with notes about how to test the solution as we didn't find the way to test it properly on branches without LPKGs.

We are also not sure why this was working before a certain GA/fix pack release. Maybe we changed how bundles and components are loaded and activated and the order has changed (before FP30, the `test-1.0.0.jar` **bundle was started after all bundles from our suite LPKGs are already started** according to @csababotos's investigation) but we were unable to locate an exact change/commit and Carlos' fix is working well, we also provided it in an SDH to the client who reported this bug.

/cc @csierra, @csababotos

### CODE REVIEW

**Comment by lipusz** [comment]
ci:reopen

**Comment by lipusz** [comment]
ci:retest

**Comment by lipusz** [comment]
ci:retest

**Comment by tinatian** [comment]
Hi @lipusz ,

After taking a quick look at this issue, I am not sure if this is the root reason of this issue, just looking at the code of ConfiguratorExtender, I am wondering why we made this a dynamic dependency if a factory is required at the beginning? And I found there is only one implementation for each factory here, why we made it ReferencePolicyOption.GREEDY?

I think @csierra knows better than me about these questions. If we did this because we want to provide an "extension" for clients or future usages. I suggest we do that only when we really need it. Like what I discussed with @csierra here: https://github.com/csierra/liferay-portal/pull/276#issuecomment-342934045

I am on maternity leave right now, if you have more findings or changes about this issue, you can send pull to @shuyangzhou.

Thanks.
Tina.

**Comment by lipusz** [comment]
Hi Tina, @tinatian

First of all, congratulations to your happy **bundle**. I wish all the good things to you and your family! Can we know his/her `Bundle Name`? ;-)

Secondly, thank you for the thoughts. We will take them into consideration and talk to @csierra tomorrow to find out how to proceed with this issue.

Regards,
Tibor

**Comment by tinatian** [comment]
Thanks @lipusz! Her name is Amy, and we are all looking forward to see her. :)

**Comment by lipusz** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/5282

**Pull request closed without merging**
