### PR TITLE
TCK3 LPS-74563

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This is caused by LPS-74355; before LPS-74355 the IllegalArgumentException was thrown by PortalContextImpl.getProperty. Created a new ticket as LPS-74355 has a BPR associated to it.

### CODE REVIEW

**Comment by tinatian** [comment]
@dantewang Is this difference causing any problem? Or you just think it should be consistent with before.

Tina.

**Comment by dantewang** [comment]
@tinatian There are some tck tests requiring the IllegalArgumentException.

**Comment by tinatian** [comment]
@dantewang I see...
portlet3.0 api requires the IllegalArgumentException. Please see https://portals.apache.org/pluto/portlet-3.0-apidocs/javax/portlet/PortletRequest.html#getProperties(java.lang.String).

Could you please update the description of this ticket? We are fixing this because it is required by api, though it is not said in spec.

Thanks.
Tina.

**Comment by dantewang** [comment]
@tinatian Ticket description updated.

**Comment by tinatian** [comment]
See https://github.com/liferay/liferay-portal/pull/1894

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/4804

**Pull request closed without merging**
