### PR TITLE
LPS-145921

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian ,
I removed six unused properties "Dl.", which included "dl.folder.icon.check.count", "Dl.file.entry.open.in.ms.office.manual.check.in.required", "dl.file.entry.version.policy", "dl.file.entry.preview.document.depth", "dl.file.entry.thumbnail.video.frame.percentage", "dl.file.entry.preview.auto.create.on.upgrade".

- **Dl.folder.icon.check.count**: It was finally deleted on commit 67de38000200cdb8283fe6f5f5a66a9d9b8d5622, see LPS-68221
- **Dl.file.entry.open.in.ms.office.manual.check.in.required**: Its usage was deleted in commit 1baca9f2ef306194bdda40807d3c941729d89a0e, see LPS-49982.
- **Dl.file.entry.version.policy**: It was removed the usage in commit fa24f805f05b500e3721c852caf05f377bff1a28, see LPS-57406
- **Dl.file.entry.thumbnail.video.frame.percentage**: The usage was finally deleted in commit cbbef2d22277d9f326c39e79f914d680278d750f, see LPS-117661
- **Dl.file.entry.preview.document.depth**: Its usage was deleted based on commit 7108c446d697d90ed6072bbb315ae6bdfad9a3d9, see 27518.
- **Dl.file.entry.preview.auto.create.on.upgrade**: It was finally deleted in commit 5efe3478d41f068b0ff69ac2956c5a79bc5a183d, see LPS-76929.

Thanks for checking .
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 For this "LPS-145919 - Remove properties "scripting.jruby.compile.mode". It was…
… deleted in commit 6393d1b, see LPS-55505" It is not deleted by LPS-55505, just the usages changes from portal properties to configuration class (see modules/portal/portal-scripting-ruby/src/com/liferay/portal/scripting/ruby/configuration/RubyScriptingConfiguration.java), but the ruby engine had been removed by LPS-96677(80ab259b5bbb3024906b446858a7c5b6b59cc2ed), so you add this info to the commit message, it is enough to show people that removing it is safe.

Other changes look good to me, please put them into your list, I am going to close this pull.

Thanks.
Tina

**Pull request closed without merging**
