### PR TITLE
LPS-91921 MySQL timezone

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
Seems something wrong in [upstream](https://test-1-1.liferay.com//userContent/jobs/test-portal-acceptance-upstream%28master%29/builds/5783/jenkins-report.html) (the NPE) is causing lots of failures...

cc @vicnate5

**Comment by vicnate5** [comment]
@tinatian @dantewang Thanks for prioritizing this. This morning I spoke to @david-truong, our Support team member and other members of our team about this issue. We aren't comfortable with adding a workaround in the code right now. If we are going to handle "fixing" the jdbc URL on our side, it would be more consistent to add other default values in as well (e.g. `characterEncoding=UTF-8`)

Instead, we are going to ask users to configure both their app server and dbserver for GMT time zone to prevent this and other issues (https://issues.liferay.com/browse/LPS-91921). I am suggesting we change our default JDBC url in portal.properties to set the time zone to GMT by default. This also prevents us from needing to hardcode the mysql property value in this Data Source class. I think this is a solution that is more consistent with how we handle similar configuration requirements.

I sent an alternate pull here: https://github.com/tinatian/liferay-portal/pull/1268

CC @shuyangzhou

**Comment by tinatian** [comment]
Hi @dantewang, 
According to @vicnate5 comment, we changed solution, I will close this pull, please see https://github.com/shuyangzhou/liferay-portal/pull/7471

Thank.
Tina.

**Comment by dantewang** [comment]
@vicnate5 Thanks!

**Pull request closed without merging**
