### PR TITLE
LPS-122573 com.liferay.portlet.webdav-storage-token is not read by PortletTracker and should be removed from OSGi Portlets as the actual property is defined in WebDAVStorage OSGi services

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@tinatian Found this when reviewing LRDOCS-8420.

**Comment by tinatian** [comment]
See  https://github.com/shuyangzhou/liferay-portal/pull/9539

**Pull request closed without merging**
