### PR TITLE
LPS-111235 Upgrade jackson-databind

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by jesseyeh-liferay** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results? Is there any real failure caused by this pull?

Thanks
Tina.

**Comment by kyle-miho** [comment]
@tinatian they are all already failing upstream or are already pretty unstable to fail even with one retry (this pull should be safe)
@vicnate5 fyi the flaky error appears here as well
LIFERAY_ERROR: Data truncation: Data too long for column 'key_' at row 1

**Comment by vicnate5** [comment]
@tinatian based on the above comment I think this should be manually forwarded.

**Comment by tinatian** [comment]
FYI @shuyangzhou Forward to Brian as support is pushing on this.

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/88251

**Comment by tinatian** [comment]
Missing commits: https://github.com/brianchandotcom/liferay-portal/pull/88274.

**Pull request closed without merging**
