### PR TITLE
LPS-131967

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Made this change as Shuyang asked in the email thread about the deadlock seen in mb benchmark tests.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
@dantewang - Some of the builds were aborted in this pull request test. Please retest if results needed. Sorry for any inconvenience.

**Comment by tinatian** [comment]
@dantewang Please add a test to expose the issue and then fix it.

Thanks.
Tina

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10028

**Pull request closed without merging**
