### PR TITLE
[SampleSQLBuilder] LPS-109454 Fix compile according to LPS-107396

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/85530

**Comment by tinatian** [comment]
@dantewang @slnn Please send pull to Brian directly if you met things like this next time and cc me and shuyang.

Thanks
Tina.

**Pull request closed without merging**
