### PR TITLE
LPS-56513

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
Hey Tina, I tried to simplify the injection process for the PortalCacheManager.  We really aren't going to support multiple types of PortalCacheManagers right?  e..g ehcache and memory in the same VM.

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by tinatian** [comment]
@mhan810 

Hi Michael,

1) Spring objects are not exported automatically, it depends on the value of "module.framework.register.liferay.services" though the default value is "true".
2) I agree that we might not want to let client use more than one type cache manager in one jvm, however, I think we do want to support more than one option,  that is clients can choose which type they want by setting "portal.cache.manager.type.multi.vm" and "portal.cache.manager.type.single.vm", right?
Now we have moved both ehcache and memory cache out  as a osgi bundle, and by default each would register a portal cache manager instance as a "MULTI_VM_PORTAL_CACHE_MANAGER" or "SINGLE_VM_PORTAL_CACHE_MANAGER". It is wrong to filter only with this, since there would be two services registered and we only want  one. 
Another solution is to generate and register service manually rather than using Component annotation, this way we might also need to deal with service dependencies manually. Compared with the bridge solution in this pull, I think the bridge one is better. What do you think?


Tina.

**Comment by mhan810** [comment]
@tinatian 
(1) Actually that property isn't used (should be removed) :) 
(2) Let's talk about this one later on.  Will ping you my morning

**Pull request closed without merging**
