### PR TITLE
[TS] LPS-135731

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-135731
https://issues.liferay.com/browse/PTR-2492

Hi @tinatian ,

Here is the PR for adding multi-threading to improve the portlet deployment time during startup, when a Liferay instance has a large number of companies.

For this PR, I focused on:
- Avoiding any logic change
- Avoiding introducing multi-threading logic in a service call

**Additional Thoughts**
Regarding the multi-threading executor service, I ended up using the PortalExecutor. I tried to make it not overly aggressive, since I'm assuming some users may be deploying modules with portlets during production.

Not sure if we should make the number of threads a configurable value.

Please let me know if you have any questions and if there's any changes you would like me to make.
Thanks!

/cc @dantewang @istvansajtos 

----

**Additional Testing Notes**
During my testing, I did run into this issue quite a few times: [LPS-121471 - Random NPE on startup with theme getColorScheme](https://issues.liferay.com/browse/LPS-121471)

From what I can tell, this issue happens if MainServlet starts serving requests, before the themes are available for use. 

I run into this less often if I clear osgi/state.

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@ericyanLr Is the random issue you mentioned only reproduced with your change or it is also reproduced on master head?

Tina.

**Comment by ericyanLr** [comment]
@tinatian , the random issue is reproducible on master head also. (Not sure if having a large number of companies, increases the chance of it happening)

It's quite random though, sometimes once it happens, the next few restarts have a much higher chance of it happening again. Clearing the osgi/state, seems to reset it, giving you a chance of a state where it doesn't happen as often.

I included an example of the logs in this comment: 
- https://issues.liferay.com/browse/PTR-2492?focusedCommentId=2479079&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2479079

Notice when we start seeing log messages like:
```
[ThemeHotDeployListener:108] 1 theme for classic-theme is available for use
```

If this happens before the request is served, we don't run into the NPE.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10172

**Pull request closed without merging**
