### PR TITLE
pull-request-109190

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@tinatian this came to me from https://github.com/brianchandotcom/liferay-portal/pull/109190

See description / comments there.

**Comment by kevhlee** [comment]
Hi @tinatian,

I was wondering if you were able to take a look at this pull request and [LPS-127157](https://issues.liferay.com/browse/LPS-127157).

**Comment by tinatian** [comment]
@kevhlee I am working on a fix now.

**Comment by kevhlee** [comment]
Got it, @tinatian. Thanks for working on this!

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10391

**Pull request closed without merging**
