### PR TITLE
[portal-impl-integration] LPS-94778 com.liferay.portal.kernel.template.TemplateResourceExternalizationTest

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
ci:reopen

Liferay Continuous Integration <notifications@github.com> 于 2019年4月26日周五
18:29写道：

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7703

**Pull request closed without merging**
