### PR TITLE
LPS-102378

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:help

**Comment by tinatian** [comment]
ci:test:search

**Comment by tinatian** [comment]
ci:test:search-solr

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please help me verify if there is any real failure?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@xbrianlee @joshchong Can you check the search failures?

**Comment by vicnate5** [comment]
@tinatian Other test failures are unrelated, just want search team's input on the search ones.

**Comment by joshchong** [comment]
Hey @vicnate5 @tinatian the failures in ci:test:search and ci:test:search-solr are known and unrelated to this pull.

**Comment by tinatian** [comment]
Cool! Thanks guys @vicnate5 @joshchong !

Tina

**Pull request closed without merging**
