### PR TITLE
LPS-84064 Another way

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian 
There are chances that the servlet context of the request and the servlet context of the portlet is not the same one. An example is the "go-to-site" link in product menu, which is another module being hosted by the product menu portlet. (By the way, only this link is using TagResourceBundleUtil to get the displayed content; other items in the menu use LanguageUtil so they are not affected).

I'm also interested in a deprecated method: `ResourceBundleLoaderUtil.getResourceBundleLoaderByServletContextNameAndBaseName`. Currently no one is using it, but I think this may help with a more precise lookup as long as we can get the correct base name (which is by default "content.Language" for all of our built-in modules). But the servlet context mismatch may also be there and I haven't come up with a good way to deal with it.

Any suggestion?

**Comment by dantewang** [comment]
cc @peterpetrekanics for progress update

**Comment by tinatian** [comment]
@dantewang Could you please check the discussion here? https://github.com/brianchandotcom/liferay-portal/pull/33622, Hope it can give you more info about TagResourceBundleUtil. I think we added this to fix the issue of including a jsp from another bundle.

Could you please send pull to @adolfopa if you have a solution to this? I think he is a better person than me to review this. Just keep the performance in mind while you are working on this, tune it as possible as you can, my bottom line is no regression if we can not improve.

Thanks.
Tina.

**Comment by dantewang** [comment]
opened a PR at https://github.com/adolfopa/liferay-portal/pull/697

**Pull request closed without merging**
