### PR TITLE
LPS-97897 JGroups 2

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Made following changes: 1) Changed parameter names to configLocation; 2) Use JGroups' ConfigurationFactory.getConfigStream() first, if not found then try portal class loader; 3) Squashed commits into 4

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8009

**Pull request closed without merging**
