### PR TITLE
Lps 111631

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result?

Thanks.
Tina

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by mtambara** [comment]
ci:stop

**Comment by mtambara** [comment]
see https://github.com/tinatian/liferay-portal/pull/1764

**Pull request closed without merging**
