### PR TITLE
[spring] LPS-106957 prefs-spring.xml

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8742

**Comment by dantewang** [comment]
@tinatian https://github.com/shuyangzhou/liferay-portal/pull/8742 is closed. What do we need to change?

**Comment by tinatian** [comment]
@dantewang we no longer need to do this change. The original reason we did this is for slim, but we have removed slim, so no need to do this.

Please close those tickets as not-fix.

Thanks.
Tina.

**Pull request closed without merging**
