### PR TITLE
LPS-108781 Apply petra StringBundler to method arguments, part 2

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5 ,
Please scan the test results.

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian No regressions.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8885

**Pull request closed without merging**
