### PR TITLE
[portal-test-integration] LPS-102245 | resend

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Arquillian test runner tries to initialize the test class at client side, where PortalClassLoaderUtil has no class loader registered. So I added another commit to avoid executing the permission checker logic at client side. cc @ChiZeLin

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8551.

I changed the solution to decouple `PermissionCheckerMethodTestRule` and `TikaSafeRandomizerBumper`, please let me know if you have any question.

Tina.

**Pull request closed without merging**
