### PR TITLE
LPS-83764 Add unit test for LiferayObjectWrapper

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian 

Diff w/ last PR:

1. Removed mock usage, use actual object or proxy instead;
2. Removed `setUp` to make the `@Test` using advice pass;
3. Minor SF

**Comment by dantewang** [comment]
cc @caixiangyue

**Comment by dantewang** [comment]
@tinatian 
Still getting the coverage failure about the `catch` part in the static block.

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:reopen

Liferay Continuous Integration <notifications@github.com> 于 2018年7月26日周四
12:54写道：

**Comment by tinatian** [comment]
@dantewang @caixiangyue 
You need to set Exception instead of Throwable because in the static block, it is catching Exception. 

Please clean up the code and resend:
1) Always use generic type, do not do "Map map", do "Map<KeyType, ValueType>" instead
2) Always put a message to Assert.fail(); (I do not think you can pass formatSource if you do this)
3) Rename the inner classes with "Test***", like change LiferayCollection to TestLiferayCollection, this way it would be more clear for people this class is just for test.

Thanks.
Tina.

**Pull request closed without merging**
