### PR TITLE
[bug fix] LPS-126999

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Yuxing explained the reason that he didn't enforce the versions using SF.

Basically only httpclient needs to be upgraded, but newer httpclient needs to depend on newer httpcore and httpmime. So if a module has httpclient and httpcore at the same time, both are upgraded.

Some modules `compileInclude` older version of httpcore but doesn't use httpclient, so they shouldn't be upgraded.

And I think we should either enforce all of httpcomponent dependencies, or enforce none. So this pull is manually upgraded.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @yxingwu @dantewang ,

> Some modules compileInclude older version of httpcore but doesn't use httpclient, so they shouldn't be upgraded.

We may not need to upgrade, but it would be clean to make all of them consistent if no special reason.

Could you please make it consistent and resend?

Thanks.
Tina.

**Comment by yxingwu** [comment]
Hi @tinatian ,
There is a special case, [jsontoken 1.1](https://github.com/liferay/liferay-portal/blob/master/modules/apps/archived/sync-security/build.gradle#L4) has a dependency on [httpcore 4.0.1](https://github.com/liferay/liferay-portal/blob/master/modules/apps/archived/sync-security/build.gradle#L7 ) . If I want to update the jar versions, the best way is update them at same time. But I found [jsontoken](https://mvnrepository.com/artifact/com.googlecode.jsontoken/jsontoken) didn't update any more after Jan, 2014.
 If I only update `httpcore` jar from 4.0.1 to 4.4.13, maybe cause the bugs.
That's why I don't make it consistent. 
BTW, the `httpcore` jar is **not** vulnerable

Regards.
Yuxing

**Pull request closed without merging**
