### PR TITLE
LPS-88873 Upgrade ASM to 7.0

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Xiangyue changed the build.gradle compile dependencies to what's really needed for compiling and tested.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7250

**Comment by tinatian** [comment]
@dantewang @caixiangyue 
Please note I did not include your last commit which build version related files. The reason is the auto-generated file can not reflect your change clearly, it changed a lot of other unrelated stuff. 

Tina.

**Pull request closed without merging**
