### PR TITLE
LPS-75535

### PR DESCRIPTION
**Pull request by juangon**
Hi @tinatian how are you doing?

I found this issue while patching LPS-74330. After this commit: https://github.com/liferay/liferay-portal/commit/57a369e33f78d887b9ed0f6fa98b4e71ebbc0998 HTTP 304 isn't returned anymore for cached pages URL.

Fix makes it working again in 7.0.x. Additionally, I couldn't make it work in master so I suspect master is affected by another issue in this regard.

Thanks!

### CODE REVIEW

**Comment by tinatian** [comment]
Hi @juangon,

Thanks for asking, I am good :)

For the changes you made, I do not think it is right by analyzing the code. Reason is :
If you the return value of `URLUtil.getLastModifiedTime(resourceURL)` is 0, the cache filed should have same lastModified date which is 0, since we do `cacheDataFile.setLastModified(URLUtil.getLastModifiedTime(resourceURL));`

I tried to reproduce this issue on **master** using the steps you provided, each time I refresh on browser, the AggregateFilter is not invoked, so I do not think this is caused by changes in AggregateFilter.

I have not tried this on 7.0.x, because I have some build issue for 7.0.x.

Could you please take a look at this again? Let me know if you have any question, I will try to reproduce this on 7.0.x at the same time.


Thanks.
Tina.

**Comment by juangon** [comment]
Sorry, I didn't have time for debugging. In any case, it will likely affect 7.0.x as this is backported...I checked that fix make this works fine again.

Do you have any hint what could be happening? As you said if 0 is being set before, then it should be equal and should give true for that comparison. Maybe isn't being stored somehow?

**Comment by tinatian** [comment]
@juangon 
One possible reason I can think up is somehow you got 0 for the first time, and later you get another value, or vice versa. But why you get different value even though you did not modify anything? that's confusing me.

I debugged on master, and I am sure that this issue on master is not caused by my changes of AggregateFilter, since when you do refresh on browser, the AggregateFilter won't be invoked at all. 

I will try to take a look at it recently, but still have other stuff in hand, so it might take some time.


Tina.

**Comment by juangon** [comment]
As per LPS comment, I close this. After rechecking today with LPS commits, Http 304 seems to be working fine.

**Pull request closed without merging**
