### PR TITLE
[deprecation] LPS-106339 Remove UserGroupLocalServiceImpl#copyUserGroupLayouts

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang This need to update functional test case: portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/administration/users/cpusergroups/UsergroupsUsecase.testcase.

Please resend.

Tina

**Comment by kyle-miho** [comment]
Just started reviewing :)

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8676

**Pull request closed without merging**
