### PR TITLE
LPS-143420

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, @tinatian
this is resubmitted from #2461 to separate by each **Util classes and reduced to have less commits.

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/98

**Pull request closed without merging**
