### PR TITLE
LPS-108588

### PR DESCRIPTION
**Pull request by tinatian**
FYI @achaparro

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:backend

**Comment by tinatian** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@achaparro Unique failures here related to Workflow. The user cannot assign a workflow task to themselves.

Steps to Reproduce (based on the test, I have not yet been able to test locally)
1. Navigate to Site Admin > Configuration > Workflow
2. Set "Blogs Entry" to Single Approver
3. Add a new Blog entry
4. Go to User menu > My Workflow Tasks
5. Go to "Assigned to My Roles" tab
6. Attempt to "Assign to Me" on the Blog entry

Error:
```
Caused by: java.lang.NullPointerException
	at com.liferay.portal.workflow.kaleo.runtime.integration.internal.WorkflowTaskManagerImpl.assignWorkflowTaskToUser(WorkflowTaskManagerImpl.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.portal.kernel.messaging.proxy.ProxyRequest.execute(ProxyRequest.java:82)
	at com.liferay.portal.kernel.messaging.proxy.ProxyMessageListener.receive(ProxyMessageListener.java:58)
	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
	at com.liferay.portal.messaging.internal.SynchronousDestination.lambda$dispatch$0(SynchronousDestination.java:46)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```

Full log (also seeing many index issues): https://testray.liferay.com/reports/production/logs/test-1-7/1589950830693/test-portal-acceptance-pullrequest%28master%29/5478/functional-tomcat90-mysql57-jdk8/11/0/liferay-log.txt.gz

**Comment by vicnate5** [comment]
Most of the integration test failures are also unique. The workflow issue is also caught there.
https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/283558/#showFailuresLink

Additional unique backend failures show this error:
```
     [exec]     java.lang.AssertionError: Thread Thread[liferay/export_import_lifecycle_event_sync-3,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.exportimport.internal.lifecycle.ExportImportProcessCallbackLifecycleListener, message=Unable to execute export import process callback
     [exec]     java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.exportimport.internal.lifecycle.ExportImportProcessCallbackLifecycleListener, message=Unable to execute export import process callback
     [exec]     	at com.liferay.portal.test.rule.LogAssertionAppender.append(LogAssertionAppender.java:60)
     [exec]     	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
     [exec]     	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
     [exec]     	at org.apache.log4j.Category.callAppenders(Category.java:206)
     [exec]     	at org.apache.log4j.Category.forcedLog(Category.java:391)
     [exec]     	at org.apache.log4j.Category.log(Category.java:856)
     [exec]     	at com.liferay.portal.log.Log4jLogImpl.error(Log4jLogImpl.java:54)
     [exec]     	at com.liferay.portal.kernel.log.LogWrapper.error(LogWrapper.java:69)
     [exec]     	at com.liferay.exportimport.internal.lifecycle.ExportImportProcessCallbackLifecycleListener.onProcessSucceeded(ExportImportProcessCallbackLifecycleListener.java:73)
     [exec]     	at com.liferay.exportimport.lifecycle.DefaultProcessAwareExportImportLifecycleListener.onProcessSucceeded(DefaultProcessAwareExportImportLifecycleListener.java:222)
     [exec]     	at com.liferay.exportimport.lifecycle.DefaultProcessAwareExportImportLifecycleListener.callProcessHandlers(DefaultProcessAwareExportImportLifecycleListener.java:130)
     [exec]     	at com.liferay.exportimport.lifecycle.DefaultProcessAwareExportImportLifecycleListener.onExportImportLifecycleEvent(DefaultProcessAwareExportImportLifecycleListener.java:47)
     [exec]     	at com.liferay.exportimport.lifecycle.BaseExportImportLifecycleMessageListener.doReceive(BaseExportImportLifecycleMessageListener.java:45)
     [exec]     	at com.liferay.portal.kernel.messaging.BaseMessageListener.doReceive(BaseMessageListener.java:48)
     [exec]     	at com.liferay.portal.kernel.messaging.BaseMessageListener.receive(BaseMessageListener.java:31)
     [exec]     	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74)
     [exec]     	at com.liferay.portal.messaging.internal.SynchronousDestination.lambda$dispatch$0(SynchronousDestination.java:46)
     [exec]     	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec]     	Suppressed: java.lang.AssertionError: {level=ERROR, loggerName=com.liferay.exportimport.kernel.lar.ExportImportDateUtil, message=org.springframework.dao.CannotAcquireLockException: Could not execute JDBC batch update; SQL [insert into PortletPreferences (mvccVersion, ctCollectionId, companyId, ownerId, ownerType, plid, portletId, preferences, portletPreferencesId) values (?, ?, ?, ?, ?, ?, ?, ?, ?)]; nested exception is org.hibernate.exception.LockAcquisitionException: Could not execute JDBC batch update
     [exec]     		at com.liferay.portal.test.rule.LogAssertionAppender.append(LogAssertionAppender.java:60)
     [exec]     		at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
     [exec]     		at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
     [exec]     		at org.apache.log4j.Category.callAppenders(Category.java:206)
     [exec]     		at org.apache.log4j.Category.forcedLog(Category.java:391)
     [exec]     		at org.apache.log4j.Category.log(Category.java:856)
     [exec]     		at com.liferay.portal.log.Log4jLogImpl.error(Log4jLogImpl.java:54)
     [exec]     		at com.liferay.portal.kernel.log.LogWrapper.error(LogWrapper.java:69)
     [exec]     		at com.liferay.exportimport.kernel.lar.ExportImportDateUtil.updateLastPublishDate(ExportImportDateUtil.java:397)
     [exec]     		at com.liferay.exportimport.internal.controller.PortletExportControllerImpl$UpdatePortletLastPublishDateCallable.call(PortletExportControllerImpl.java:1481)
     [exec]     		at com.liferay.exportimport.internal.controller.PortletExportControllerImpl$UpdatePortletLastPublishDateCallable.call(PortletExportControllerImpl.java:1438)
     [exec]     		at com.liferay.exportimport.internal.lifecycle.ExportImportProcessCallbackLifecycleListener.onProcessSucceeded(ExportImportProcessCallbackLifecycleListener.java:70)
     [exec]     		... 12 more
```
Examples:
[com.liferay.depot.web.internal.item.selector.provider.test.GroupItemSelectorProviderImplTest.testGetGroupsCountStaging](https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/283558/AXIS_VARIABLE=8,label_exp=!master/testReport/junit/com.liferay.depot.web.internal.item.selector.provider.test/GroupItemSelectorProviderImplTest/testGetGroupsCountStaging/)
[com.liferay.journal.upgrade.v1_1_6.test.UpgradeAssetDisplayPageEntryTest.testUpgradeLocalStagingGroupMultipleArticlesMultipleVersions](https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/283558/AXIS_VARIABLE=19,label_exp=!master/testReport/junit/com.liferay.journal.upgrade.v1_1_6.test/UpgradeAssetDisplayPageEntryTest/testUpgradeLocalStagingGroupMultipleArticlesMultipleVersions/)

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Fix workflow issue at https://github.com/tinatian/liferay-portal/pull/1833.

**Pull request closed without merging**
