### PR TITLE
LPS-145171

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian ,

Resend
As discussed, I make changes to "wsadmin.py", and relocate unused properties

1. remove unused file "wsadmin.py", based on commit e930ab6f2b44e116a95a6390366a6c88d83d127e, see LPS-61201
2. relocate unused properties from portal.properties to build.properties, which included "auto.deploy.websphere.wsadmin.app.manager.install.options
auto.deploy.websphere.wsadmin.app.manager.list.options, auto.deploy.websphere.wsadmin.app.manager.update.options, auto.deploy.websphere.wsadmin.app.manager.query".

Thanks for checking!

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:environments

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by zhangyan0701** [comment]
ci:test:environments

**Comment by zhangyan0701** [comment]
The Websphere tests passed in the latest job.

**Comment by tinatian** [comment]
@jeffwu0724 Please also remove related variables defined in PropsValues and PropsKeys. Please put this into your list, I am going to close this pull.

**Pull request closed without merging**
