### PR TITLE
[deprecation] LPS-106564 util-taglib

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This one is a bit late. If there's still time, I think maybe we can let front-end guys take a look.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Please scan the test result.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Results look good

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8708

**Comment by tinatian** [comment]
@dantewang @yuhai  I did not include the commits about input editor, cause the whole input editor has been deprecated, no need to remove the deprecated fields, it should be removed as a whole once usages of input editor are gone.

Tina.

**Pull request closed without merging**
