### PR TITLE
LPS-142626

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina, @tinatian 

This is resubmitted from #2450 to reduce duplicated code in filter logic.
I added an overloaded method with additional FileFilter param and extracted the logic that appends and concat class paths into a string

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by tinatian** [comment]
@julschong  Please resend as we have talked this afternoon.

Thanks.
Tina.

**Pull request closed without merging**
