### PR TITLE
Lps 140576 master

### PR DESCRIPTION
**Pull request by SamZiemer**
Hi @tinatian, here is the configuration upgrade with tests as you requested. Let me know if there is anything that could be improved here.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@SamZiemer The integration test did not cover all the cases we may meet.
First, you need to understand what kind of data will stay in database before you upgrade, then you verify all the data based on the requirement below:
In Configuration_ table, all the factory pid stored in the cofigurationId column should use "~" as separator
In Configuration_ table, the dictionary column, the service.pid value should match its cofigurationId column
In Configuration_ table, the dictionary column, if it has "felix.fileinstall.filename" set, and the corresponding file existed, please update the cofigurationId column:
       a. Suppose file name is "my.configuration-default.config", the cofigurationId column needs to be  "my.configuration~default.config"
        b. Suppose file name is "my.configuration_default.config", the cofigurationId column needs to be  "my.configuration~default.config"
         c. Suppose file name is "my.configuration~default.config", the cofigurationId column needs to be  "my.configuration~default.config"

**Comment by tinatian** [comment]
@SamZiemer The integration test did not cover all the cases we may meet.
First, you need to understand what kind of data will stay in database before you upgrade, then you verify all the data based on the requirement below, please read the code and try to understand what kind of data it might have. Please feel free to come to me if you have no clue how to do it.

```
In Configuration_ table, all the factory pid stored in the cofigurationId column should use "" as separator
In Configuration_ table, the dictionary column, the service.pid value should match its cofigurationId column
In Configuration_ table, the dictionary column, if it has "felix.fileinstall.filename" set, and the corresponding file existed, please update the cofigurationId column:
a. Suppose file name is "my.configuration-default.config", the cofigurationId column needs to be "my.configurationdefault.config"
b. Suppose file name is "my.configuration_default.config", the cofigurationId column needs to be "my.configurationdefault.config"
c. Suppose file name is "my.configurationdefault.config", the cofigurationId column needs to be "my.configuration~default.config"
```

**Pull request closed without merging**
