### PR TITLE
[Bug fix] LPS-135357

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This pull includes https://github.com/tinatian/liferay-portal/pull/2354 as they modify the same file.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10248

**Pull request closed without merging**
