### PR TITLE
[portal-impl-integration] LPS-96126 Resource*ServiceTest to portal-security-permission-test

### PR DESCRIPTION
**Pull request by dantewang**
Moved to portal-security-permission-test since all the tested services are permission-related.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7833

**Pull request closed without merging**
