### PR TITLE
LPS-122557 git commit

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
@vicnate5 Could you please check if those unique failures real?

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian Failures are unrelated. First one Matt fixed and I need to make sure it gets applied. The second one I fixed this morning.

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
@vicnate5 Could you please test this pull? 
Before: all cluster nodes will be blocked when exceeding max cluster node size
With this pull: only the latest cluster nodes are blocked when exceeding max cluster node size, please note the overload cluster node number may > 1.

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian FAILED manual testing.

When an extra node is added, the first 2 nodes are no longer accessible with LCS error. The 3rd node is still running and redirects to activation page.

ExceedingNodeCount

Logs from each node
node1 https://gist.github.com/vicnate5/0897c784075d855eefb05c6922bed124
node2 https://gist.github.com/vicnate5/e5bed5124b35e62d66118cb3a8d4ed95
node3 (exceeding) https://gist.github.com/vicnate5/d06640849f257473292b76d9210d0c3c

Will DM you a link to the bundle I used for testing. I compiled locally using this branch and portal master.

**Comment by tinatian** [comment]
@vicnate5 My bad, forgot to expose the new added method, I just pushed one more commit to the release repo pull, could you please test it one more time?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian PASSED Manual Testing.

Execute tests 1a, 1b, 2a, 2c. Test steps modified for this new requirement where needed.
https://docs.google.com/document/d/1aRqP8C8hQtHxqOpMEZ7yyoJv8XueEWMbdqsRuYj33m8/edit#

**Pull request closed without merging**
