### PR TITLE
[bug fix] LPS-95571 Sybase: REPLACE does not support TEXT as parameter

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://issues.liferay.com/browse/LPS-95571

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@tinatian Pulls for blockers:
https://github.com/tinatian/liferay-portal/pull/1614
https://github.com/tinatian/liferay-portal/pull/1616
https://github.com/tinatian/liferay-portal/pull/1618

Hai tested upgrading from 7.0 to master with all these fixes.

**Comment by achaparro** [comment]
Hi @dantewang, @yuhai, @tinatian,

We have a framework to be used in these cases where we need to execute different queries depending on the database:
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/upgrade/v7_0_3/UpgradeMessageBoards.java#L137

Could you rewrite the changes using it?

Thanks.

**Comment by tinatian** [comment]
@dantewang @yuhai Please resend as @achaparro requested.

Thanks.
Tina

**Pull request closed without merging**
