### PR TITLE
LPS-108588 DB Partition: scheduled jobs

### PR DESCRIPTION
**Pull request by achaparro**
Hi @tinatian,

I have applied the wrapping approach you suggested in our call. Can you review it?

Thanks!

PS: Maybe more tests than needed will run since some unrelated commits are added to the pull due to the repo is not up to date.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@achaparro I will close this as we talked yesterday.

Tina.

**Pull request closed without merging**
