### PR TITLE
[portal-test-integration] LPS-102159 BaseDBTestCase master

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

**Comment by tinatian** [comment]
Hi @dantewang @ChiZelin
Let's move BaseDBTestCase to portal-impl.

Generally portal-test contains test utils, not detailed test case logic like this one, thus I think it would be better to move it to portal-impl.

Tina.

**Comment by dantewang** [comment]
@tinatian This class should be in portal-impl/test/unit if we move it to portal-impl, but then it won't be accessible for the sub classes in those private modules.

**Comment by tinatian** [comment]
@dantewang 
Why it is not seen by private modules? Did we do something special in gradle?

Tina.

**Comment by tinatian** [comment]
@dantewang 
I see, we did not include test classes in portal-impl.jar.

Tina.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8381

**Pull request closed without merging**
