### PR TITLE
LPS-74148 SampleSQLBuilder #1 Clean up and SF

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian I appended a change to the csv writer handling. From git log and what I remember, the property was extracted to the properties file for plugins to create their own SampleSQLBuilder by extending portal's. I think this is no longer needed now so I removed it. Please drop the last 2 commits related to CSV logic if you thinkit may still be used in some occasions.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by tinatian** [comment]
Hi @dantewang @slnn ,
Please see https://github.com/slnn/liferay-portal/pull/463.
 
@dantewang for the csv property removal, please create a new ticket and resend. By the way, why you are using computeIfAbsent when populating csvwriters? I thought the ftl files should be rendered with the same order we defined, not concurrently.

Tina.

**Comment by dantewang** [comment]
@tinatian I see. I chose it just for simpler logic and didn't notice about the concurrent modification protection. Will go back to normal way to populate csv writers.

**Pull request closed without merging**
