### PR TITLE
LPS-119196 FAKE GRADLE CACHE

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian,
 did you have time to take a look to this PR?
Kind regards.

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian,
 do you have any updates about this PR?
Kind regards.

**Comment by tinatian** [comment]
@marianoalvarosaiz Sorry for the delay, busy with blockers recently.
I still have a question about this ticket.
For this example in the description: `CN=Admin Two\\,OU=test,DC=liferay,DC=com`, what would the value I really want to set?
Could you please add more test to show the expected values for the cases you are fixing?

Tina.

**Comment by marianoalvarosaiz** [comment]
No worries, I understand the delay.

The idea is to not unescape when calling _ConfigurableUtil._createConfigurableSnapshot()_ since the string can be already unescaped and can break all places where that's assumed. I've created a new test, see https://github.com/tinatian/liferay-portal/pull/1969

**Pull request closed without merging**
