### PR TITLE
[Bug fix] LPS-129172 3-25

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@vicnate5 The current master has startup failure on commerce modules, which will fail a lot of CI tests. The resolve failures of `com.liferay.headless.commerce.punchout.impl` should be irrelevant of this pull.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9893

**Pull request closed without merging**
