### PR TITLE
LPS-72061 Add both categories and tags to the asset publisher query

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
cc @tomwang2011

**Comment by tinatian** [comment]
@dantewang  Are you sure this is working? Can you really query by "AssetContains"? I can only see "assetTags" and "assetcategories" on UI.

**Comment by dantewang** [comment]
I saw the ap pages showing different filtered content. Will double check
the filters in UI tomorrow.

Tina Tian <notifications@github.com>于2017年4月21日周五 00:24写道：

**Comment by tinatian** [comment]
Where did you find "AssetContains" and "AssetNotContains"?

**Comment by dantewang** [comment]
Thought it was just a name...

Tina Tian <notifications@github.com>于2017年4月21日周五 00:38写道：

**Comment by tinatian** [comment]
No, it is something generated from UI. I will work on this today, will cc you once I finished.

**Pull request closed without merging**
