### PR TITLE
LPS-78082 Add to deprecated list according to GitId:c969332ac1079d67eb70a540883dc8d4415bacdd

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian This property has been removed in original commits of LPS-78082

**Comment by tinatian** [comment]
@dantewang Is this blocking our test? If no, let's wait for the fix of performance regression caused by this ticket. Not sure if we need to revert all their changes.

Tina.

**Comment by dantewang** [comment]
@tinatian No, we can wait.

Tina Tian <notifications@github.com>于2018年3月21日周三 上午12:55写道：

**Comment by tinatian** [comment]
@dantewang Do we still need this?

**Comment by dantewang** [comment]
@tinatian Yes, since the regression is addressed without reverting, it's still needed.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/5952

**Pull request closed without merging**
