### PR TITLE
LPS-111020 Upgrade dom4j to 2.1.1

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian poshi-runner is excluded since it's irrelevant to the security issue and upgrading causes many test failures.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8986

**Pull request closed without merging**
