### PR TITLE
[MB Performance] LPS-96121 Get root message from MBTreeWalker

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,

Could you please verify the test result here?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian test failures not related.

**Comment by tinatian** [comment]
Thanks @vicnate5!

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7842

**Pull request closed without merging**
