### PR TITLE
[SyntheticBundleClassTestRule] LPS-94205 | format, rebase and resend

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7728.
@dantewang @ChiZelin 
I did not include the portalImpl test change cause I am not sure if that test is OK to be a unit test, it seems it wants to test something in a real env. See my changes for more details and let me know if you have any question.

Thanks.
Tina

**Comment by dantewang** [comment]
@tinatian Thanks! Just wondering, do you see some warnings when executing `PortalImplTest.testGetUserId()` after moving it to unit? I saw two warnings from `PortalImpl.getDoAsUserId()` (around line 7728) because the mock request or unit test env lacked context of Company etc.

**Comment by dantewang** [comment]
@tinatian 
It's this warning:
```
WARNING: Unable to impersonate 0 because the string cannot be decrypted
```
See https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/304841/AXIS_VARIABLE=0,label_exp=!master/consoleFull

**Comment by tinatian** [comment]
Thanks @dantewang ! I fixed it and updated the pull.

Tina.

**Pull request closed without merging**
