### PR TITLE
[deprecation round2] LPS-103951 portal-kernel part 3

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://issues.liferay.com/browse/LPS-103951; Just to note, part 2 is still in review

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@vicnate5 Is the `StringUtil` I try to replace in https://github.com/tinatian/liferay-portal/pull/1580/commits/2cff3c6fe49ae65906b931a16a24c65f069d0a30 the same one in portal-kernel? If so, do you know how to get rid of the failure of https://github.com/tinatian/liferay-portal/pull/1580#issuecomment-551035618? Thanks!

**Comment by vicnate5** [comment]
@dantewang This is working after the revert https://github.com/tinatian/liferay-portal/pull/1580/commits/b10c4dcf83e4b5ee0123bf825fcbe5568834b2c8

The `StringUtil` in Poshi is using this class: https://github.com/liferay/liferay-portal/blob/master/modules/test/poshi-runner/poshi-runner/src/main/java/com/liferay/poshi/runner/util/StringUtil.java

In the future you can validate poshi changes locally with: `ant -f build-test.xml run-poshi-validation`

**Comment by dantewang** [comment]
@vicnate5 I see. Thanks! I'll resend without that change.

**Pull request closed without merging**
