### PR TITLE
remove_deprecated_part_1

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian .

I have removed deprecated methods for **"portal-impl/src/com/liferay/portal/deploy/hot"**, **"portal-impl/src/com/liferay/portal/events"**, **"portal-impl/src/com/liferay/portal/language"**, **"portal-impl/src/com/liferay/portal/cache/key"** and **"portal-impl/src/com/liferay/portal/change/tracking"**.
see https://github.com/jeffwu0724/liferay-portal/pull/19.

Thanks,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test:app-servers

**Comment by jeffwu0724** [comment]
@vicnate5 Can you help me scan the test result, please?

Thanks.
Jeff

**Comment by vicnate5** [comment]
@zhangyan0701 can you check the app server results once they upload to Testray? The rest of the test results are unrelated.

**Comment by tinatian** [comment]
@jeffwu0724 I guess you trigger "ci:test:app-servers" in wrong pull. We need to trigger it for the pull to remove wsadmin.py, not this one, right?

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/323

**Comment by jeffwu0724** [comment]
> @jeffwu0724 I guess you trigger "ci:test:app-servers" in wrong pull. We need to trigger it for the pull to remove wsadmin.py, not this one, right?

Hey Tina, I trigger "ci:test:app-servers" here because I check out ci:test report, and I saw some errors about "Wildfly, Weblogi, Websphere", which is similar as the case in "https://github.com/liferay-core-infra/liferay-portal/pull/305".  In that PR, Victor told me to run "ci:test:app-servers" to see how will it go, so I decided to do the same thing in this PR and see if I can figure out the bug.

**Comment by zhangyan0701** [comment]
> @zhangyan0701 can you check the app server results once they upload to Testray? The rest of the test results are unrelated.

The app server results are also unrelated.

**Pull request closed without merging**
