### PR TITLE
LPS-104416 PropsValues for SampleSQLBuilder

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Lily wants to write the CT part on top of this so that it's easier to use the properties.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9162

**Comment by tinatian** [comment]
@slnn @dantewang Please see Shuyang's comment https://github.com/shuyangzhou/liferay-portal/pull/9162#issuecomment-644455114.

**Comment by dantewang** [comment]
Got it

**Pull request closed without merging**
