### PR TITLE
[ResourceAction] LPS-117531

### PR DESCRIPTION
**Pull request by yuhai**
cc @dantewang

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by yuhai** [comment]
ci:test

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by zhangyan0701** [comment]
Comparison with master head:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1270793907&testrayRunIdA=1270632088&statusB=2

Almost all tests failed when create virtual instance, below error in console:
`04:37:24,775 ERROR [http-nio-8080-exec-3][EditInstanceMVCActionCommand:121] com.liferay.portal.kernel.exception.NoSuchResourceActionException: 90#MANAGE_COMMERCE_HEALTH_STATUS
com.liferay.portal.kernel.exception.NoSuchResourceActionException: 90#MANAGE_COMMERCE_HEALTH_STATUS`

Example full console output:
https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/428485/consoleFull

**Comment by yuhai** [comment]
Thanks, @zhangyan0701, I will check this.

**Pull request closed without merging**
