### PR TITLE
LPS-106669 Upgrade Freemarker

### PR DESCRIPTION
**Pull request by dantewang**
Previously tested in https://github.com/slnn/liferay-portal/pull/471

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang Please run performance test to verify that we are not bringing any performance regression.

Thanks.
Tina

**Comment by dantewang** [comment]
@tinatian FYI performance result https://github.com/slnn/liferay-portal/pull/471#issuecomment-586572482

**Comment by tinatian** [comment]
@dantewang we do have regression according to Lily's comment, please figure out the reasons, or else we can not move on.

Thanks.
Tina.

**Comment by dantewang** [comment]
@tinatian Which test cases show regression in Lily's comment?

The "decrease" showed in the 3 test cases are less than 1%. The largest one is 0.8%. Also, other test cases show "increase" by 1% ~ 4%. Increase/descrease of 1% are within the deviation of our performance testing environment. Based on this I'd consider the performance of this pull **at least not worse** than before.

I'll ask Lily to run it again for another diff, but if this pull doesn't introduce improvement nor regression, we will always see small increase/decreases.

**Comment by tinatian** [comment]
Sorry @dantewang , I was wrong, I thought there was a 8% down on blog.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8906

**Pull request closed without merging**
