### PR TITLE
[Company-Log] LPS-154229

### PR DESCRIPTION
**Pull request by yuhai**
@tinatian, @dantewang, SF can't be passed. I didn't find the reason yet.

### CODE REVIEW

**Comment by yuhai** [comment]
@tinatian, @dantewang, I just push force two commits. In order to review convenient, I didn't merge them to the previous commits.

**Comment by yuhai** [comment]
@tinatian, @dantewang, I just push force new change to make SF happy.

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai I see you use an SF suppression because the private fields in your builder does not start with `_`. Is that demanded by the Log4J plugin mechanism?
I wonder if you can just extend `RollingFileAppender.Builder` and override only `build()` method... that builder should have getter methods for all of its plugin fields... Will that work?

**Comment by yuhai** [comment]
@dantewang, @tinatian, sorry, I didn't get email notification when you @ me. I don't know the reason for now. I will check the issue.

Update:
1.  Log4J provided mechanism to let private field start with **_**.
2. We can't extends RollingFileAppender.Builder because RollingFileAppender.Builder#build() return RollingFileAppender.

send it to https://github.com/liferay-core-infra/liferay-portal/pull/855

**Pull request closed without merging**
