### PR TITLE
Lps 115420 lps 115687 7

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@GinsonRen Please run a diff on this pull, please run those with big regressions first, if you still see regression with this pull, please gather memory and cpu profiles. if you did not see regression, go on to gather result of other test cases.

FYI @dantewang @slnn

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
Hi @tinatian , I cannot see the regression any more. Here is the result:

Login:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5af927be | 44,329 | 272 | 81.7 | -
PR-1873 | - | 44586 | 278 | 83.7 | 0.58%

WC:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5af927be | 53,297 | 508 | 156 | -
PR-1873 | - | 53427 | 557 | 169 | 0.24%

MB:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5af927be | 16757 | 29 | 78.8 | -
PR-1873 | - | 16756 | 27.6 | 78.6 | -0.01%

Blog:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5af927be | 13,985 | 149 | 234 | -
PR-1873 | - | 14285 | 154 | 236 | 2.15%

DL:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5af927be | 24,604 | 242 | 336 | -
PR-1873 | - | 24522 | 240 | 334 | -0.33%

Wiki:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5af927be | 15361 | 256 | 481 | -
PR-1873 | - | 15147 | 257 | 478 | -1.39%

AP:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5af927be | 24,665 | 434 | 182 | -
PR-1873 | - | 24756 | 425 | 175 | 0.37%

/cc @dantewang @slnn

**Pull request closed without merging**
