### PR TITLE
[TS] LPS-84064 Module containing multiple portlets and resource bundles will always read from first

### PR DESCRIPTION
**Pull request by peterpetrekanics**
Hi Tina,

I would like to ask for your kind help:
Please review my fix, and forward it to the next approver in case you find everything ok.
I have created this fix with the help of Minhchau Dang.
Link to my LPS:
LPS-84064

Thank you,
Peter

### CODE REVIEW

**Comment by peterpetrekanics** [comment]
ci:test

**Comment by peterpetrekanics** [comment]
ci:reopen

**Comment by tinatian** [comment]
@dantewang Could you please take a look at this?

Thanks.
Tina.

**Comment by dantewang** [comment]
Fetched <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dantewang** [comment]
Hi @peterpetrekanics this PR at least breaks the localization `go-to-site` link in site administration section in the product menu.

Start portal built from this PR, login, open product menu, and you'll see the language key `go-to-site` being displayed, instead of the actual string "Go to site".

**Comment by dantewang** [comment]
@peterpetrekanics I sent you a PR as an example to get the `go-to-site` link working, see https://github.com/peterpetrekanics/liferay-portal/pull/1

Please review the issue and the whole solution carefully to make sure no other places are broken. Thanks!

**Comment by tinatian** [comment]
Close as @dantewang 's comment

**Pull request closed without merging**
