### PR TITLE
LPS-122557 git commit

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
@vicnate5 Could you please check the test results?

Thanks
Tina

**Comment by vicnate5** [comment]
ci:test:license-cluster

**Comment by vicnate5** [comment]
@tinatian No access to localhost:8080 on the first node when using a `virtual-cluster` license, this is why all the license-cluster automation failed. I also reproduced locally.

CI test logs can be found at: https://testray.liferay.com/home/-/testray/case_results/1525570053

Here is the bundle and license I used to reproduce locally: https://drive.google.com/drive/folders/1FGBU5ANeYc_rtet4FamumVtFmrn8GhU5?usp=sharing
(key validator is disabled)

The issue was **not** reproducible when I used a `developer-cluster` license (no node limit set)

**Pull request closed without merging**
