### PR TITLE
[Bug Fix] LPS-137136 Jdom | 10-21

### PR DESCRIPTION
**Pull request by dantewang**
- LPS-137136 Update rometools to 1.16.0
- LPS-137136 Replace Liferay patched Rome 1.0 usages with Rometools
- LPS-137136 Remove rome.jar
- LPS-137136 Replace jdom usages with jdom2
- LPS-137136 Remove jdom.jar
- LPS-137136 Don't import optional jdom 1 packages in these modules
- LPS-137136 Remove the patch module for old Rome
- LPS-137136 Create patch module for JDom2
- LPS-137136 Check in original code
- LPS-137136 Patch SAXBuilder to always set expand entities to false and ignore user input
- LPS-137136 FAKE GRADLE CACHE
- LPS-137136 Apply
- LPS-137136 Auto SF
- LPS-137136 Build lib versions

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @dantewang , please seehttps://github.com/shuyangzhou/liferay-portal/pull/10372. Please note I did not include the removal of patched Rome as it might be used by other versions.

Tina

**Pull request closed without merging**
