### PR TITLE
[portal-impl-integration] LPS-95463 XmlRpcParserTest

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @dantewang @ChiZelin ,
Is there any reason we can not make it a unit test?

Tina.

**Comment by dantewang** [comment]
@tinatian See https://github.com/tinatian/liferay-portal/pull/1386

**Pull request closed without merging**
