### PR TITLE
[deprecation] LPS-106409 Remove other unused stuff from portal-impl

### PR DESCRIPTION
**Pull request by dantewang**
As https://github.com/tinatian/liferay-portal/pull/1658#issuecomment-569214181

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8679

**Pull request closed without merging**
