### PR TITLE
LPS-98695 Set _initialized to false when activating component

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
Hi @tinatian 

@jkappler and I found some unexpected behaviour while redeploying contributed fragments.
- After redeploying contributed fragments, they are displayed multiple times within the Content Page Editor. It seems they are not being removed correctly from the tracker
- If _initialized is set to true, after redeploying _fragmentEntries is never recomputed which leads to a NPE
- We noticed that _fragmentEntries is always null in FragmentCollectionContributorTrackerImpl.unsetFragmentCollectionContributor when undeploying contributed fragments. Could lines 142-156 be removed?

Can you take a look at these changes and see if they make sense to you?

We also noticed that some commits were linked to LPS-98659 instead of LPS-98695.

Thanks a lot!

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @ruben-pulido and @jkappler ,

Thanks for letting me know, this is a problem, and I agreed that we should always remove the contributor. However, I do not think we should do "_initialized = false;" theoretically, this is useless cause every time the bundle is redeployed, a new instance will be created and "_initialized" will be initialized to false.

Could you please try if your problem can be fixed by the first commit? If not, please send me steps to reproduce the issue,  I will take a look at what happened.


Thanks.
Tina.

**Comment by jkappler** [comment]
Hi @tinatian, you just have to redeploy either the basic component or basic section fragment collection contributor modules to reproduce the issue

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by tinatian** [comment]
Hi @jkappler，
Thanks! If you still see the problem, Could you please list the detailed steps about how to reproduce it? Actually I am not familiar with how we use fragments on UI.

Thanks.
Tina.

**Comment by jkappler** [comment]
I'm testing and it seems everything works well with only the first commit. I'll check it out more and cc you in the pull if everything goes well.

Thanks @tinatian

**Comment by tinatian** [comment]
Cool! Thanks @jkappler !

Tina

**Pull request closed without merging**
