### PR TITLE
LPS-136753

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian,
 I've seen Shuyang's comment: https://github.com/shuyangzhou/liferay-portal/pull/10203#issuecomment-895417393.

I understand his concerns, but should be leave into the customer hands the following: " is to change the code to avoid mixing large batch reading with writing"? It makes sense, but they don't now the inners of Liferay transactional cache, and what they are doing is just that, iterating through a large batch read to change the events that satisfy a certain condition (you can see their code in https://issues.liferay.com/browse/LPP-41717?focusedCommentId=2501179&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2501179).

Would it be possible to remove the cached items when the buffer gets exhausted instead of relying on the customer good practices? That will not lead to inconsistent data, since they will only have reach the data through the DB.

Kind regards.

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian,
 did you have a chance to take a look to the previous comment?
Kind regards.

**Comment by tinatian** [comment]
Hi @marianoalvarosaiz ,
This does not sound right to me.

For example, you already have a entry stored in the entity cache, and you start a new transaction to modify it, you should end up the entry stored in cache cleared or updated when the transaction is fully committed. With you change, the update change of cache may be ignored as the uncommited buffer is cleared which means you are missing the update event triggered by transaction invocation.

Tina.

**Comment by tinatian** [comment]
@marianoalvarosaiz Close for now, please reopen if needed.

Tina.

**Comment by marianoalvarosaiz** [comment]
Hi @tinatian,
 I don't understand your first sentence. As you can see in https://github.com/tinatian/liferay-portal/pull/2373, with https://github.com/marianoalvarosaiz/liferay-portal/commit/d5faceac417e7d9ce0704e6d18f9ffc854aa55f7, if there was a already a value in the portalCache, and the buffer gets exhausted, the portalCache will be cleared, so no inconsistent value will be saved and the code will need to retrieve the value from DDBB.
Kind regards.

**Comment by tinatian** [comment]
@marianoalvarosaiz Sorry I misunderstood your code. As Shuyang's comment, this solution is breaking transactional's acid. I am going to fix this issue in another way. Will update you. 

Thanks.
Tina.

**Pull request closed without merging**
