### PR TITLE
LPS-84130 Rebase 08-27

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by Emmaliu** [comment]
Thanks @dantewang @tinatian for working on this. As this is a customer reported issue and it has been a while since they reported the ticket, would it be possible to take this one with higher priority?

Thanks,
Emma

**Comment by tinatian** [comment]
Hi @dantewang ,
There are some questions about this I would like you to think:
1) Do you need to register GlobalClassLoader like what we did for ClassLoaderPool. The reason we have this for ClassLoaderPool is we need to know the global class loader to deserialize class. If you think you also need it here, please tell me the reason.

2) Do you need to provide a fallback for getContextName() and getClassLoader()? I mean when you can not find the mapping between context name and class loader, do you need to provide a fall back, like return "null" for context name. This is needed for ClassLoaderPool also because of serialization reason. Please give me your reason if you think you need the fall back.


Tina.

**Comment by dantewang** [comment]
@tinatian 
After reviewing and debugging, I don't find any reason for either the GlobalClassLoader or the fallback to exist in the ServletContextClassLoaderPool. I think they should be removed. I'll make the changes.

Additionally, I have a question. Currently servlet context name - class loader mappings are registered/unregistered in both `CustomServletContextHelper` and `PluginContextListener`. For WARs that will be processed to be WABs, both classes will be invoked, causing registering/unregistering to happen twice.

I hesitate to remove registering/unregistering logic from the latter one because I still see something to be deployed in old ways, like the old portlet-tck2 portlets.

What do you think about this?

---

If we keep registering/unregistering logic in `PluginContextListener`, I think another change needs to be made:
```
	@Override
	public void contextDestroyed(ServletContextEvent servletContextEvent) {
		ServletContext servletContext = servletContextEvent.getServletContext();

		ServletContextClassLoaderPool.unregister(
			servletContext.getServletContextName());

		portalDestroy();
	}
```
Not sure why `ClassLoaderPool.unregister` was put before `portalDestroy()`, but for the `ServletContextClassLoaderPool` case, since `portalDestroy()` dispatches the un-deploy event to listeners, which may contain code that looks up the pool, the `unregister()` has to happen after `portalDestroy()`.

**Comment by tinatian** [comment]
@dantewang 
Can you skip registering/unregistering in CustomServletContextHelper by checking if this is a WAR or not?

Tina

**Comment by dantewang** [comment]
@tinatian 
I didn't find any useful way from `Bundle` related API.

However, currently `ServletContextHelperRegistrationImpl` uses [existence of `WEB-INF` directory](https://github.com/liferay/liferay-portal/blob/master/modules/apps/static/portal-osgi-web/portal-osgi-web-servlet-context-helper-impl/src/main/java/com/liferay/portal/osgi/web/servlet/context/helper/internal/ServletContextHelperRegistrationImpl.java#L71) to determine whether it's a generated WAB.

It seems that `WEB-INF` directory is not a must for a WAR file according to the Servlet Spec. There can be a WAR file that only contains HTML/JSP/etc. in its root dir. Does Liferay support deploying that kind of WAR? If not, we can go this way with very simple changes (see https://github.com/dantewang/liferay-portal/pull/790/commits/1019b6c25f52c8535ccbb27c80b28b05570278ef).

Another way can be appending info to, e.g. MANIFEST.MF, when generating the WAB, and retrieve it later.

**Comment by daviddotzhang** [comment]
@dantewang @tinatian, could you prioritize the pull request, this is a customer-related one.

**Comment by dantewang** [comment]
@daviddotzhang The change is relatively big which affects many parts in the Portal, and I'm working on it to make sure nothing is broken.

**Comment by daviddotzhang** [comment]
@dantewang  got it, thanks!

**Comment by dantewang** [comment]
@daviddotzhang By the way, if you're following up the customer ticket about LCSUtil ClassNotFound when one cluster node shuts down, which I've talked about with Emma/Vincent, you can either provide the customer with a temp patch with the first 4 commits in this PR, or investigate what LCS does -- we think it's wrong that LCS sends a cluster message when its context is being destroyed.

**Pull request closed without merging**
