### PR TITLE
LPS-145050

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,
Thanks for debugging with me together.
This is to fix the isPetra logic issue because Attribute containKey() method was misused.

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
@vicnate5 Hi Victor, 
This is the same PR that had some unique failure [Cor-Infra#251](https://github.com/liferay-core-infra/liferay-portal/pull/251#issuecomment-1023523882)
The issue should be gone now 🥳 
Could you please help us scan the result again?
Thank you!

**Comment by vicnate5** [comment]
ci:test:tango-analytics-cloud

**Comment by vicnate5** [comment]
@julschong The previous issue with PDF processor is resolved. However, there is a new regression:

`java.lang.NoClassDefFoundError: com/liferay/portal/kernel/module/util/SystemBundleProvider` in [com.liferay.counter.test.CounterLocalServiceTest](https://testray.liferay.com/home/-/testray/case_results/1605316748)

Some analytics cloud tests also uniquely failed, but it could be a random issue. I am not sure how to run them locally, so I am just re-running on CI.

**Comment by julschong** [comment]
@vicnate5 Hi Victor, I'll try to run that integration test and see what happens. 
update 1/31 5pm: I can duplicate the error locally, I will try to find out what is going on :dango:

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by vicnate5** [comment]
@koor4356 Can you check the new results here? 

See previous issues 
https://github.com/liferay-core-infra/liferay-portal/pull/251#issuecomment-1023523882
https://github.com/tinatian/liferay-portal/pull/2502#issuecomment-1026157938

**Comment by koor4356** [comment]
okay, thanks

**Comment by koor4356** [comment]
ci:test:bundles

**Comment by koor4356** [comment]
ci:test:bundle

**Comment by koor4356** [comment]
@julschong @tinatian, @vicnate5  
It looks good. I am not seeing anything new or previous issues. 
Thanks!

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/296

**Pull request closed without merging**
