### PR TITLE
[portal-impl-integration] LPS-98490 Migrate LayoutTestUtil to module layout-test-util

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This is in preparation of moving com.liferay.portal.util tests. I decide to create a separate ticket because 1) many files need to be modified to apply this change; 2) there are several classes in portal-test-integration depending on LayoutTestUtil, not sure how long it takes to move them out.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

**Comment by tinatian** [comment]
Hi @dantewang,
This pull itself looks weird, you deprecate a class but also leave some usages of the deprecate class. Generally we remove all the usages then deprecate.

I know it may be a big pull, but it is inevitable, in the case separating a large pull makes people confused, we prefer the large pull to avoid unnecessary misunderstanding.

Please resend.

Thanks.
Tina.

**Comment by tinatian** [comment]
@dantewang 
I can not remember the reason we have to move out LayoutTestUtil if there are still other classes in portal-test-integration depending on it. If we really want to move it out, we have n to move out the dependent classes first, then this one.

Tina.

**Pull request closed without merging**
