### PR TITLE
[portal-impl-integration] LPS-93519 Move upgrade related tests

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
ci:test:backend

**Comment by tinatian** [comment]
@dantewang  Please rebase and resend.

Thanks!
Tina

**Pull request closed without merging**
