### PR TITLE
[portal-impl-integration] LPS-95019 UserGroupServiceTest

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Moved to user-groups-admin-test module since UserGroupLocalServiceTest is already there.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7751

**Comment by tinatian** [comment]
@dantewang 
I did not include this commit: LPS-95019 Extract to constant to make it more clear.
The reason is they should not be constant cause the value of them depends on the number of groups you add in the loop before it. It is better we keep it as before so that people can figure out the relation between them quickly.

Tina.

**Pull request closed without merging**
