### PR TITLE
LPS-84417 Assert listener before/after reconfigure

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian I added logic to try to assert:

1. Aggregate listener is added into the new Ehcache
2. Listener registered by code is kept untouched
3. Listener can be configured by configuration file

However, for 3, **it doesn't work now**, for two reasons:

1. `EhcachePortalCacheManager.reconfigurePortalCaches` calls the configurator with `_usingDefault` which is `true` if Portal is not started with customized config files; when `_usingDefault` is true, listener configuration provided in the re-config file will be ignored.
2. Even if I force the configurator to parse the `CacheEventListenerFactory` element, `EhcachePortalCacheListenerFactory` will fail to create instance of the factory because `EhcachePortalCacheListenerFactory` uses the class loader that loads itself.

Is this by design, or a bug?

**Comment by tinatian** [comment]
@dantewang 
For 1. yes, this is what it supposes to work. We have this to avoid people modifying the default config file directly, they should create their own config file if they want to modify the configs.
For 2. yes, it is using the same classloader, why this is a problem for you? I do not understand.

**Comment by dantewang** [comment]
@tinatian 
For 1, what I mean is, if the module is initialized with its default config files, then other module trying to reconfig caches won't be able to config listener via the config file it provides. Shouldn't a config file provided by a reconfig module be considered as non-default?

For 2, it will be a problem if the reconfig module tries to declare its own `CacheEventListenerFactory`. `EhcachePortalCacheListenerFactory`'s class loader won't be able to find it.

**Comment by tinatian** [comment]
@dantewang 
1. If you want to support listeners reconfig, there are two options;
a) add the new listener to current listener list 
b) remove all the old ones and only keep the new defined ones?
If you chose to a), then means you are not doing a fully reconfig of listeners, you still can not change the ones in the default file. 
If you chose to b), does it mean if you do not have any listener defined, then you are going to remove all the define in the old ones? this way it will give client more control, but client must be aware of what's in the default one clearly.

2. Yes, it will be. 

I am seeing both of the concerns as limitation of current cache framework, let's just take it as what is it now, and work on the test first. We can do the improvement later.

Tina.

**Comment by dantewang** [comment]
resent at https://github.com/tinatian/liferay-portal/pull/1035

**Pull request closed without merging**
