### PR TITLE
[portal-test-integration] LPS-102160 & LPS-102247

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8308
https://github.com/shuyangzhou/liferay-portal/pull/8307

**Pull request closed without merging**
