### PR TITLE
Lps 125421 2 2 new 1

### PR DESCRIPTION
**Pull request by slnn**
Hi @tinatian 

During the previous talk, I make a make mistake that we can get these generic SQL files that contain create statements, but we need translate them, it be done by this commit https://github.com/tinatian/liferay-portal/commit/06da5b2e4f6ba6ac5c1f248b20dd2bea051560c0

On the other hand, we did not need the additional property like "sample.sql.output.sql.file",  I remove it in this pull.

Lily

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by slnn** [comment]
benchmark side changes please see:https://github.com/tinatian/liferay-benchmark-ee/pull/56

**Comment by tinatian** [comment]
@slnn Please rebase and resend if needed.

Thanks.
Tina.

**Pull request closed without merging**
