### PR TITLE
Lps x finder cache 9

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @slnn @GinsonRen 
Please wait for ci result, if no major issue, please run a diff on this.

Thanks.
Tina.

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test result?

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian Most of the integration test failures are unique
https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/398625/#showFailuresLink

Functional failures are unrelated.

**Comment by GinsonRen** [comment]
@tinatian I just noticed you closed this pull, I already got login and AP result here. Just let me know if I need to continue.
Login:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 3a5d1ed | 15312 | 267 | 65.3 | -
PR | - | 15761 | 235 | 55.3 | 2.93%

AP:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 3a5d1ed | 9071 | 200 | 134 | -
PR | - | 8884 | 200 | 134 | -2.06%

**Pull request closed without merging**
