### PR TITLE
LRQA-53786 | master

### PR DESCRIPTION
**Pull request by kyle-miho**
https://issues.liferay.com/browse/LRQA-53786

### CODE REVIEW

**Comment by kyle-miho** [comment]
Tested here: https://github.com/kyle-miho/liferay-portal/pull/326
but it seems like the integration test may not have run?
cc: @vicnate5

https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/368737/AXIS_VARIABLE=25,label_exp=!master/testReport/

**Comment by tinatian** [comment]
@dantewang, please take over this.

Tina

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
See https://github.com/kyle-miho/liferay-portal/pull/328

**Comment by dantewang** [comment]
ci:close

**Pull request closed without merging**
