### PR TITLE
LPS-128171

### PR DESCRIPTION
**Pull request by julschong**
Hi Tina,

This is rebased from [#9799](https://github.com/shuyangzhou/liferay-portal/pull/9799)
I think this time is finally right!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:sf

**Comment by julschong** [comment]
This PR has been resubmitted to [liferay-core-infra #42](https://github.com/liferay-core-infra/liferay-portal/pull/42)

**Pull request closed without merging**
