### PR TITLE
[deprecation round2] LPS-103869 portal-kernel part 2

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://issues.liferay.com/browse/LPS-103869

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian Previous test result: https://github.com/dantewang/liferay-portal/pull/1394#issuecomment-552353131

@vicnate5 Could you take a look at the test results? This pull contains some changes that may affect html elements on some pages.

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
Reviewing, going to take a little longer because Testray is currently having issues.

**Comment by vicnate5** [comment]
@dantewang @tinatian Looks good.

**Comment by tinatian** [comment]
Hi @dantewang  @yuhai ,

Please see https://github.com/shuyangzhou/liferay-portal/pull/8528.

I did not include the last two commits, reason is that list.jsp file is actually used by multiple places, where the property is going to use. We should only remove it after all the real usages are migrated to use the lexicon one, which needs to update the front UI. Let's hold on this and revisit after we finished the easier ones and still have time to work on deprecation.

Tina.

**Pull request closed without merging**
