### PR TITLE
LPS-125170 Take isolation level when resuming queued tasks | 01-05

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Currently the BackgroundTaskExecutorRegistry does not know executors from war plugins, so we switched back to lockKey and used a separate commit to make it clear. The registry part is more of a design/infrastructure issue or tech debt, and Hai will try to do some refactoring.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang @yuhai 
If `BackgroundTaskExecutorRegistry` has an issue then `BackgroundTaskLockHelper#getLockKey` won't work either. Please add test to expose that issue and fix it first then resend this pull.

Thanks.
Tina.

**Pull request closed without merging**
