### PR TITLE
[deprecation] LPS-103202 portal-impl

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
Hi @vicnate5 Could you review the test result when CI finishes? Thanks!

For reference, the CI result yesterday: https://github.com/dantewang/liferay-portal/pull/1337#issuecomment-542211230

**Comment by vicnate5** [comment]
@dantewang Potential unique failure in `com.liferay.portal.tools.PortalClientBuilderTest.testPortalClientBuilder` https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/342281/AXIS_VARIABLE=0,label_exp=!master/consoleText as I do not see this at head.

However, this does not occur on https://github.com/dantewang/liferay-portal/pull/1337#issuecomment-542211230, so it should be safe to assume a fluke or unrelated if nothing changed between these pulls.

Other failures not related.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8397

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8400

**Pull request closed without merging**
