### PR TITLE
Lps 135570 test

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:clustering

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test result?

Thanks.
Tina.

**Comment by vicnate5** [comment]
ci:test:clustering

**Comment by vicnate5** [comment]
@tinatian On this PR, One of the cluster session replication tests is failing due to https://issues.liferay.com/browse/LPS-99796. I am OK treating this as a separate issue. The basic session replication is working.

**Pull request closed without merging**
