### PR TITLE
LPS-72054 Found one more key in master

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian 
The new key is in
```
apps:web-experience:layout:layout-admin-web
```

### CODE REVIEW

**Comment by tinatian** [comment]
@dantewang @ChiZelin Could you please try to add a test either integration test or unit test, so that we do not need to maintain this manually. Next time if someone add new portlet and new keys but forget to add localization, it will fail the test.

We did same thing for localization of configuration files, please see changes of this ticket for more details: https://issues.liferay.com/browse/LPS-75199

Thanks.
Tina.

**Comment by dantewang** [comment]
@tinatian 
Back when we first worked on LPS-72054, Preston sent us an integration test, finding all the missing titles from all the deployed portlets. See https://github.com/dantewang/liferay-portal/pull/422

We didn't check in this test at that moment mainly because on CI we also deploy private modules so that the test case still fails even if all portlets in master are fixed.

Also, this test looks for missing keys from all deployed portlets, and in test environment there are some test portlets that don't need the title key. On CI, it will show 3 extra portlets used by other tests. I'm thinking of providing a white-list for the test case, or is there any Liferay-preferred practice?

Thanks

**Comment by tinatian** [comment]
@dantewang Do not use white list, fix the test portlet so that it will follow same rule as a normal portlet.

**Comment by tinatian** [comment]
@dantewang You can work on the test first, and we can check it in and ignore it on CI. After you fix all the failures, we enable it. If someone else broke it later, then it would be his responsibility to fix his code.

Tina.

**Pull request closed without merging**
