### PR TITLE
[SampleSQLBuilder] LPS-113497 Content page homepage 5-11

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang @slnn  Is it possible to avoid adding those json files?

Tina

**Comment by slnn** [comment]
Hi @tinatian 

I will try it, but I think it is hard as I have confirmed with Pavel if we did not use these json files that came from DB, then SampleSQLBuilder needs some runtime of portal such as *LocalService.java

**Comment by slnn** [comment]
After https://issues.liferay.com/browse/LPS-117064, SampleSQLBuilder can not use fragment API as it depends on local services

**Comment by tinatian** [comment]
@slnn What kind of dependency fragment API has? Any exceptions when you use it SampleSQLBuilder?

Tina

**Comment by slnn** [comment]
Hi @tinatian 

Before LPS-11704, we can use this method to generate the json in java code instead of using default-homepage-layout-definition.json which decided which fragment component be put on the home page,  unfortunately, this way we still need these *_configuration.json and *_editValue.json for each fragment component.

After LPS-11704, the generation will be failed by some exception (sorry, I can not remember exactly exception, but I am sure here will be failed)

```
private LayoutStructure _generateJsonData(
		LayoutStructure layoutStructure, LayoutModel layoutModel,
		List<FragmentEntryLinkModel> fragmentEntryLinkModels) {

		//Generate the first Container in the home page
		String parentItemId = layoutStructure.getMainItemId();

		ContainerLayoutStructureItem containerLayoutStructureItem1 =
			(ContainerLayoutStructureItem)
				layoutStructure.addContainerLayoutStructureItem(
					parentItemId, 0);

		containerLayoutStructureItem1.setBackgroundImageJSONObject(
			JSONUtil.put(
				"title", _BACKGROUND_PICTURE_TITLE
			).put(
				"url", _BACKGROUND_PICTURE_URL
			));

		containerLayoutStructureItem1.setAlign(null);
		containerLayoutStructureItem1.setBorderColor(null);
		containerLayoutStructureItem1.setBorderRadius("");
		containerLayoutStructureItem1.setBorderWidth(0);
		containerLayoutStructureItem1.setContentDisplay("block");
		containerLayoutStructureItem1.setJustify("");
		containerLayoutStructureItem1.setMarginBottom(0);
		containerLayoutStructureItem1.setMarginLeft(0);
		containerLayoutStructureItem1.setMarginRight(0);
		containerLayoutStructureItem1.setMarginTop(0);
		containerLayoutStructureItem1.setOpacity(100);
		containerLayoutStructureItem1.setPaddingBottom(8);
		containerLayoutStructureItem1.setPaddingLeft(0);
		containerLayoutStructureItem1.setPaddingRight(0);
		containerLayoutStructureItem1.setPaddingTop(8);
		containerLayoutStructureItem1.setShadow("");
		containerLayoutStructureItem1.setWidthType("fluid");

		//Generate the login portlet in the first Container of the home page

		for (FragmentEntryLinkModel fragmentEntryLinkModel :
				fragmentEntryLinkModels) {

			String rendererKey = fragmentEntryLinkModel.getRendererKey();

			if (rendererKey.equals("") &&
				(fragmentEntryLinkModel.getPlid() == layoutModel.getPlid())) {

				layoutStructure.addFragmentLayoutStructureItem(
					fragmentEntryLinkModel.getFragmentEntryLinkId(),
					containerLayoutStructureItem1.getItemId(), 0);

				break;
			}
		}

		//Generate second Container in the home page

		parentItemId = containerLayoutStructureItem1.getItemId();

		ContainerLayoutStructureItem containerLayoutStructureItem2 =
			(ContainerLayoutStructureItem)
				layoutStructure.addContainerLayoutStructureItem(
					parentItemId, 1);

		JSONObject jsonObject2 = JSONFactoryUtil.createJSONObject();

		containerLayoutStructureItem2.setBackgroundImageJSONObject(jsonObject2);

		containerLayoutStructureItem2.setAlign(null);
		containerLayoutStructureItem2.setBorderColor(null);
		containerLayoutStructureItem2.setBorderRadius("");
		containerLayoutStructureItem2.setBorderWidth(0);
		containerLayoutStructureItem2.setContentDisplay("block");
		containerLayoutStructureItem2.setJustify("");
		containerLayoutStructureItem2.setMarginBottom(0);
		containerLayoutStructureItem2.setMarginLeft(0);
		containerLayoutStructureItem2.setMarginRight(0);
		containerLayoutStructureItem2.setMarginTop(0);
		containerLayoutStructureItem2.setOpacity(100);
		containerLayoutStructureItem2.setPaddingBottom(0);
		containerLayoutStructureItem2.setPaddingLeft(3);
		containerLayoutStructureItem2.setPaddingRight(3);
		containerLayoutStructureItem2.setPaddingTop(0);
		containerLayoutStructureItem2.setShadow("");
		containerLayoutStructureItem2.setWidthType("fixed");

		//Generate fragment components on home page
		FragmentLayoutStructureItem fragmentLayoutStructureItem = null;

		for (FragmentEntryLinkModel fragmentEntryLinkModel :
				fragmentEntryLinkModels) {

			String rendererKey = fragmentEntryLinkModel.getRendererKey();

			if (rendererKey.equals(_HEADING_RENDER_KEY) &&
				(fragmentEntryLinkModel.getPlid() == layoutModel.getPlid())) {

				fragmentLayoutStructureItem =
					(FragmentLayoutStructureItem)
						layoutStructure.addFragmentLayoutStructureItem(
							fragmentEntryLinkModel.getFragmentEntryLinkId(),
							containerLayoutStructureItem2.getItemId(), 0);
			}
			else if (rendererKey.equals(_PARAGRAPH_RENDER_KEY) &&
					 (fragmentEntryLinkModel.getPlid() ==
						 layoutModel.getPlid())) {

				fragmentLayoutStructureItem =
					(FragmentLayoutStructureItem)
						layoutStructure.addFragmentLayoutStructureItem(
							fragmentEntryLinkModel.getFragmentEntryLinkId(),
							containerLayoutStructureItem2.getItemId(), 1);
			}
		}

		return layoutStructure;
	}
```

**Comment by dantewang** [comment]
@tinatian The fragment APIs internally call various local services, which are only available in portal runtime. This happened in the past and since then we had to put the json files dumped from database in SampleSQLBuilder.

**Comment by tinatian** [comment]
@dantewang @slnn "The fragment APIs internally call various local services", I would like to know what kind of local services that would be, most likely they should not have the dependencies in API modules. It should be fixed in the API modules, not in SampleSQLBuilder.

**Comment by dantewang** [comment]
@tinatian I found this from the slack chat history with Lily:

```
[java] Caused by: java.lang.NoClassDefFoundError: org/osgi/framework/FrameworkUtil
     [java] 	at com.liferay.fragment.service.FragmentEntryLinkLocalServiceUtil.<clinit>(FragmentEntryLinkLocalServiceUtil.java:818)
     [java] 	at com.liferay.layout.util.structure.FragmentStyledLayoutStructureItem.setFragmentEntryLinkId(FragmentStyledLayoutStructureItem.java:93)
     [java] 	at com.liferay.layout.util.structure.LayoutStructure.addFragmentLayoutStructureItem(LayoutStructure.java:208)
     [java] 	at com.liferay.portal.tools.sample.sql.builder.DataFactory._generateJsonData(DataFactory.java:4610)
     [java] 	at com.liferay.portal.tools.sample.sql.builder.DataFactory.newLayoutPageTemplateStructureRelModel(DataFactory.java:2770)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [java] 	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1505)
     [java] 	at freemarker.ext.beans.ReflectionCallableMemberDescriptor.invokeMethod(ReflectionCallableMemberDescriptor.java:56)
     [java] 	at freemarker.ext.beans.MemberAndArguments.invokeMethod(MemberAndArguments.java:51)
     [java] 	at freemarker.ext.beans.OverloadedMethodsModel.exec(OverloadedMethodsModel.java:61)
     [java] 	... 32 more
     [java] Caused by: java.lang.ClassNotFoundException: org.osgi.framework.FrameworkUtil
     [java] 	at org.apache.tools.ant.AntClassLoader.findClassInComponents(AntClassLoader.java:1388)
     [java] 	at org.apache.tools.ant.AntClassLoader.findClass(AntClassLoader.java:1337)
     [java] 	at org.apache.tools.ant.AntClassLoader.loadClass(AntClassLoader.java:1095)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

`FragmentStyledLayoutStructureItem`, which is in layout-api, uses `FragmentEntryLinkLocalServiceUtil` from fragment-api to fetch a `FragmentEntryLink` object using given `fragmentEntryLinkId` in `FragmentStyledLayoutStructureItem#setFragmentEntryLinkId(long)`.

**Pull request closed without merging**
