### PR TITLE
[Log4J] LPS-125548 Clean up unnecessary Log4J API usage

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian

Only `UncompressUtil` is modified. It originally uses Log4J 2 API (which is compileIncluded by the ES7 module, maybe as ElasticSearch dependency), but it runs inside portal.

For other classes, as @ChiZeLin states:

1. `com.liferay.portal.search.elasticsearch7.internal.util.SearchLogHelperImpl` configures the logging level of `org.elasticsearch.client.RestClient` which uses commons-logging managed Log4J.
2. `com.liferay.portal.output.stream.container.internal.OutputStreamContainerFactoryTrackerImpl` injects a custom `Appender` which is for custom output destinations of `UpgradeProcess`es.
3. `com.liferay.portal.tools.PluginsEnvironmentBuilder` is a tool only executed by an Ant target to generate Eclipse related project files, and it does not use Log4J API, but just appends "log4j.jar" to a classpath it builds.

Leon also found

4. `com.liferay.portal.search.elasticsearch7.internal.sidecar.ElasticsearchServerUtil` uses Log4J 2 API and runs inside the sidecar process so it's irrelevant to our Log4J version upgrade.

All other Log4J usages are either in the Log framework or test utils related.

Especially for `com.liferay.portal.test.log.Log4JLoggerTestUtil` usages, since its method takes Log4J's `Level` as parameter, all tests using it needs to import that class. Do you think we should modify this to avoid using `Level`? (UPDATE) and also `LoggingEvent`?

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9726

**Pull request closed without merging**
