### PR TITLE
LPS-112055 merge PortletResourceActionsBag and ModelResourceActionsBag

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:reopen

**Comment by tinatian** [comment]
@dantewang Please see https://github.com/dantewang/liferay-portal/pull/1607.
Can you check if we have corresponding usages need to change?

**Pull request closed without merging**
