### PR TITLE
LPS-86616 Error message when configuring virtual instance with IPV6

### PR DESCRIPTION
**Pull request by pei-jung**
Hi Tina,

Can you review this? This is a continuation of Sam's work on the ticket before (see https://github.com/tinatian/liferay-portal/pull/1148). 

Thanks\!

/cc @drewbrokke @alee8888

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by pei-jung** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@pei-jung 
Could you please add corresponding test to cover your changes? The logic of dealing ip address is kind of mess, and it is hard to tell what the expected behavior, by adding a test, we can easily track back when something is wrong.

Thanks.
Tina.

**Comment by pei-jung** [comment]
Sure, I'll add test coverages and resend.

**Pull request closed without merging**
