### PR TITLE
[deprecation] LPS-106315 remove SingleVMPoolUtil and MultiVMPoolUtil

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Test results are good.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8699

**Pull request closed without merging**
