### PR TITLE
LPS-112282 Add SparseBitSet as poi needs

### PR DESCRIPTION
**Pull request by dantewang**
New version of poi needs SparseBitSet on the classpath.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/tinatian/liferay-portal/pull/1808

**Pull request closed without merging**
