### PR TITLE
MainServlet

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:backend

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by zhangyan0701** [comment]
Unique failures of ci:test:default are unrelated:

1. functional-smoke-websphere90-mysql57-jdk8/0: https://issues.liferay.com/browse/LPS-115835
2. functional-tomcat90-mysql57-jdk8/125: https://issues.liferay.com/browse/LRQA-56772

**Comment by tinatian** [comment]
@dantwang Please send me a pull about this with detailed explanations why we make this change.

Thanks.
Tina.

**Pull request closed without merging**
