### PR TITLE
[Bug fix] LPS-120742

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian No regressions found in test results.

**Comment by tinatian** [comment]
@dantewang Please update to the latest version of 9 ( 9.4.38.v20210224) and resend.

Thanks.
Tina.

**Comment by dantewang** [comment]
@tinatian jetty-server 9.4.38.v20210224 is not compatible with 9.3.x version -- the `AbstractSessionManager` is removed and seems to be replaced by another class. Updating to 9.4.38 will cause a major version bump in `com.liferay.portal.servlet` because `JettyHttpSessionWrapper` and `JettySharedSessionWrapper` implement `AbstractSessionManager.SessionIf`. Removing these two deprecated classes will also cause a major version bump.

**Pull request closed without merging**
