### PR TITLE
LPS-143420

### PR DESCRIPTION
**Pull request by julschong**
Hii Tina, @tinatian 

This is to follow up Victor's cooment about the unit tests in [liferay-core-infra #98](https://github.com/liferay-core-infra/liferay-portal/pull/98#issuecomment-1000460319)

I was able to make them pass after using ReflectTestUtil.setFieldValue() as we discussed

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test

**Comment by julschong** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/143

**Pull request closed without merging**
