### PR TITLE
[portal-test-integration] LPS-102243 12-17

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian TestDB is only used by the *SQLTransformerTests, which are in portal-impl. The one that is used by DXP DB support modules is BaseDBTestCase.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5 Could you please help scan the result?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Test results look good.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8634

**Pull request closed without merging**
