### PR TITLE
[bug fix] LPS-89569

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Added a try-catch as discussed. I tested manually:

1. Start 2 nodes simultaneously 
  - No exception during startup
2. Run the following Groovy script in `Server Administration - Script`
  - No exception, got class name output

```
out.println(com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.getOSGiServiceIdentifier());
```

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
@tinatian Failures seem to be upstream, 10 passed in a previous run: https://github.com/dantewang/liferay-portal/pull/1081#issuecomment-481103782

**Comment by vicnate5** [comment]
Confirmed, the failures are not related to clustering.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7653

**Pull request closed without merging**
