### PR TITLE
[portal-impl-integration] LPS-93010 com.liferay.portal.security.permission tests | 2

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@tinatian A compile failure in portal-aop-test is preventing CI from running the tests I moved. I ran those locally and they passed.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7566

**Pull request closed without merging**
