### PR TITLE
Lps 119013 lps 118633

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@GinsonRen Please run a diff. Please run login first, and if you see a huge regression, then no need to run others.

Thanks.
Tina.

**Comment by GinsonRen** [comment]
@tinatian There is -3.05% regression on login. Here is the result:
Login:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | ec7f95b4 | 44,102 | 270 | 81 | -
PR-1936 | - | 42755 | 257 | 76.4 | -3.05%

**Pull request closed without merging**
