### PR TITLE
LPS-82603

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-82603

https://github.com/tinatian/liferay-portal/pull/971

Since you wanted us to remove the synchronized block, I decided it would make sense to allow for the race condition, since the worst case is that it will wait for the full timeout. This is implemented without a map, and only runs the code if we're trying to get the cluster node ID for the master node.

To minimize the potential wait time in tests, the time unit has been changed to milliseconds, and the test timeout is smaller than the default timeout.

From @ericyanLr : 

> ## Brief Summary
> As discussed, this fix now consists of using synchronized blocks and CompletableFuture, so that:
> 
> 1. If a ClusterNode is not found, create a future
> 2. Introduce a timeout for the future, to avoid the no-delay loop
> 3. If a valid ClusterNode is found, complete the future so it will not have to wait the entire timeout

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@holatuwol @ericyanLr 
Please see my changes here : https://github.com/shuyangzhou/liferay-portal/pull/6608

There are two problems with this pull:
1) _masterNodeCompletableFuture needs to be volatile
2) if I do memberJoined(AddressA), and I see _masterNodeCompletableFuture is null, I do nothing.
Meantime someone is do getClusterNode(AddressA), and it has passed the loop below and create a future, then no one is going to set value to that future, and we are going to retry forever.
`              for (ClusterNodeStatus clusterNodeStatus :
				_clusterNodeStatuses.values()) {
			if (address.equals(clusterNodeStatus.getAddress())) {
				return clusterNodeStatus.getClusterNode();
			}
		}`

**Comment by holatuwol** [comment]
@tinatian Yes, what you described in (2) was the race condition mentioned in my first comment. If you accept the idea that the race condition isn't harmful, then you don't need to declare it as volatile, either, and (1) was a non-issue.

I feel as though ConcurrentHashMap.computeIfAbsent isn't much better than synchronizing on the map due to [JDK-8161372](https://bugs.openjdk.java.net/browse/JDK-8161372), but if that's what you trying to get us to do in the previous pull requests, I'll keep that in mind for next time.

**Comment by tinatian** [comment]
Hi @holatuwol 
If the address of coordinator is not changed at runtime, the race condition is not harmful.

The problem is the coordinator may change.
1) In thread 1, you are invoking getClusteNode(AddressA), and you see it is not in the map, and you check if this is a master address, support at this moment AddressA is master, you create a future and wait for result
2) In thread 2, memberJoined(AddressB), and you check if it is a master address, suppose at this moment AddressB is master, you will check if the future and set it.
3) the wait on thread 1 will be stopped, and return the cluster node of addressB, but in fact you are asking for cluster node of AddressA

At function level, this may not have any side effect, since you are getting the updated master cluster node, even if this is not you are asking for originally. 

From API point of view, this does not make sense to me. If you are exposing a method named like getMasterClusterNode() rather than getClusterNode(Address), I think it would make more sense to me.

I do not want to always keep in mind that we have this kind of implicit side effect, so I think it would be better to use a map, so that it would be clear and easy to maintain in future.

The old way is you are synchronizing two maps, this is what I want to avoid. I think we can do this with only one map and this way we do not need synchronizing.

For the JDK issue you are talking about, I did not know this. Thanks for letting me know, I will check and see if we have a better solution.


Tina

**Comment by tinatian** [comment]
@holatuwol Also, I think volatile is needed, or else even if someone is creating a new future and waiting on, another thread may not see it, the waiting may be forever.

**Comment by tinatian** [comment]
Hi @holatuwol,
For the JDK bug you are talking about, it is going to be slow when you are using the same key and checking. So compared to synchronizing, the performance should also be better, since synchronze will be slow for every key, not only the same key.
I am going to keep my current implementation, if you have more question, please feel free to let me know.

Tina.

**Pull request closed without merging**
