### PR TITLE
[Bug fix] LPS-115034

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian We decided to add the limitation protection to the ConfigurationModelListener mainly because the error message can be i18ned and automatically shown on the page. It's also a common pattern in portal.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:sf  Force pushed for SF

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang @ChiZelin I am confused about this pull. The issue is that you can not set a value twice, and your fix is just to add a limitation. 
What if I do:
Set the value to 204800
Set the value to 204801
What would happen?

Tina

**Pull request closed without merging**
