### PR TITLE
Jasper 2020-03-27

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Still looking into the long `ant all` time issue.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang give it 4 hours, if still no clue, move on to other tasks.

Tina.

**Comment by dantewang** [comment]
@tinatian Got it.

I've identified the issue with CPU sampling but havn't figured out the cause. The issue is the logger for Tomcat Jasper is somehow set at DEBUG level, and each debug log needs a stack trace created. CPU sampling shows almost all CPU time in the stack trace creation. This is happening in Tomcat's code. Not sure why DEBUG is enabled for it...

**Comment by dantewang** [comment]
ci:stop

**Pull request closed without merging**
