### PR TITLE
LPS-138776

### PR DESCRIPTION
**Pull request by ghost**
Hi @tinatian,

this is the PR for [LPS-138776](https://issues.liferay.com/browse/LPS-138776) as we discussed.

When starting Gogo shell from a local telnet session, `disconnect` did not return the usual confirmation response. This was caused by [this bug in `org.eclipse.equinox.console`](https://git.eclipse.org/c/equinox/rt.equinox.bundles.git/commit/bundles/org.eclipse.equinox.console?id=3efe80718c250997669591eef197580148b2f47c).

The related libraries were updated and patched when necessary. The old `.patch` files of `org.apache.felix.gogo.runtime` were not compatible with the new version so a new `.patch` file was generated which contains all their changes.

Thank you!

### CODE REVIEW

**Comment by ghost** [comment]
ci:test:sf

**Comment by ghost** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Failures not related

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10296

**Pull request closed without merging**
