### PR TITLE
[Throughput Testing] PTR-111 Change default value articleViewPermissionsCheckEnabled to true

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Hi @tinatian 

In JournalArticle, by default, view permissions are ignored due old throughput reasons (see [LPS-1445](https://issues.liferay.com/browse/LPS-1445) ). 
We think that throughput issues are related to old permission algorithm and perhaps are already solved in master branch.

As part of [PTR-111](https://issues.liferay.com/browse/PTR-111) analysis, we want to changing this behaviour and check JournalArticle view permissions by default (`articleViewPermissionsCheckEnabled=true`).
We will allow customers to leave original behavior setting this check to false.

In order to check this change is feasible, we have to analyze throughput issues after activating this feature.
Can you execute throughput testings after changing this setting?

Thank you

/cc: @ealonso @juliocamarero @dacousalr

**Note:** This change must be sent to Journal subrepo, but I am sending it to liferay-portal for convenience. I will take care about correct pull request after executing throughput tests.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:reopen

**Comment by tinatian** [comment]
@tomwang2011 Could you please run web content test with this change?

cc @shuyangzhou

Tina.

**Comment by tomwang2011** [comment]
Hi Jorge, I noticed a slight drop (1.6%) for this change, thanks!

**Comment by tinatian** [comment]
@jorgediaz-lr To confirm the result Tom run, I will ask our China Team to run it again.

@slnn @dantewang Could you please rerun web content test with changes in this pull? Please also run login test if you have time.


Thanks.
Tina.

**Comment by slnn** [comment]
OK, got it.

@dantewang @tinatian

**Comment by slnn** [comment]
Hi all,

Here are test results of Login and Web Content, from test results I did not see big regression on them.

Login

Portal Version | Session Count | Mean Time of Login | Mean Time of Log out
------------ | ------------- | ------------- | -------------
BaseLine | 26643 | 225 |62
PR | 26565 | 222|60.6


Web Content:

Portal Version | Session Count | Mean Time of Login | Mean Time of View Page
------------ | ------------- | ------------- | -------------
BaseLine | 33077 | 508 | 180
PR | 33076 | 497 | 177


Regards
Lily

**Comment by tinatian** [comment]
Hi @jorgediaz-lr, 

According to the results, it should be OK to make this change. I am going to close this pull.

cc @shuyangzhou

Thanks.
Tina.

**Comment by jorgediaz-lr** [comment]
Thank you @tinatian we will create a LPS and implement it

**Comment by jorgediaz-lr** [comment]
For the record, this change will be implemented in https://issues.liferay.com/browse/LPS-73847

**Pull request closed without merging**
