### PR TITLE
[SampleSQLBuilder] LPS-74148 consistency: Commerce

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9286

**Comment by tinatian** [comment]
Hi @slnn @dantewang ,
I think you should be able to remove initCommerceIds().

1) List<CPInstanceModel> CPInstanceModels = newCPInstanceModels()
2) List<CProductModel> CProductModels = newCProductModels(CPInstanceModels)
3) List<CPFriendlyURLEntryModel> CPFriendlyURLEntryModels = newCPFriendlyURLEntryModels(CProductModels)
4) List<CPDefinitionModel> CPDefinitionModels = newCPDefinitionModels(CPInstanceModels, CProductModels)
5) List<CPDefinitionLocalizationModel> CPDefinitionLocalizationModels = newCPDefinitionLocalizationModels(CPDefinitionModels)
6) List<AssetEntryModel> AssetEntryModels = newCPDefinitionAssetEntryModels(CPDefinitionModels)

It needs a lot of changes, I am not sure if this is worthy depending on if you can separate current logic into different classes. If you can move commerce logic into different class with current code, then it is better we do not change it.

Tina.

**Comment by slnn** [comment]
Hi @tinatian 

Finally, the DataFactory will be separated into different classes in this pull https://github.com/dantewang/liferay-portal/pull/1678

Regards
Lily

**Comment by slnn** [comment]
Based on currently way, the initCommerceIds() will be moved to BaseDataFactory, however, it will be extended by all *DataFactory, I will try to remove the initCommerceIds() to avoid nonCommerceDataFactory extend the method.

**Pull request closed without merging**
