### PR TITLE
Lps 122190 lps 122225 5

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@GinsonRen Please run a diff on benchmark test cases, run login first, and if you see a big regression, no need to run others, please try to finish this by end of your Monday.

Thanks.
Tina.

**Comment by GinsonRen** [comment]
@tinatian Here is the result except AP, I am going to update AP result tomorrow morning. There is -5.68% regression on MB, do I need re-run it or run profile for it?

Login:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 44c022b894f | 38965 | 265 | 78 | -
PR-2004 | - | 38743 | 264 | 78 | -0.57%



WC:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 44c022b894f  | 53250 | 559 | 167 | -
PR-2004 | - | 51926 | 742 | 219 | -2.49%

MB:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 44c022b894f  | 16597 | 70.5 | 116 | -
PR-2004 | - | 15655 | 353 | 119 | **-5.68%**

Blog:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 44c022b894f  | 14174 | 49.5 | 128 | -
PR-2004 | - | 14150 | 581 | 138 | -0.17%

DL:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 44c022b894f  | 24284 | 223 | 318 | -
PR-2004 | - | 24036 | 211 | 306 | -1.02%

Wiki:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 44c022b894f  | 14035 | 239 | 532 | -
PR-2004 | - | 13765 | 250 | 458 | -1.92%

**Comment by tinatian** [comment]
No, thanks @GinsonRen!

**Comment by tinatian** [comment]
@GinsonRen I updated the pull, please run MB and WC again.

FYI @dantewang
Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Rebase at https://github.com/tinatian/liferay-portal/pull/2006

**Pull request closed without merging**
