### PR TITLE
LPS-108588

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
ci:test:bundle

**Comment by tinatian** [comment]
FYI @achaparro

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result?

Thanks
Tina

**Comment by vicnate5** [comment]
Integration test issue from https://github.com/tinatian/liferay-portal/pull/1829#issuecomment-631646768 is still present here:

Example:
https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/394031/AXIS_VARIABLE=14,label_exp=!master/testReport/junit/com.liferay.exportimport.internal.content.processor.test/DefaultExportImportContentProcessorTest/testDeleteTimestampFromDLReferenceURLs/

**Comment by tinatian** [comment]
Fix integration tests here https://github.com/tinatian/liferay-portal/pull/1837

**Pull request closed without merging**
