### PR TITLE
[Bug] LPS-95099 Clear timer threads after shutting down module framework

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test

Liferay Continuous Integration <notifications@github.com> 于 2019年6月3日周一
16:37写道：

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
@vicnate5 Could you take a look at the results once it finishes? Thanks!

**Comment by vicnate5** [comment]
@dantewang test failures not related.

**Comment by dantewang** [comment]
@vicnate5 Thank you!

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7866

**Pull request closed without merging**
