### PR TITLE
[Bug fix] LPS-129172 Jackson

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:reevaluate:1127401_5028

**Comment by zhangyan0701** [comment]
Comparation with acceptance upstream:
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1557847995&testrayRunIdA=1557523859&statusB=2

The failed functional tests are unrelated.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10251

**Pull request closed without merging**
