### PR TITLE
[Bug Fix] LPS-132693

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian According to OSGi Spec Ch.4.4.16 (http://docs.osgi.org/specification/osgi.core/7.0.0/framework.lifecycle.html#i3264631) as well as Ch.701.5 (http://docs.osgi.org/specification/osgi.core/7.0.0/util.tracker.html#d0e52320), a bundle should use its own bundle context for operations like tracking services.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10067

**Pull request closed without merging**
