### PR TITLE
LPS-96877 No need to check restricted classes for unrestricted templates in FreeMarker and Velocity

### PR DESCRIPTION
**Pull request by topolik**
/cc @lipusz

### CODE REVIEW

**Comment by topolik** [comment]
ci:test:relevant

**Comment by topolik** [comment]
ci:test:sf

**Comment by lipusz** [comment]
Hi Tomas @topolik 

I've just pushed an extra commit to fix the LOWT failures in https://github.com/lipusz/liferay-portal/commit/a47cdbcca5d49d91c8998d07a64933569a1aaf37.

Can you please include that commit too?

Thanks a lot!

**Comment by topolik** [comment]
Please see https://github.com/lipusz/liferay-portal/pull/271 Thanks.

**Comment by topolik** [comment]
ci:test:stop

**Pull request closed without merging**
