### PR TITLE
LPS-91281 Remove tests for simple integration points

### PR DESCRIPTION
**Pull request by dantewang**
https://issues.liferay.com/browse/LPS-91281

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian Actual ticket number should be LPS-91281 (https://issues.liferay.com/browse/LPS-91281)

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

Liferay Continuous Integration <notifications@github.com> 于 2019年2月27日周三
19:57写道：

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7410

**Pull request closed without merging**
