### PR TITLE
[bug fix] LPS-116325 Merge ClusterClassLoaderPool into ClassLoaderPool

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:clustering

**Comment by dantewang** [comment]
ci:test

**Comment by zhangyan0701** [comment]
ci:test:relevant results:

No unique failures. Also see in upstream or other pull requests.

**Comment by dantewang** [comment]
@zhangyan0701 Could you also take a look at the clustering result?

**Comment by zhangyan0701** [comment]
ci:test:clustering:

Failures are unrelated. They are known issue: https://issues.liferay.com/browse/LRQA-54661.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9325

**Pull request closed without merging**
