### PR TITLE
LPS-95463 Move XmlRpcParserTest to unit test

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See 

https://github.com/tinatian/liferay-portal/pull/1386
--

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7797

**Pull request closed without merging**
