### PR TITLE
LPS-122557 git commit

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:license-cluster

**Comment by tinatian** [comment]
ci:test:license

**Comment by tinatian** [comment]
@vicnate5 Could you please check the results?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian The only reason for the test failures here is because they are looking for the old message:
```
you have exceeded the maximum number of cluster nodes in cluster, overloaded nodes will be deactivated in 2 hours on cluser node
```

I will update the tests for the new wording. I also expect they need to be updated to account for the shutdown (instead of deactivate), I will need to check this locally and then send the test updates.

**Comment by tinatian** [comment]
@vicnate5 
Could you please also update the test plan to include test cases about auto shutdown? 

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian 
Test plan updated and I am running updated automation tests repeatedly at https://github.com/vicnate5/liferay-portal/pull/1712 to check for stability.

Test bundle https://drive.google.com/drive/folders/1FGBU5ANeYc_rtet4FamumVtFmrn8GhU5?usp=sharing

#### Known Issue 1
When I exceed the node limit by more than double, none of the nodes shutdown - they deactivate instead. (Node limit: 2, Nodes started 5). The 5th node never activates and remains deactivated. The other nodes will deactivate after the grace period, instead of shutting down. The first 2 nodes (that do not deactivate) continue to show the UI warning about exceeding the node count.

I added an automation test for exceeding the node limit by more than double, but because of the heaviness of running 5 tomcats, it might never be stable enough to run on CI regularly. It still makes local testing a little easier for me when needed.

#### Known Issue 2
There is some inconsistency on which node gets deactivated when using manual recovery (`license.cluster.overload.node.auto.shut.down=false`), even though we always start the nodes in the same order. Automation shows that any of the 3 nodes randomly might be the one deactivated after the grace period. The expected result is that the 3rd node deactivates, so the automation will pass in this scenario.

#### Known Issue 3
The UI error message needs to be cleaned up in wording and is not always populating variable values.

Example UI message:
"You have exceeded the maximum number of cluster nodes 2, please shut down overloaded nodes as soon as possible. Grace period started and will expire in , 4 nodes are allowed during grace period, current node is at 2, it is normal and will not be deactivated or shut down automatically after grace period"

Notice "Grace period started and will expire in [blank]". I did modify the grace period to only 5 minutes in my test build, but shouldn't the message [account for minutes left](https://github.com/tinatian/liferay-release-tool-ee/pull/74/files#diff-bd599bcf924b0ced63de886ecb6f6242a976be5d2e0c92e484cf5f6dae454c35R732)? I know that the real user period will always be 2 hours, I will try to test again with the real time period when I have a chance.

We should probably discuss the entire message wording and format with product stakeholders, and this is easy to fix in a follow up.

#### Known Issue 4
I think the error message should show up in all node console logs. We didn't enforce this before, but I expect we might have users who are relying on the console output to provide information about the cluster status. Also, it should be there [per the spec](https://docs.google.com/document/d/1ahZnkNMKWKrqTaxvCzpyZBiFd4qNChKjQbV65eMmIoo/edit#):
"When the number of cluster nodes is exceeded, the cluster will kick off the 2-hour grace period and display grace period warnings in the console and for admin users in the UI, on all nodes."

I will need to update the automation in the future to check for this.

**Pull request closed without merging**
