### PR TITLE
[bug fix] LPS-124222 Patch daisydiff to avoid NoClassDefFoundException on Websphere

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian The current daisydiff lib has a class importing classes from package com.sun. This causes exceptions on Websphere as it uses IBM JDK.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9696

**Pull request closed without merging**
