### PR TITLE
Lps 118633 lps 108614 lps 115420 2

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@GinsonRen 
Please run a diff.
Please run Login first, and if you see big regression, then no need to run other tests.
I would like to see the result by end of your day, if you can not finish all the tests, please at least get the result of Login.

Thanks.
Tina.

**Comment by GinsonRen** [comment]
Hi @tinatian , here is the result of login, other tests are running now, will upload the results later in the day.
Login:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 99057eb | 42793 | 261 | 77.6 | -
PR-1952 | - | 43359 | 275 | 825 | 1.32%

**Comment by GinsonRen** [comment]
Hi @tinatian There are the rest of result:

WC:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 99057eb | 51,973 | 691 | 208 | -
PR-1952 | - | 53146 | 731 | 217 | 2.26%

MB:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 99057eb | 16753 | 23.6 | 59.2 | -
PR-1952 | - | 17488 | 135 | 166 | 4.39%

Blog:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 99057eb | 14,209 | 42 | 120 | -
PR-1952 | - | 14873 | 177 | 251 | 4.67%

DL:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 99057eb | 24,042 | 229 | 337 | -
PR-1952 | - | 24754 | 274 | 265 | 2.96%

Wiki:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 99057eb | 14260 | 258 | 539 | -
PR-1952 | - | 14278 | 253 | 465 | 0.13%

AP:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 99057eb | 22,018 | 411 | 180 | -
PR-1952 | - | 22450 | 415 | 180 | 1.96%

**Pull request closed without merging**
