### PR TITLE
Lps 85008 Remove unnecessary PowerMockito

### PR DESCRIPTION
**Pull request by lanceji92674957**
Hi Tina,

This pull is to replace some PowerMockito that actually are just using Mockito function.

I'll send the first version of API and the replacement of the tests later.

The replacements will start with Mockito usages.

Thanks.
Lance

### CODE REVIEW

**Comment by lanceji92674957** [comment]
ci:test

**Comment by tinatian** [comment]
@lanceji92674957 I do not know why you are doing this. This is not what you showed me, the thing you show me is you can remove some of mock related annotation without failing a test, which means the annotation is not needed.

Tina.

**Comment by tinatian** [comment]
@lanceji92674957 Our goal is to remove both PowerMockito and Mockito, what you are doing now is not going to help us at all. What do you think?

**Comment by lanceji92674957** [comment]
@tinatian Since we don't have a clear solution for removing PowerMockito yet, I am trying to clear the tests with Mockito usage first. What I'm trying to do here is to get these tests separated from PowerMockito ones and ready for the new API, so after the next pull which is replacing Mockito with new API, some of these tests can be marked as done.

**Comment by lanceji92674957** [comment]
@tinatian For removing mock annotation, I was actually planning to do it with the API replacement pull, since I thought that is also some kind of change to the usage of mock. Maybe I should combine these changes together?

**Comment by tinatian** [comment]
@lanceji92674957 why not just apply your new API to current case directly? I did not see any reason you have to do this first.

**Comment by tinatian** [comment]
@lanceji92674957 The remove annotation part is actually some kind of progress since it is removing not replacing like what you did here while considering our goal is to remove, I can take that as an clean up of current usages.

I am going to close this pull. If you want to put the remove annotation part with the API, it's fine. But this is definitely not what a progress I want.

Tina

**Comment by lanceji92674957** [comment]
@tinatian ok. I'll send you the API pull later

**Pull request closed without merging**
