### PR TITLE
LPS-104545 Create specific number of content pages with web content fragment

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by slnn** [comment]
Hi @tinatian 

With this pull, set this properties "sample.sql.max.content.page.count=6" when generate data.

The page looks like this:


LPS-104545-1589

But for WebContent we have these properties:
1>sample.sql.max.journal.article.count=1
2>sample.sql.max.journal.article.size=1200
3>sample.sql.max.journal.article.version.count=1

my concern is about 2>sample.sql.max.journal.article.size, do we need keep the webcontent with fragment use the same artice size as baseline? For this pull. the artice size in page is fixed.

For the script update in https://github.com/tinatian/liferay-benchmark-ee/pull/43 to apply the property sample.sql.max.content.page.count=6

If we need apply more properties please let me know.

Thanks 
Lily

**Comment by tinatian** [comment]
Hi @pavel-savinov 
I guess this is what we want to see, right?
Screenshot

I am wondering if we need the static content from web_content.html, we do not have this in our web content test.


Tina.

**Comment by tinatian** [comment]
Hi @slnn,
The fragment sample data actually requires you have at least one journal article, please see git id (4b9bcac077d2968b8632947785a9e6324555c698), so you need to set the following journal article properties for fragment's sample data generation:

1>sample.sql.max.journal.article.count=1
2>sample.sql.max.journal.article.size=1200
3>sample.sql.max.journal.article.version.count=1

**Comment by slnn** [comment]
Hi @tinatian 

Update the property about journal in https://github.com/tinatian/liferay-benchmark-ee/pull/43

**Comment by slnn** [comment]
Hi @tinatian 

Test script be updated in https://github.com/tinatian/liferay-benchmark-ee/pull/44

For the static content from web_content.html, I used it as the keyword in the test step ViewPage 

With the data generation in this pull + test script in https://github.com/tinatian/liferay-benchmark-ee/pull/44

I encountered this issue:
The journal article only dispalyed on its own page but did not dispaly on the fragment page:

Here is the journal page:
LPS-104545-journal

Here is the fragment page:
LPS-104545-fragment


Regards
Lily

**Comment by pavel-savinov** [comment]
@slnn @tinatian There is no web content because of this commit https://github.com/brianchandotcom/liferay-portal/commit/64840babebf31acf8ee8366afdf9ff1a68ff9235
We're using the default article, so I moved fragment script after journal article one.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8520

**Pull request closed without merging**
