### PR TITLE
[portal-impl-integration] LPS-94773 com.liferay.portal.kernel.messaging.BaseMessagingConfiguratorTest

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

**Comment by dantewang** [comment]
ci:reopen

Liferay Continuous Integration <notifications@github.com> 于 2019年4月26日周五
18:13写道：

**Comment by tinatian** [comment]
Hi @dantewang ,
Can you remove the busy loop like this?
`while (ArrayUtil.isEmpty(_serviceTracker.getServices())) {
			Thread.sleep(1000);
		}`

Please send me a new pull.

Thanks.
Tina

**Pull request closed without merging**
