### PR TITLE
LPS-134082 Revert the previous commit

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Yesterday I reverted the previous commit for this ticket (so portal uses the patched version) and I didn't reproduce the issue; however, Summer told me that she and Melody reproduced the issue on latest master snapshot bundle, while another QA didn't reproduce on master. This can somehow prove that the issue is not related to the patch and I'll need to look into it further, so I think we can revert the previous fix.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang I will wait for the final fix to send this out together.

**Comment by tinatian** [comment]
Close for now and please resend with the final fix

**Pull request closed without merging**
