### PR TITLE
[Portlet 3.0 Async] LPS-81670 Part 2 Rebased

### PR DESCRIPTION
**Pull request by dantewang**
Hi @tinatian, could you prioritize this? Thanks!  cc @ngriffin7a

### CODE REVIEW

**Comment by tinatian** [comment]
@dantewang why you need to modify modules/apps/static/portal-osgi-web/portal-osgi-web-wab-extender/build.gradle?

**Comment by dantewang** [comment]
@tinatian The modification of build.gradle is in the commit which is marked "[TEMP]". This commit applies the change in https://github.com/shuyangzhou/rt.equinox.bundles/pull/17 locally , and serves as a placeholder in this PR.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/6906

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/6906

**Pull request closed without merging**
