### PR TITLE
Lps 118633 lps 108614 4

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@GinsonRen Please run a diff.

Thanks 
Tina.

**Comment by GinsonRen** [comment]
Hi @tinatian Here is the result:

Login:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 86c9e22 | 44,124 | 279 | 84 | -
PR-1933 | - | 40517 | 275 | 82.5 | -8.17%

WC:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 86c9e22 | 52,782 | 614 | 186 | -
PR-1933 | - | 48717 | 1200 | 394 | -7.70%

MB:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 86c9e22 | 16776 | 23 | 59.2 | -
PR-1933 | - | 16757 | 255 | 63.3 | -0.11%

Blog:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 86c9e22 | 14,217 | 38.2 | 118 | -
PR-1933 | - | 14014 | 84.8 | 170 | -1.43%

DL:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 86c9e22 | 24,093 | 273 | 363 | -
PR-1933 | - | 22692 | 188 | 307 | -5.81%

Wiki:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 86c9e22 | 14569 | 276 | 545 | -
PR-1933 | - | 14049 | 245 | 462 | -3.57%

AP:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 86c9e22 | 22,706 | 401 | 176 | -
PR-1933 | - | 21048 | 412 | 182 | -7.30%

**Comment by GinsonRen** [comment]
@tinatian Sorry, the baseline should be master: 86c9e22c4ba247742fce5cb5b199c6cc3389e45a.

**Pull request closed without merging**
