### PR TITLE
Lps x temp

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test

**Comment by GinsonRen** [comment]
@tinatian Result please check [here](https://docs.google.com/spreadsheets/d/1ZrU7SMqpRjbz2-8fKXC5J1s5iKkBtAHv-H4TcFyibZ4/edit#gid=0&range=C3174:C3179).

**Comment by tinatian** [comment]
Thanks @GinsonRen ! 
Could you please list details of the result in the comment next time like this https://github.com/shuyangzhou/liferay-portal/pull/9573#issuecomment-724432587?

Tina.

**Comment by GinsonRen** [comment]
@tinatian Sure.

**Pull request closed without merging**
