### PR TITLE
LPS-56227

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hey Tina,

Shuyang told me to forward this fix on to you. Let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:retest

**Comment by tinatian** [comment]
ci:retest

**Comment by AngeloJ** [comment]
ci:retest

**Comment by tinatian** [comment]
close, see https://github.com/shuyangzhou/liferay-portal/pull/1396

**Comment by tinatian** [comment]
@jonathanmccann 

I think there's something wrong with current cron exception, so I would like to confirm with you:

If you set a Kaleo job to be triggered every 10 hours after it is first triggered, and the first trigger time is 11:00

Do you want the job to be triggered at : 
21:00, 7:00 of next day.....(the interval is 10 hours, no cron exception)
or 
10:00, 20:00, 10:00 of next day....(start from 0:00 and interval is 10  hours, cron exception is 0 0 */10 * * ?)
or
21:00,  11:00 of next day....(start from 11:00, and interval is 10 hours, cron exception is 0 0 11/10 * * ?)

If what you want is the first case, then we might need to refactor current implementation.

Tina.

**Comment by jonathanmccann** [comment]
Hey @tinatian,

I did not write the fix, @SamZiemer did so I will have him look at your comment since he would know what the expected behavior should be.

Thanks!

**Comment by SamZiemer** [comment]
Hello @tinatian 

Sorry for the delay in responding, I was away on vacation all last week and have not been able to get to this until now. I believe we would want the first option, the job to trigger every 10 hours.

**Pull request closed without merging**
