### PR TITLE
Lps 88972 Remove unnecessary mocks in users-admin

### PR DESCRIPTION
**Pull request by lanceji92674957**
Hi Tina,

This pull touched one test and it's tested locally.

Thanks.

Lance

### CODE REVIEW

**Comment by tinatian** [comment]
@lanceji92674957 

Let's trigger Ci test each time to confirm that it won't affect other tests.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@Preston-Crary, please take this over!

Thanks!
Tina

**Comment by Preston-Crary** [comment]
ci:close As we talked about let's leave this one for the proxy API.

**Pull request closed without merging**
