### PR TITLE
[third-party lib] LPS-104363 Ehcache

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian There's no new version of Ehcache 2.x we can upgrade to, so I just removed the files triggering the security scanning from Ehcache jar. These files are about Restful management API and is never used by Liferay.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:backend-hypersonic

**Comment by tinatian** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/8565

**Pull request closed without merging**
