### PR TITLE
[portal-test-integration] LPS-102243 12-18

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian I removed the related things from build files, and went ahead to exclude it from Gradle-plugin-built dependencies. Otherwise our Gradle plugin will deploy a very old version of the portal-test-integration jar to portal before starting an integration test. cc @Petershin

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
Hi @vicnate5,
Could you please scan the result?

Thanks.
Tina

**Comment by vicnate5** [comment]
@tinatian looks good.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8642

**Pull request closed without merging**
