### PR TITLE
Lps 120376 lps 125421 2 1

### PR DESCRIPTION
**Pull request by slnn**
Hi @tinatian

This pull includes the changes in https://github.com/tinatian/liferay-portal/pull/2127, please see https://github.com/tinatian/liferay-portal/commit/6ae8c5d3c0a957e64669753706e21f43718c00f2

/cc @dantewang

Lily

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:relevant

**Comment by slnn** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@slnn Let's have a talk about this pull.

**Comment by slnn** [comment]
Resend in https://github.com/tinatian/liferay-portal/pull/2134

**Pull request closed without merging**
