### PR TITLE
[ResourceAction] LPS-123517 Clean up usage of deprecated property service.configurator.portlet.ids

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
@yuhai Could you double check the test result? Some of the failures seem to be caused by removal of one of the portlet.properties?

**Comment by yuhai** [comment]
@dantewang, the error is related with the fix. I will resend it.

**Pull request closed without merging**
