### PR TITLE
LPS-96289

### PR DESCRIPTION
**Pull request by topolik**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
Hi @topolik,
Could you please explain to me why this can fix the permission issue?

To me, portlet.getPrimaryKey() and portlet.getPortletId() should be same as long as you can locate an unique entry in database. portlet.getPrimaryKey() is for sure to be unique cause it is the primary key of Portlet table, that's why I use it rather than portlet.getPortletId().

Thanks.
Tina.

**Comment by topolik** [comment]
Hi,

Instance id is the answer. Permissions are tied to the full portlet id, not
root portlet id that is saved in db.


(sent from smartphone)

Dne st 19. 6. 2019 22:45 uživatel Tina Tian <notifications@github.com>
napsal:

**Comment by tinatian** [comment]
Thanks @topolik !
According to what you said, the column "portletId" in the Portlet table should be named as "rootPortletId" right?

Tina.

**Comment by topolik** [comment]
You know, historical reasons. In portlet XML it's portlet name and nobody
cares. Jorge tried to normalize it with the portlet codec so maybe he would
know better what name would fit the best.

(sent from smartphone)

Dne st 19. 6. 2019 23:12 uživatel Tina Tian <notifications@github.com>
napsal:

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7942

**Pull request closed without merging**
