### PR TITLE
[SampleSQLBUilder] LPS-83275 Support to add search page to site | 12-02

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@GinsonRen when you get the diff done please post it here.

**Comment by tinatian** [comment]
@dantewang @slnn Why we need the property for search bar? With a clean portal + clean database, is the search bar on the page or not? If we add the search bar to the page by default, is it going to cause a big regression?

Tina.

**Comment by slnn** [comment]
Hi @tinatian

Here are the origin test results  https://docs.google.com/spreadsheets/d/18SLxdJH9nqpZQo_mI3BfwY0WtTC0LECuzJSPxti4nGA/edit?usp=sharing for enabling the search bar, I can see a noticeable performance regression on WebContent and small one on DL and AssetPublisher.

We have asked @GinsonRen to rerun tests on the current head of master.

Lily

**Comment by GinsonRen** [comment]
@tinatian @slnn @dantewang Here are the result:
Login:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5b6e9a62 | 37,717 | 297 | 83.1 | -
LPS-83275 | - | 38004 | 312 | 94.7 | 0.76%


WC:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5b6e9a62 | 51,014 | 566 | 174 | -
LPS-83275 | - | 47007 | 1290 | 412 | **-7.85%**


MB:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5b6e9a62 | 16240 | 805 | 698 | -
LPS-83275 | - | 15827 | 427 | 430 | **-2.54%**


Blog:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5b6e9a62 | 13,715 | 194 | 268 | -
LPS-83275 | - | 13590 | 930 | 597 | -0.91%


DL:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add DL File | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5b6e9a62 | 24,824 | 244 | 306 | -
LPS-83275 | - | 24057 | 258 | 314 | **-3.09%**


Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5b6e9a62 | 14243 | 235 | 444 | -
LPS-83275 | - | 14074 | 245 | 457 | -1.19%


AP:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 5b6e9a62 | 19,666 | 389 | 195 | -
LPS-83275 | - | 19715 | 345 | 182 | 0.25%

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9667

**Pull request closed without merging**
