### PR TITLE
LPS-88710

### PR DESCRIPTION
**Pull request by yuhai**
Hi @tinatian 

The PR is based on https://github.com/tinatian/liferay-portal/pull/1159 and it removes the unrelated change(the commit https://github.com/tinatian/liferay-portal/pull/1159/commits/8b9efab6796371c86a0c4d95ee7686df46035788) in AbortedMultipartUploadCleaner class.

Please refer to the below test cases which I have done.
**Test Case:**
Add the below code in doReceive() method in test listener to check if scheduler can work normally.
```
Date now = new Date();
System.out.println("moduleName + className" + now.toString());
```
**Case 1**.
In module "com.liferay.blogs.web", let CheckEntryMessageListener use SchedulerEventMessageListenerWrapper (original schedulerEngineHelperImpl.register(), that is to say, do not any change in CheckEntryMessageListener class) and let LinkbackMessageListener use SchedulerEventMessageListener way (use the current fix) to test. 

1.1 In system setting UI, update the configuration to test. For example, change "Entry Check Interval" to "1", and then check the output. The output is correct. Every 1 minute will print related info from  doReceive() method.

1.2 In gogo shell
1.2.1 Stop the module: Can't see any output after 2 minute
1.2.2 Start the bundle: Can see the output. Work well.
1.2.3 Redeploy the module. Can see the output. (Work well)

**Case 2**. Using https://issues.liferay.com/secure/attachment/293702/scheduler-test-portlet-7.2.0.1.war to test SchedulerEventMessageListenerWrapper by using deploy way.
2.1 Deploy the war (simple-trigger-value=1):
Can see the output (every 1 minute) from doReceive() method of SchedulerTestMessageListener class.
2.2 Redeploy the war (simple-trigger-value=2): Can see the output (every 2 minute).
2.3 In gogo shell, stop the war bundle number,  Can't see any output after 3 minute or longer.

**Case 3.**
Based on case 1 and case 2, make sure I can see the output. In gogo shell, do action for the module “com.liferay.portal.scheduler”. 
3.1 Stop the module: Can't see any output.
3.2 Start the module: Can see the output. Work well.
3.3 Redeploy the module: Can see the output. Work well.

cc @dantewang

Thanks,
Hai

### CODE REVIEW

**Comment by yuhai** [comment]
ci:test:sf

**Comment by yuhai** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@yuhai For case 1, currently you directly modified `doReceive` of the listeners in blogs-web module to show the output, right? Could you make a dummy OSGi module jar just like the war you made, and attach it to the ticket?

Also, does `moduleName` and `className` in `System.out.println("moduleName + className" + now.toString());` represent the actual names your hardcoded when you add the outputs to the listeners?

**Comment by yuhai** [comment]
Hi @dantewang 

> currently you directly modified doReceive of the listeners in blogs-web module to show the output, right?

Yes. I will do the dummy OSGi module.

> represent the actual names your hardcoded when you add the outputs to the listeners?

Yes.

**Comment by yuhai** [comment]
Hi @tinatian and @dantewang 

I do the "com.scheduler.test.jar" in https://issues.liferay.com/secure/attachment/294319/scheduler-test-module.tar, it is the dummy osgi module for testing the osgi deploy way.

Thanks,
Hai

**Comment by tinatian** [comment]
@yuhai @dantewang 

I am looking at your first commit. It is too complex, hard to track back what changed and what not changed. Could you please separate it into different commits, for example:
1. According to the context, the type of serviceRegistration in _serviceRegistrations should be SchedulerEventMessageListenerWrapper rather than SchedulerEventMessageListener. Make this change in one commit.
2. I see you add some protected method and may want to reuse it later. Do this in one commit. Just move out the logic into a method, there should be no logic change. Sometime, to make it clear that no logic change I would do things like these two commits:
https://github.com/shuyangzhou/liferay-portal/pull/7261/commits/34457ba8c7a39b7f0fb64258834bc32ea307da58
https://github.com/shuyangzhou/liferay-portal/pull/7261/commits/27c4aa65a49270a98ad93eb8730c55d5b46f8844
3. If you want to pull out a method, make it private, only make it protected when you really need to.
4. For this method signature:
`protected SchedulerEventMessageListenerWrapper schedule(
		BundleContext bundleContext, String destinationName,
		SchedulerEntry schedulerEntry,
		SchedulerEventMessageListenerWrapper
			schedulerEventMessageListenerWrapper)`.
Why you pass in a schedulerEventMessageListenerWrapper and return one? I think what you need is just a boolean value to tell if the job is scheduled.

Please note this is a really important class for scheduler, it includes most of control logic and we did have lots of bugs in this class before. I really want to pay more attention to each line we changed, please try your best to separate it into small changes, it does not matter how many commits it will be, I want clear change log more.


Thanks.
Tina.

**Pull request closed without merging**
