### PR TITLE
LPS-111929

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang which commit in my pull is actually causing the issue? I thought I already removed it.

Tina.

**Comment by dantewang** [comment]
@tinatian It should be the first commit which changes MainServlet based on
my debugging.

Tina Tian <notifications@github.com> 于 2020年4月24日周五 11:38写道：

**Comment by dantewang** [comment]
@zhangyan0701 I can't see portal log in any of the CI links. Do you know where I can see it?

cc @tinatian

**Comment by dantewang** [comment]
@tinatian Actual log: https://testray.liferay.com/reports/production/logs/test-1-7/1587680580768/test-portal-acceptance-pullrequest%28master%29/5345/functional-smoke-jboss71-mysql57-jdk8/0/0/liferay-log.txt.gz

**Comment by dantewang** [comment]
Fetched

**Comment by dantewang** [comment]
@tinatian It's https://github.com/tinatian/liferay-portal/pull/1807/commits/7c34740a15829b60b844f51bd15f95f17d7e91ac which causes the errors. The `getPortletResourceActions(Portlet)` and `getPortletResourceActions(String)` has different underlying logic. I haven't got the time to compare the full logic between master and this pull, but I doubt just excluding the commit could make everything right (though it does eliminate the error). Will trigger a CI run to see.

**Pull request closed without merging**
