### PR TITLE
[SampleSQLBuilder] LPS-110665 Generate default release data in SampleSQLBuilder

### PR DESCRIPTION
**Pull request by dantewang**
https://issues.liferay.com/browse/LPS-110665

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
FYI @shuyangzhou Forward to Brian

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
