### PR TITLE
[SampleSQLBuilder] LPS-125473 compileInclude module jars and use them to build classpath

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Since Java's URLClassLoader does not support loading class from jars inside a jar, we extracted the bundled jars to a temp dir to build the classpath.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@slnn Merge conflicts, please resend

**Comment by slnn** [comment]
Resend in https://github.com/dantewang/liferay-portal/pull/1877

**Comment by dantewang** [comment]
See https://github.com/tinatian/liferay-portal/pull/2113

**Pull request closed without merging**
