### PR TITLE
[portal-impl-integration] LPS-96407 Move UserRatingsTest and move ratings related classes out of portal-test

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:help

**Comment by dantewang** [comment]
ci:test:relevant:norebase

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
ci:test:relevant:7e360a730eacc2350202f50d8ce11d8d1a39fa82

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7882

**Pull request closed without merging**
