### PR TITLE
[SampleSQLBuilder] LPS-109695 Update to support urlSubject in MB

### PR DESCRIPTION
**Pull request by dantewang**
Appended the meesage ID to each urlSubject to make sure they are unique as there's an unique index on groupId + this column.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@slnn Please verify this pull in the context of benchmark to make sure it doesn't break anything.

**Comment by slnn** [comment]
OK, got it

**Comment by dantewang** [comment]
@slnn Sorry I commented on the wrong pull :(

**Comment by tinatian** [comment]
see https://github.com/shuyangzhou/liferay-portal/pull/8922

**Pull request closed without merging**
