### PR TITLE
[ResourceAction][7.4 only] LPS-117531 Remove commerce special handling

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian https://issues.liferay.com/browse/COMMERCE-4874 has finished and there's no portlet 90 resource actions in Commerce. I mark 7.4-only in title because the Commerce changes are not backported.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9817

**Pull request closed without merging**
