### PR TITLE
TCK3 LPS-75370

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian 
40 failures are fixed as counted by CI result.

According to Portlet Spec 3.0, Ch 8.4,

> The portlet can find out which container runtime options are supported by the portlet container through the PortletContext.getContainerRuntimeOptions method. This method returns an enumeration of type String containing the keys of all container runtime options that the current portlet container supports.

So this method should always return an enumeration. I only found two keys in `LiferayPortletConfig` that are supported by portal.

The problem of this pull is that other people may not remember to add the key when they add support to some other runtime options. Any suggestion?

### CODE REVIEW

**Comment by tinatian** [comment]
@dantewang Please try return "_portlet.getPortletApp().getContainerRuntimeOptions()"

We collect the run time options when reading portlet xml in PortletLocalServiceImpl.readPortletXML().


Tina.

**Comment by dantewang** [comment]
@tinatian 
`PortletContext.getContainerRuntimeOptions()` is supposed to return the keys of options the portlet container supports, while `_portlet.getPortletApp().getContainerRuntimeOptions()` returns what is defined in the xml.

For example, if Liferay doesn't support `javax.portlet.renderHeaders`, the enumeration returned by `PortletContext.getContainerRuntimeOptions()` shouldn't contain it; however, if a portlet declares this option in the xml, the map returned by `PortletApp.getContainerRuntimeOptions()` will contain this key.

**Comment by tinatian** [comment]
@dantewang I am wondering if there is a way to define runtime options for portlet context? I mean does the spec say anything this kind of feature?

**Comment by dantewang** [comment]
@tinatian According to search results with the key word "runtime option", there's nothing in the Spec about how the Portlet Container should define the runtime options it supports. I think this would be implementation specific. Apache Pluto puts the keys of supported runtime options in a properties file and loads it as ResourceBundle. The properties file is packed in its jar.

**Pull request closed without merging**
