### PR TITLE
[Unit Test] LPS-85563 MethodKeyTest

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang @ChiZelin Please see my changes here : https://github.com/shuyangzhou/liferay-portal/pull/6835. Let me know if you have any questions.

Thanks.
Tina.

**Comment by dantewang** [comment]
@tinatian Got it. Will read changes merged in master and do check&refactor.

**Pull request closed without merging**
