### PR TITLE
[Bug fix] LPS-105107 SQL Server does not support drop primary key

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian For the constraint query, see comment in https://issues.liferay.com/browse/LPS-105107

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:upgrade

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8602

**Pull request closed without merging**
