### PR TITLE
[Hibernate] LPS-134886

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang Can you add an integration test to expose the issue then fix it? 
Basically you can add a integration test to check if the field value and loaded state consistent. 
Please resend.

Thanks.

**Comment by dantewang** [comment]
See https://github.com/tinatian/liferay-portal/pull/2305

**Pull request closed without merging**
