### PR TITLE
[ResourceAction] LPS-116063 MainServlet

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
Description also in https://issues.liferay.com/browse/LPS-116063

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9200

**Pull request closed without merging**
