### PR TITLE
Lps 134886 2

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:test:sf

**Comment by tinatian** [comment]
ci:test

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the test results?

Thanks
Tina

**Comment by vicnate5** [comment]
@tinatian no regressions found. Thanks for the test @dantewang!

**Comment by dantewang** [comment]
@tinatian Could you use this commit https://github.com/tinatian/liferay-portal/pull/2307/commits/4ff6ecb58c7dc13f894d04de0e635277f3d94faa for the integration test when sending out the pull? I added explicit declaration for hibernate dependency in build.gradle.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10153

**Pull request closed without merging**
