### PR TITLE
[Bug fix] LPS-127074

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@tinatian The patch was taken from the original pull request Sunny mentioned in the ticket.

**Comment by tinatian** [comment]
@dantewang For the patch, did you copy from the fix Sunny mentioned here https://issues.liferay.com/browse/LPS-127074?focusedCommentId=2380102&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2380102?

**Comment by dantewang** [comment]
@tinatian Force pushed to update the commit message.

**Comment by tinatian** [comment]
@dantewang Please rename the folder, remove the version part. 

Thanks.
Tina.

**Pull request closed without merging**
