### PR TITLE
LPS-110758 Remove portlet sandbox (SPI)

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@dantewang @yuhai 
Please also remove modules in `modules/dxp/apps/spi`
I saw there is still a usage in `BasePortalCacheManager`, please check it one more time to make sure all usages are removed.

Thanks.
Tina.

**Pull request closed without merging**
