### PR TITLE
LPS-110227

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by tinatian** [comment]
Hi @balazssk @darquesdev @Preston-Crary ,
I do not like this coupling with PortletCodeId, cause if we did this, to be consistent with other logic, we have to modify the max length (PortletIdCodec#PORTLET_INSTANCE_KEY_MAX_LENGTH) to include the segments part too, which is going to affect the max length of all portlets. 

I am not sure how this segments experience is going to be used, is it possible that any portlet may have a segement experience or this is just for some specific portlets? 

If it is only for some specific portlets, I would prefer to fix this by moving segments experience id into portlet preference instead of as part of portlet id. It seems this id stored in portlet id is always retrieved from a portlet preference. 

What do you think?

Thanks.
Tina.

**Comment by darquesdev** [comment]
Hi @tinatian and thanks for the review,

Answering your question, yes,  any portlet may be segmented. Please note that any portlet that can be added through the Layout Editor editor must be segmented. This affects both multi-instance and single-instance portlets.

We already have related bugs:
- https://issues.liferay.com/browse/LPS-111210
- https://issues.liferay.com/browse/LPS-110227
- https://issues.liferay.com/browse/LPS-106351

Meanwhile we're investigating your alternative solution.

Let me know what you think.

Thanks in advance

CC: @balazssk @pavel-savinov  @Preston-Crary

**Comment by darquesdev** [comment]
This is the original ticket: https://issues.liferay.com/browse/LPS-96730

**Comment by balazssk** [comment]
Hi @tinatian ,
I don't think that RuntimeTag (used to render the portlets in question) or a friendlyURLMapper could handle rendering portlets without a distinct portletId.

**Comment by tinatian** [comment]
Hi @balazssk ,
I can not understand what you said, could you please describe the problem in more details?

Thanks.
Tina.

**Comment by tinatian** [comment]
@balazssk I see your point now.

**Comment by balazssk** [comment]
Hi @tinatian ,
Sorry I couldn't get back to you sooner.
I think the thought process went like this:

1. Experiences are using the same plid to display different portlets on the same page for different conditions.
2. Singleton portlets aren't working due to portletId collision (https://issues.liferay.com/browse/LPS-96730)
3. Most of the code is using the portletId to look up the portlet. Including rendering and friendly urls.
4. LPS-96730 was fixed by amending the portletId.
This is of course my hypothesis, @pavel-savinov can you confirm this please?

**Comment by tinatian** [comment]
Hi @balazssk @darquesdev @pavel-savinov ,
Thanks for the explanations. I would like to suggest to do this:

1. Remove `_SEGMENTS_EXPERIENCE_` from portlet id, simply concat instance id and segments experience id, this way you will still get an unique portlet id and it can be used to render portlet.
2. Put the segments experience id into portlet preference, and retrieve it when needed, this way, you do not need to parse portlet id to get it.
3. Add checking in PortletIdCodec to avoid non-valid instance id. (I will do this after you have done the first two steps)

Reasons:
1. By checking the code used `_SEGMENTS_EXPERIENCE_`, I noticed that we actually takes the segments experience as part of instance id, it should be cause we are using it to differentiate portlets which is what instance id means to do. By using a different separator, we actually put segments experience as another part of portlet id, at the same level with instance id rather than part of instance id.
2. Make sure encoding and decoding happen in the same place. In this pull, we have segments code encoding segments experience id, but PortletIdCodec decoding. This is really bad design, hard to understand and maintain.
3. Make sure we get consistent instance id. When rendering portlet, we need the instance id to be unique (with the experience id), but when you get the instance id by Portlet#getInstanceId, you will get part of your unique instance id. This inconsistency is also a potential pitfall, and it is really hard for people to understand and diagnose the issue if they did not know this hidden rule.
4. Decoupling from PortletIdCodec.


Tina.

**Comment by darquesdev** [comment]
Hi @tinatian. 

We're going to analyze your proposal and we'll contact you again. 

Thank you very much,

David

**Comment by tinatian** [comment]
Hi guys @balazssk @darquesdev @pavel-savinov ,

As the comments above, I am going to close this pull, please resend if needed.

Thanks.
Tina.

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
