### PR TITLE
LPS-100879 String.format portal-kernel

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian We're creating sub-task per module to send the changes. This pull is for String.format usages in portal-kernel. There are two usages left untouched, one in LicenseManagerMessageType to construct some kind of JSON string, one in BaseReplacePortletId to construct SQL. In this pull, most of the usages we replaced are for Exception messages. After changes I can feel the drawback of readability. What do you think?

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@dantewang Any reason we are doing this? I feel like we had some reason for it, but can not remember.

Tina.

**Comment by dantewang** [comment]
@tinatian See https://github.com/tinatian/liferay-portal/pull/1426

The current problem we face is that there are many usages that construct a very complex string. It will be extremely unreadable after switching to string concat for those usages.

**Comment by dantewang** [comment]
Will resend

**Pull request closed without merging**
