### PR TITLE
LPS-77649

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
@tinatian 
See https://issues.liferay.com/browse/LPS-77649

This is a Windows specific issue.

> The root cause is that <replace> task uses platform-specific EOL character when performing multi-line token matching. The standalone.xml extracted from wildfly's zip archive has unix-style EOL, so the matching fails on Windows.

As a result, a critical part of the standalone.xml is not modified during `unzip-wildfly`, which causes the startup error.

There's no way to change the behavior of `<replace>` task, and the multi-line matching-replacing is  intentional, so I go with `<fixcrlf> task.

**Comment by tinatian** [comment]
@dantewang I did not see the mult-line matching-replacing you are talking about. The <replace> followed is only doing one line matching-replacing.

Tina.

**Comment by tinatian** [comment]
@dantewang never mind, I saw it.

**Comment by tinatian** [comment]
@dantewang If the root cause is like what you said, wildfly should never work on windows, why this was just found by QA?


Tina.

**Comment by dantewang** [comment]
@tinatian 
It was changed into multi-line matching on Dec 20, 2017:
https://github.com/liferay/liferay-portal/commit/4d2980b29e41bce57ddd0b46a69ec97967fe4adf#diff-d4b5e4f49a175d7de38e49921685981f

After that, all builds under Windows following "unzip-wildfly-then-ant-all" process should be broken.

Not sure why QA saw the error nearly 3 months later...

**Comment by tinatian** [comment]
@dantewang I see... I will comment on the ticket to ask QA to handle this part. 

Tina.

**Comment by tinatian** [comment]
Hi @xbrianlee 
This issue is caused by your change in LRQA-36773. The root cause is you are adding a new line in replacetoken. I am wondering if the new line is necessary, since I do not like the fix very much, but it seems if we can not remove the new line you added, we have to do this.


Thanks.
Tina.

**Comment by tinatian** [comment]
@dantewang JBoss may also fail on same reason, right? If that's the case, we may need to fix it in a general way.

Tina.

**Comment by tinatian** [comment]
@xbrianlee Please ignore my first comment, I think we need to fix this in a general way to avoid same problem in future.

@dantewang Could you please try to fix in general way, try to avoid things like this in future.

Thanks.
Tina.

**Comment by dantewang** [comment]
No, although I also added the fixcrlf to unzip-jboss, the target doesn't
use multi line matching for the portalRealm part, so it will work even
without my changes.

There are only 3 places using multiline matching in replace task: two
places to change logging output setting for unzip-jboss and unzip-wildfly,
and one place to change security (the portalRealm) setting for
unzip-wildfly.

The logging changes won't break anything if they are not applied, but the
security one causes this issue.

Tina Tian <notifications@github.com> 于 2018年3月28日周三 08:37写道：

**Comment by tinatian** [comment]
@dantewang Could you please try to see if we can fix it in a general way, so that we can avoid same thing happen in future. If not, let's check all the app servers we support if potential issue like this exist. If yes, let's fix then together.

Tina.

**Comment by dantewang** [comment]
@tinatian I wonder if there could be a general way to fix this. I will try to see if I can get a task to override `<replace>` in build-dist.xml

**Comment by dantewang** [comment]
@tinatian 
I did some extra research about the replace task:

- There's no way to disable the "using OS EOL" logic, except copying all the logic from Ant's `Replace.java` and remove the lines;
- I can combine the `FixCRLF` call together with a `Replace` call in a custom Ant task and override Ant's own `<replace>`, but since I need to taskdef it, I need to compile it. In a freshly cloned repo, it will fail.

If we go with either of the ways above, we need to do it like what we have for `<mirrors-get>` task, which means putting a checked-in jar in lib/development (see com.liferay.ant.mirrors.get.jar).

Thus, I think neither way is better than just put a piece of task call in the build file.

Any suggestion?

**Comment by tinatian** [comment]
@dantewang 
Let's create a macrodef to handle this:
1) Create a macrodef
2) In the macrodef, do the FixCRLF first then do replace
3) Apply to the one which are using multi-line token

This way we can make people understand more clearly why we have to do FixCRLF, and later if someone changed the token into multi-line, he can apply our macrodef to fix it.

Thanks.
Tina.

**Pull request closed without merging**
