### PR TITLE
[Bug fix] LPS-129966 resend

### PR DESCRIPTION
**Pull request by dantewang**
@vicnate5 Added additional fix for the leftover bat files in Windows.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
PASSED Manual testing on both Windows and Linux

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10268

**Pull request closed without merging**
