### PR TITLE
[ResourceAction] LPS-123329 Remove redundant resource action logic from kaleo-designer-web

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
@yuhai Please separate the commit into two. One for the model listener, one for the upgrade. Your comment is kind of confusing as LPS-81732(5178c295bfcbef5cfc7a611df46d05b53aefd1fc) only modified model listener.

Please modify and resend.

Thanks.

**Pull request closed without merging**
