### PR TITLE
[deprecation] LPS-106573 Remove SubscriptionSender.replaceContent()

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian I went with another way to remove the deprecated method. By reading the code, the processMailMessage() way should produce identical result for subject and body.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@vicnate5 Could you please scan the result?

Thanks.
Tina.

**Comment by vicnate5** [comment]
@tinatian Looks good

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8694

**Pull request closed without merging**
