### PR TITLE
LPS-91612 SampleSQLBuilder time zone

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Besides what's mentioned before, I also made the time zone ID parsing more strict using java.time.ZoneId.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:reopen

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7500

**Pull request closed without merging**
