### PR TITLE
LPS-102427 Set PropsKeys.SCHEDULER_ENABLED to True because of the restriction imposed here https://github.com/liferay/liferay-portal/blob/9ccf657b00c67feee6977ebb1f29a1b74124ba71/portal-test/src/com/liferay/portal/kernel/test/rule/SynchronousDestinationTestRule.java#L153, some cases the tests are running asynchronously causing failures.

### PR DESCRIPTION
**Pull request by inacionery**

### CODE REVIEW

**Comment by tinatian** [comment]
Hi @inacionery ,
As told by @xbrianlee, the issue fixed by this pull can not be reproduced, so I am going to close this pull.

Thanks.
Tina.

**Comment by barrosdennys** [comment]
Hi @tinatian , 
If you observe the history of these failures, they occurred again on Oct 4th (after Inacio's commits)

https://testray.liferay.com/home/-/testray/cases/440041348
(failed again on _out 4, 2019 4:54 PM_ , on CE Development Acceptance (master)) - [details](https://testray.liferay.com/home/-/testray/case_results/814625885?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F440041348%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D440041348%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc)

So, this continues to be an intermittent issue and I believe that @inacionery 's commits are still valid.

**Comment by inacionery** [comment]
ci:reopen

**Comment by tinatian** [comment]
Hi @inacionery ,
Your change in this pull is actually not changing anything at all:
1. By default, scheduler is enabled for CI integration test. The link you provided is from test tray, not a normal ci test, I am wondering if there is something different from normal ci test?
2. By default, you do not need to use @Sync cause it will always swap the destination, please see https://issues.liferay.com/browse/LPS-76856.

According to the new error you linked, I also did not see anything related to scheduler/message bus destination like the old one. The random failure may cause by others.

Anyway, this pull should not be the right fix for the issue, so I am going to close it. 

I know it is hard to figure out the root cause of a random failure on ci, if you need any help with it, please let me know.


Tina.

**Comment by tinatian** [comment]
@inacionery 
Forgot to mention, the checking for scheduler has been removed in LPS-102626(b3539a07962174717fc45f9978f45f976ae37fad)

Tina

**Comment by inacionery** [comment]
Hey @tinatian,

I didn't about https://github.com/tinatian/liferay-portal/commit/b3539a07962174717fc45f9978f45f976ae37fad 

Thanks!

**Pull request closed without merging**
