### PR TITLE
LPS-74720

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian The root cause is again the usage of File.toURL(). I can't pass the encoded path string as the string is also used to create file in Jasper. There's an SF error of the java source code I copied from the Jasper source code. Should we SF this file or exclude it?

### CODE REVIEW

**Comment by dantewang** [comment]
ci:retest

**Comment by tinatian** [comment]
@dantewang I did not see the SF error you are talking about according to the CI result. Are we still having the problem?

Tina

**Comment by dantewang** [comment]
@tinatian There was an issue with master build yesterday causing all PR testing fail. This pull actually didn't get tested. Will resend.

**Comment by dantewang** [comment]
@tinatian Hi Tina, I asked Hugo and he said third-party java files shouldn't be SFed. He will address the SF issue later and I will resend after that.

**Pull request closed without merging**
