### PR TITLE
[Log4J] LPS-128599 Refactor CaptureAppender to avoid expose Log4J API

### PR DESCRIPTION
**Pull request by dantewang**
@hhuijser We deprecated some `Closeable` classes with new ones. SF records such classes in `closeable-type-names.json`. Should the class names of the deprecated ones in this file be directly replaced with new ones?

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9823

**Pull request closed without merging**
