### PR TITLE
[Bug fix] LPS-121334

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@tinatian Other team patched Httpclient 3.1 and applied it to sharepoint-soap-repository.

**Comment by tinatian** [comment]
@dantewang Wrong reference, please see https://github.com/shuyangzhou/liferay-portal/pull/9852.

**Pull request closed without merging**
