### PR TITLE
[SampleSQLBuilder] LPS-94526 Add missing data for comment related AssetEntry

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This is only needed for master, shouldn't be backported.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@tinatian To be clear, by "shouldn't be backported" I mean "to 7.1.x and 7.0.x".

**Comment by tinatian** [comment]
@dantewang @slnn 
Do we really need this?
I started head of master from an empty database, add an blog entry and add comment, I did not see a new entry in ClassName_ with name like what we trying to add "firstClazz.getName()_secondClazz.getName" in the pull.


Tina.

**Comment by slnn** [comment]
Hi Tina,
I checked this with clean database on this version:8998a7fd32a49a516d7543bbbbb50b27b60c4f3c, add blog entry and then add a comment to the blog entry, I can see the entry like "com.liferay.message.boards.model.MBDiscussion_com.liferay.blogs.model.BlogsEntry" be inserted in he DB table ClassName_, I will double check on today's head of master.

For Blog:
select * from ClassName_ where value='com.liferay.message.boards.model.MBDiscussion_com.liferay.blogs.model.BlogsEntry';

For Wiki:
select * from ClassName_ where value='com.liferay.message.boards.model.MBDiscussion_com.liferay.wiki.model.WikiPage';

Lily

**Comment by slnn** [comment]
Hi Tina,

I double checked with clean DB on today's head of master(GitId:9532a33bbc4eb7aaca3104e56a9693b1ba54ee84), I can see the entry like "com.liferay.message.boards.model.MBDiscussion_com.liferay.blogs.model.BlogsEntry" be inserted in he DB table ClassName_ when add a comment to blog entry, it will happen only once on the first time to add comment to blog entry.

I have resend a pull to fix one hardcode way issue about the changes in https://github.com/dantewang/liferay-portal/pull/1111

Lily

**Comment by dantewang** [comment]
@tinatian Resent at https://github.com/tinatian/liferay-portal/pull/1352

**Pull request closed without merging**
