### PR TITLE
LPS-113963 clean up Akismet

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@tinatian I still can't enable build of Akismet modules. It has a lot of issues. I just cleaned up what I saw.

**Comment by tinatian** [comment]
@dantewang what do you mean by "can't enable build of Akismet modules"? It won't be deployed by default cause by missing of build trigger. What are the issues you are talking about?

Tina.

**Comment by tinatian** [comment]
See https://github.com/tinatian/liferay-portal/pull/1831

**Comment by dantewang** [comment]
@tinatian Yeah. I mean I added build trigger at first and saw many failures on CI. I only fixed some (e.g. the dynamic query) by the end of yesterday.

**Comment by tinatian** [comment]
@dantewang Can you work on my pull and see if there are more failures?

**Comment by dantewang** [comment]
@tinatian Sure.

**Pull request closed without merging**
