### PR TITLE
[Log4J] LPS-129717

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:smoke

**Comment by dantewang** [comment]
@tinatian I tested localy and the content of log files were normal.
@vicnate5 The current master has startup failure on commerce modules, which will fail a lot of CI tests. The resolve failures of `com.liferay.headless.commerce.punchout.impl` are irrelevant of this pull.

**Comment by jpince** [comment]
ci:test:relevant

**Comment by jpince** [comment]
forwarded to https://github.com/shuyangzhou/liferay-portal/pull/9884

**Pull request closed without merging**
