### PR TITLE
LPS-105694 Split DataFactory

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang @slnn 
1) I do not like so many properties added to the freemarker context. Please add a factory class, and generate the concrete factories at run time, and make sure each concrete factory is a singleton.
For example, in asset.ftl, I need assetDataFactory, then I retrieve it first from factory class and use it.
2) Please try to make the BaseDataFactory only contain common logic which are going to be used by concrete factory. Move the data like _classNameModels out of it.

Please resend.

Thanks.
Tina.

**Comment by slnn** [comment]
OK, will resend later.

**Pull request closed without merging**
