### PR TITLE
[test fix] LPS-106782 Fix compile errors caused by LPS-104913

### PR DESCRIPTION
**Pull request by dantewang**
https://issues.liferay.com/browse/LPS-106782

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang @ChiZelin Please see my fix https://github.com/shuyangzhou/liferay-portal/pull/8703.

Tina.

**Comment by dantewang** [comment]
@tinatian Thanks!

**Pull request closed without merging**
