### PR TITLE
[SampleSQLBuilder] LPS-113497 Content page homepage

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@dantewang @slnn 
The `heading.html` has similar content with https://github.com/liferay/liferay-portal/blob/master/modules/apps/fragment/fragment-collection-contributor/fragment-collection-contributor-basic-component/src/main/resources/com/liferay/fragment/collection/contributor/basic/component/dependencies/heading/index.html.

Same thing with other files you added.

Could you please try to reuse the files from portal instead of adding to sample sql builder? It would be a lot of maintenance work if we have separate files in sample sql builder.

Please resend.

Thanks.
Tina.

**Comment by slnn** [comment]
Resend in https://github.com/dantewang/liferay-portal/pull/1975

**Pull request closed without merging**
