### PR TITLE
Lps 119013 lps 118633 lps 108614

### PR DESCRIPTION
**Pull request by tinatian**

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@GinsonRen Please run a diff. Please run login first, and if you see huge regression, no need to run others, gather the cpu profiles before and after.

Thanks.
Tina.

**Comment by tinatian** [comment]
@GinsonRen I just pushed two commits, please run a diff, same requirements as earlier.

Thanks.
Tina.

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by GinsonRen** [comment]
Got it, will run on next Monday.

**Comment by tinatian** [comment]
@GinsonRen 
If you have run it but not finished all the tests, just show me the results you have.
If you have not run it yet, let's wait for Monday.

Thanks.
Tina.

**Comment by tinatian** [comment]
@vicnate5 Could you please help me verify the functional failures?

Thanks
Tina.

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@tinatian Real failures here with Import of some existing LAR test artifacts.

A few examples:
1. Users and Organizations https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/dependencies/organizations-7.0.lar
2. Web Content https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/dependencies/space-web-content.lar
3. Web Content https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/dependencies/content-display-templates.lar

I will reach out to the teams who created these. Do they need to be regenerated based on your change?

**Comment by tinatian** [comment]
@vicnate5 No, my changes already included all the generated files.

**Comment by vicnate5** [comment]
These are LARs exported from previous portal code, should we consider this a bug that they do not import anymore?

**Comment by vicnate5** [comment]
@tinatian Example error on import
https://testray.liferay.com/reports/production/logs/test-1-14/1597380972056/test-portal-acceptance-pullrequest(master)/6969/functional-tomcat90-mysql57-jdk8/88/0/liferay-log.txt.gz

**Comment by GinsonRen** [comment]
Hi @tinatian Here is the result:
Login:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Logout | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 35ac960 | 44,187 | 275 | 83 | -
PR-1940 | - | 44842 | 272 | 82.2 | 1.48%

WC:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 35ac960 | 52,776 | 626 | 191 | -
PR-1940 | - | 52197 | 653 | 201 | -1.10%

MB:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add MB Thread | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 35ac960 | 16753 | 23.3 | 59.6 | -
PR-1940 | - | 16763 | 22.2 | 56.8 | 0.06%

Blog:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 35ac960 | 14,199 | 38.2 | 117 | -
PR-1940 | - | 14229 | 383 | 119 | 0.21%

DL:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Blog Entry | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 35ac960 | 14,199 | 38.2 | 117 | -
PR-1940 | - | 14229 | 383 | 119 | 0.21%

Wiki:

Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of Add Wiki Page | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 35ac960 | 14346 | 246 | 552 | -
PR-1940 | - | 13972 | 248 | 579 | -2.61%
PR-1940 | - | 14011 | 267 | 612 | -2.34%
PR-1940 | - | 14181 | 290 | 659 | -1.15%

AP:
Portal Version | Git Id | Session Count | Mean Time of Login | Mean Time of View Page with Filter | Session Count Change （%）
-- | -- | -- | -- | -- | --
BaseLine | 35ac960 | 22,492 | 400 | 176 | -
PR-1940 | - | 22470 | 409 | 178 | -0.10%

**Comment by vicnate5** [comment]
@tinatian Echo team is fixing the failing tests to manually create the data for export instead of using an old LAR file, this should prevent these failures in the future (https://issues.liferay.com/browse/LRQA-61022).

I do not expect this fix to be finished today. If this code is urgent, I can disable the test cases. Otherwise I would rather wait for the test changes so we can merge with full testing.

**Pull request closed without merging**
