### PR TITLE
LPS-103577 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Rebased on https://github.com/tinatian/liferay-portal/pull/1684

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@tinatian startup still fails on CI. Extra output:
```
     [exec] ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
     [exec] 20:06:34,536 INFO  [com.liferay.portal.search.elasticsearch7.internal.sidecar.SidecarProcessCallable@7ee96c1c[-Xms1g -Xmx1g -XX:+AlwaysPreTouch -Des.distribution.flavor=default -Des.distribution.type=tar -Des.path.conf=/opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.17/temp/20200110200633474UAKBPOKX/config -Des.path.home=/opt/dev/projects/github/liferay-portal/bundles/elasticsearch7 -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dio.netty.allocator.type=unpooled -Dio.netty.allocator.numDirectArenas=0 -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.17/temp/20200110200633474UAKBPOKX -Djava.security.policy=/opt/dev/projects/github/liferay-portal/bundles/tomcat-9.0.17/temp/20200110200633474UAKBPOKX/security.policy -Djna.nosys=true]-][NotifyParentProcessCallable:38] Starting sidecar
     [exec] ERROR StatusLogger No Log4j 2 configuration file found. Using default configuration (logging only errors to the console), or user programmatically provided configurations. Set system property 'log4j2.debug' to show Log4j 2 internal initialization logging. See https://logging.apache.org/log4j/2.x/manual/configuration.html for instructions on how to configure Log4j 2
     [exec] [2020-01-10T12:06:35,985][WARN ][o.e.d.b.Bootstrap        ] [liferay]future versions of Elasticsearch will require Java 11; your Java version from [/opt/java/jdk1.8.0_121-x64/jre] does not meet this requirement
     [exec] 20:06:36,532 ERROR [main][ElasticsearchConnectionManager:93] bundle com.liferay.portal.search.elasticsearch7.impl:2.0.0 (235)[com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionManager(650)] : The activate method has thrown an exception 
     [exec] java.lang.IllegalStateException: Unable to get network host address
     [exec] 	at com.liferay.portal.search.elasticsearch7.internal.sidecar.Sidecar.getNetworkHostAddress(Sidecar.java:112)
     [exec] 	at com.liferay.portal.search.elasticsearch7.internal.connection.SidecarElasticsearchConnection.lambda$createRestHighLevelClient$0(SidecarElasticsearchConnection.java:64)
     [exec] 	at com.liferay.portal.search.elasticsearch7.internal.util.ClassLoaderUtil.getWithContextClassLoader(ClassLoaderUtil.java:34)
     [exec] 	at com.liferay.portal.search.elasticsearch7.internal.connection.SidecarElasticsearchConnection.createRestHighLevelClient(SidecarElasticsearchConnection.java:61)
     [exec] 	at com.liferay.portal.search.elasticsearch7.internal.connection.BaseElasticsearchConnection.connect(BaseElasticsearchConnection.java:45)
     [exec] 	at com.liferay.portal.search.elasticsearch7.internal.connection.SidecarElasticsearchConnection.connect(SidecarElasticsearchConnection.java:46)
     [exec] 	at com.liferay.portal.search.elasticsearch7.internal.connection.ElasticsearchConnectionManager.activate(ElasticsearchConnectionManager.java:187)
```

**Comment by tinatian** [comment]
Rerun here https://github.com/tinatian/liferay-portal/pull/1689 with more logging

**Pull request closed without merging**
