### PR TITLE
[SampleSQLBuilder] LPS-83275 Search bar | resend

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Resend as Brian commented https://github.com/brianchandotcom/liferay-portal/pull/96923#issuecomment-745757429

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:forward

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
ci:forward

**Pull request closed without merging**
