### PR TITLE
LPS-67993 Making sure the old service registration is unregistered when registering a new one for the same listener. This was causing the scheduled job not to unregister after a change in the interval.

### PR DESCRIPTION
**Pull request by sergiogonzalez**
Hey Tina,

I'm sending this to you per Mike's comment https://github.com/mhan810/liferay-portal/pull/1292#issuecomment-270647350

Thx!

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
cc/ @4lejandrito

**Comment by tinatian** [comment]
Hi @sergiogonzalez,
 
Do you have a way to reproduce the issue you are fixing by this pull? If you only made an change in internal, it should have nothing to do with the listeners, I am thinking this might not be the root cause. Could you please send me the steps to reproduce it?

Thanks.
Tina.

**Comment by sergiogonzalez** [comment]
Hey @4lejandrito can you provide @tinatian with the details she's asking? I think that they are in the LPS ticket, right?

**Comment by 4lejandrito** [comment]
Hi @tinatian, I described the issue in Jira last week. Please have a look over [there](https://issues.liferay.com/browse/LPS-69996) and let me know if you still need more information.

**Comment by tinatian** [comment]
Please see https://github.com/sergiogonzalez/liferay-portal/pull/3706

**Pull request closed without merging**
