### PR TITLE
LPS-73275 PortalCacheIndexer

### PR DESCRIPTION
**Pull request by Preston-Crary**
Sorry about the pull request spam, should have full test coverage again.

[One change](https://github.com/tinatian/liferay-portal/blob/7e2acc6ece19bb0b2d32735c52e99de7b9a57a70/portal-kernel/src/com/liferay/portal/kernel/cache/index/PortalCacheIndexer.java#L181-L184) that I had to make for full test coverage I really didn't like. I would have preferred to put this is a static block and throw an ExceptionInInitializerError but then I had some unreachable lines of code in the catch block.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@tinatian why'd you close the pull?  Did you fix this in another way?

**Comment by tinatian** [comment]
@Preston-Crary Sorry, I think I closed it by mistake, something wrong with my master branch, so I made some change to my git and all the pulls are closed.

**Comment by Preston-Crary** [comment]
Rebased and resolved the conflict.

**Comment by tinatian** [comment]
Start reviewing, close for now to trigger ci test.

**Pull request closed without merging**
