### PR TITLE
[Portlet 3.0 Async] LPS-81670 Initial implementations

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
cc @ngriffin7a

**Comment by dantewang** [comment]
@tinatian This is basically a bare bone which simply delegates to servlet async. We'll add detailed implementations step by step in follow-up PRs.

cc @ChiZelin

**Comment by tinatian** [comment]
@dantewang I did not see any difference compared with last pull. Even if this is just bare bone, it should be right and followed the spec. It does not make sense to me to commit something wrong and modify it later.

Could you please fix and resend?

Thanks.
Tina.

**Comment by ChiZelin** [comment]
@tinatian We added the logic as follow in ResourceRequestImpl.startPortletAsync:
```
if (_portletAsyncContext != null) {
	return _portletAsyncContext;
}
```

**Comment by tinatian** [comment]
@ChiZelin Sorry, my bad, might look at the old version.

**Comment by tinatian** [comment]
@dantewang @ChiZelin 
For PortletAsyncContextImpl.java,
We should also implement isCalledDispatch(), right?
In complete(), you updated state "_calledComplete = true" first, and then do complete. I think usually we do things first then update status, any reason we did this?

For ResourceRequestImpl.java,
in startPortletAsync(), same status update issue as above, this one should have problem that is httpServletRequest.startAsync() will throw exception, but you updated status first.

Also, could you please try to send a little bit more at one time? so that I would have more clear what you are trying to do.

Tina.

**Pull request closed without merging**
