### PR TITLE
LPS-91921 | master

### PR DESCRIPTION
**Pull request by vicnate5**
Alternate solution to mysql driver issue

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:reopen

**Comment by vicnate5** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
ci:reopen

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7471

**Pull request closed without merging**
