### PR TITLE
[Bug fix] LPS-132399 Make HibernateStatisticsService a DynamicMBean and publish

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian When the class being registered as management bean implements `DynamicMBean`﻿ instead of being a POJO, it must implement the interface-defined methods to provide information that JMX needs. So I have to create a `StandardMBean` for delegation.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10027

**Pull request closed without merging**
