### PR TITLE
LPS-145166

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian ,

As we discussed yesterday, I have removed unused file "wsadmin.py",  based on commit e930ab6f2b44e116a95a6390366a6c88d83d127e, see LPS-61201.
Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by tinatian** [comment]
@jeffwu0724 Please resend this change with the removal of other websphere related properties and similar logic in build.xml.


Tina.

**Comment by jeffwu0724** [comment]
> @jeffwu0724 Please resend this change with the removal of other websphere related properties and similar logic in build.xml.
> 
> Tina.

got it, then I will wait for Victor's verification, and submit them all together as a commit

**Pull request closed without merging**
