### PR TITLE
[Bug fix] LPS-129172 Upgrade jackson

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@zhangyan0701 Could you review the test failures? Yesterday's run didn't show some of these failures: https://github.com/dantewang/liferay-portal/pull/2047#issuecomment-892526924

**Comment by zhangyan0701** [comment]
This is no unique failures.

**Comment by dantewang** [comment]
@yuhai Please rebase and resend this pull to Tina, thanks!

**Pull request closed without merging**
