### PR TITLE
LPS-146150

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi @tinatian,

I have removed unused properties "Zip.file.name.encoding", and updated to propskeys.java, propsvalues.java and verifyproperties.java.

"ZIP_FILE_NAME_ENCODING" was added in commit 6f377e083e0b3ce6b5c19fa00f5e10b9fc0fd7f6, see LPS-76719, and it was used in ZipReaderImpl.java.
It is deleted in commit 015acd962f6f1cdaa1621f5d52ff60384288eb90, see LPS-111972

Thanks for checking.

Best,
Jeff

### CODE REVIEW

**Comment by jeffwu0724** [comment]
ci:test:sf

**Comment by jeffwu0724** [comment]
ci:test:relevant

**Comment by jeffwu0724** [comment]
ci:test

**Comment by tinatian** [comment]
@jeffwu0724 This pull looks good to me, please put it into your list. I am going to close this pull. 

Thanks.
Tina.

**Pull request closed without merging**
