### PR TITLE
LPS-145946 Remove xalan.jar

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This PR is on top of https://github.com/tinatian/liferay-portal/pull/2498 and includes xalan.jar removal.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/295

**Pull request closed without merging**
