### PR TITLE
[Deprecation] LPS-106008 Clean up used deprecations, portal-kernel part8

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian This is the easy part of what we talked about these days.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8661

**Pull request closed without merging**
