### PR TITLE
[SampleSQLBuilder] LPS-136758 generate PortalPreferences for company

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
@tinatian `CompanyThreadLocal._setCompanyId` method fetches the default user of the company.

During this fetch, `PortalPreferencesLocalServiceImpl.getPortalPreferences()` will be called using the company id, and if the `PortalPreferences` does not exist, the method will try to add a new one.

The adding operation starts a new transaction, during which `com.liferay.portal.spring.hibernate.LastSessionRecorderUtil#syncLastSessionState` clears the session's state, including the `entityEntries` map in the `PersistenceContext` of the session. This results in the assertion error in the post load event listener we encounter -- the map is empty, so the listener can't get the `EntityEntry` for the entity (`UserImpl` object).

When starting portal on a clean database, portal creates the default company with its `PortalPreferences`, and then queries the company data. This way there's no "adding" so that this error doesn't happen...

I asked Lily to generate this data to get a quick fix. But I wonder if this means something wrong in the data/transaction handling?

For stack trace of the "clear" of the session, see comment in https://issues.liferay.com/browse/LPS-136758

**Comment by dantewang** [comment]
ci:stop

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/10212

**Pull request closed without merging**
