### PR TITLE
LPS-89050 test module for intergation point | 2

### PR DESCRIPTION
**Pull request by dantewang**

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test:relevant

Liferay Continuous Integration <notifications@github.com> 于 2019年1月15日周二
18:48写道：

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/7267

**Pull request closed without merging**
