### PR TITLE
LPS-85799 Semantic versioning.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by tinatian** [comment]
@marianoalvarosaiz 
Could you please add a checking in the activate method of ClusterSchedulerEngineConfigurator, to avoid creating an instance of ClusterSchedulerEngine when scheduler is not enabled? This should fix the endless loop you are talking about in the ticket.

Also, this way we do not need to change the api which causes an major version bump. 


Thanks.
Tina.


Thanks.
Tina.

**Comment by marianoalvarosaiz** [comment]
Thanks @tinatian,
 that solves the NullPointerException loop, but what about customer that configures one node with scheduler.enabled to true, the other to false, and at the end, with a couple restarts the first one "looses" its jobs. Shouldn't we advise them that it isn't a valid configuration? If we fix the NullPointerException and don't show any other information they are going to have an incorrect configuration based on our design, but they don't have to know how the code works and that's why often there are support tickets with this scenario, where they report it as a situation where jobs are lost.

**Comment by tinatian** [comment]
@marianoalvarosaiz 
While you are doing the checking, you can log warning saying current node does not enable scheduler and may cause error, they should enable scheduler and restart.

What do you think?

Tina.

**Comment by marianoalvarosaiz** [comment]
Ok @tinatian, sounds good, I'll do so and send a new PR. Thanks!

**Comment by tinatian** [comment]
@marianoalvarosaiz 
Basically, I prefer to log message to people instead of checking other cluster nodes to valid if the configuration is right or wrong. Doing this is too much to cluster framework, I would like to involve people to handle things like this.

Tina.

**Comment by tinatian** [comment]
Thanks @marianoalvarosaiz ! I will close this pull.

**Pull request closed without merging**
