### PR TITLE
LPS-120753 Upgrade MySQL | resend

### PR DESCRIPTION
**Pull request by dantewang**
@tinatian Resend as discussed this morning. Please note that we only put Class.forName() in initDataSource() and swallow ClassNotFoundException since it's enough to judge whether MySQL driver is available.

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test:sf

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
ci:test

**Comment by tinatian** [comment]
https://github.com/shuyangzhou/liferay-portal/pull/9537

**Pull request closed without merging**
