### PR TITLE
[bug fix] LPS-107011 Modules compile failure in PacketAspect.java

### PR DESCRIPTION
**Pull request by dantewang**
https://issues.liferay.com/browse/LPS-107011

### CODE REVIEW

**Comment by dantewang** [comment]
ci:test

**Comment by dantewang** [comment]
ci:test:relevant

**Comment by dantewang** [comment]
It compiles successfully. @vicnate5 Do you know if there's any test batch that covers its functionality?

**Comment by vicnate5** [comment]
@dantewang no specific test batch I can find.

@tinatian Test results look good on this PR.

**Comment by tinatian** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/8746

**Pull request closed without merging**
